### ISSUE TITLE
Dead code elimination failure in torch-mlir's canonicalizer

### ISSUE THREAD

**Issue by Vremold** [llvm/torch-mlir#1041]
Recently, I use the torch-mlir to get mlir from torchscript object graph. However, the ouput mlir has some dead codes uneliminated. Here is an example:
The input mlir is:
```
func.func @test(%arg0: !torch.vtensor<[4],f32>, %arg1: !torch.vtensor<[4], f32>) -> !torch.vtensor<[4],f32> {
    %int1 = torch.constant.int 1
    %0 = torch.prim.NumToTensor.Scalar %int1 : !torch.int -> !torch.vtensor<[],si64>
    %1 = torch.aten.add.Tensor %arg0, %arg1, %int1 : !torch.vtensor<[4],f32>, !torch.vtensor<[4],f32>, !torch.int -> !torch.vtensor<[4],f32>
    return %arg0 : !torch.vtensor<[4],f32>
}
```
The output mlir is: (using `torch-mlir-opt -canonicalize` command line)
```
func.func @test(%arg0: !torch.vtensor<[4],f32>, %arg1: !torch.vtensor<[4],f32>) -> !torch.vtensor<[4],f32> {
    %int1 = torch.constant.int 1
    %0 = torch.prim.NumToTensor.Scalar %int1 : !torch.int -> !torch.vtensor<[],si64>
    %1 = torch.aten.add.Tensor %arg0, %arg1, %int1 : !torch.vtensor<[4],f32>, !torch.vtensor<[4],f32>, !torch.int -> !torch.vtensor<[4],f32>
    return %arg0 : !torch.vtensor<[4],f32>
}
```
`%0` and `%1` are never used, thus dead codes. But their ops are not marked with 'NoSideEffect', causing them not properly eliminated by the canonicalizer pass. Is it a bug, or just a feature?

**Comment by silvasean** [comment]
You will need to run https://github.com/llvm/torch-mlir/blob/main/build_tools/update_torch_ods.sh and rebuild to see the change.

**Comment by Vremold** [comment]
> %1 can throw an error in some cases of shape mismatch, so it is not trivial to remove without more complicated logic -- we could remove it here in theory though.
> 
> We should mark torch.prim.NumToTensor as NoSideEffect though. Can you add `traits=["NoSideEffect"]` here and see if it fixes your issue?
> 
> https://github.com/llvm/torch-mlir/blob/9017be9e9e6b4a1573dd75638ad085ae55d259c4/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py#L578

I have already done the experiments, that fix my issue. Thanks! But I'm still wondering how to handle with other ops with similar traits. I'll be glad if I could know what's the plan of the community.

**Comment by Vremold** [comment]
> Which other ops do you have in mind? I think that all ops that are NoSideEffect should have that trait. We might want to add a custom EraseIfDead trait that is a bit more general than NoSideEffect.

There are lots of op in the "generatedTorchOps.td" with only "ReadOnly" trait, but no "NoSideEffect" trait. I guess that the same problem may exists for them, too (if not taken the potential validation check into consideration). AtenAddTensorOp and PrimNumToTensorScalarOp are just examples. It's great to add a custom "EraseIfDead" trait for these ops. Thanks a lot for your help!

**Comment by silvasean** [comment]
ReadOnly is different from NoSideEffect -- a ReadOnly op can throw an error.

**Comment by Vremold** [comment]
> ReadOnly is different from NoSideEffect -- a ReadOnly op can throw an error.

I know that. But thanks for your explanation anyway.
