### ISSUE TITLE
run update_torch_ods.sh && update_shape_lib.sh failure du to `aten.zero`

### ISSUE THREAD

**Issue by YellowHCH** [llvm/torch-mlir#1060]
I'm trying to run update_torch_ods.sh to add some new op. It works well before I sync the latest commit 479a8a89631c8.
An error occurred after synchronization as:
`KeyError: 'aten::zero : (Tensor) -> (Tensor)'`

`aten.zero` was not found at JITOperatorRegistryDump.txt, It seems registry not contain `aten.zero`

**Comment by ramiro050** [comment]
Hi @YellowHCH,

I was unable to recreate your issue on my machine. It's possible that this is an issue with the pytorch version you're using, since the changes to the `aten::zero` op were only recently made. Can you try updating your pytorch version to the latest nightly?

**Comment by YellowHCH** [comment]
> Hi @YellowHCH,
> 
> I was unable to recreate your issue on my machine. It's possible that this is an issue with the pytorch version you're using, since the changes to the `aten::zero` op were only recently made. Can you try updating your pytorch version to the latest nightly?

Should we compile pytorch from latest source code or just use mlir_vevn ? I am currently using mlir_venv to get libtorch.

**Comment by YellowHCH** [comment]
> > Hi @YellowHCH,
> > I was unable to recreate your issue on my machine. It's possible that this is an issue with the pytorch version you're using, since the changes to the `aten::zero` op were only recently made. Can you try updating your pytorch version to the latest nightly?
> 
> Should we compile pytorch from latest source code or just use mlir_vevn ? I am currently using mlir_venv to get libtorch.

Both are ok, I was not at latest libtorch
