### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wm901115nwpu** [llvm/torch-mlir#1068]
[56/388] Building CXX object tools/torch-mlir/lib/Dialect/Torch/IR/CMakeFiles/obj.TorchMLIRTorchDialect.dir/TorchDialect.cpp.o
FAILED: tools/torch-mlir/lib/Dialect/Torch/IR/CMakeFiles/obj.TorchMLIRTorchDialect.dir/TorchDialect.cpp.o
ccache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DGTEST_HAS_RTTI=0 -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/Users/unicorn/MyCodes/torch-mlir/build/tools/torch-mlir/lib/Dialect/Torch/IR -I/Users/unicorn/MyCodes/torch-mlir/lib/Dialect/Torch/IR -I/Users/unicorn/MyCodes/torch-mlir/build/include -I/Users/unicorn/MyCodes/torch-mlir/externals/llvm-project/llvm/include -I/Users/unicorn/MyCodes/torch-mlir/externals/llvm-project/llvm/../mlir/include -I/Users/unicorn/MyCodes/torch-mlir/build/tools/mlir/include -I/Users/unicorn/MyCodes/torch-mlir/include -I/Users/unicorn/MyCodes/torch-mlir/build/tools/torch-mlir/include -I/Users/unicorn/MyCodes/torch-mlir/lib/Dialect/Torch/IR/Users/unicorn/MyCodes/torch-mlir/externals/llvm-project/llvm/../mlir/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk  -fno-exceptions -fno-rtti -UNDEBUG -std=c++14 -MD -MT tools/torch-mlir/lib/Dialect/Torch/IR/CMakeFiles/obj.TorchMLIRTorchDialect.dir/TorchDialect.cpp.o -MF tools/torch-mlir/lib/Dialect/Torch/IR/CMakeFiles/obj.TorchMLIRTorchDialect.dir/TorchDialect.cpp.o.d -o tools/torch-mlir/lib/Dialect/Torch/IR/CMakeFiles/obj.TorchMLIRTorchDialect.dir/TorchDialect.cpp.o -c /Users/unicorn/MyCodes/torch-mlir/lib/Dialect/Torch/IR/TorchDialect.cpp
/Users/unicorn/MyCodes/torch-mlir/lib/Dialect/Torch/IR/TorchDialect.cpp:67:22: error: no matching function for call to 'generatedTypeParser'
  auto parseResult = generatedTypeParser(parser, &mnemonic, genType);
                     ^~~~~~~~~~~~~~~~~~~
/Users/unicorn/MyCodes/torch-mlir/build/tools/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchTypes.cpp.inc:38:36: note: candidate function not viable: no known conversion from 'llvm::StringRef *' to '::llvm::StringRef' for 2nd argument; remove &
static ::mlir::OptionalParseResult generatedTypeParser(::mlir::AsmParser &parser, ::llvm::StringRef mnemonic, ::mlir::Type &value) {
                                   ^
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by silvasean** [comment]
This looks like one of the things fixed here: https://github.com/llvm/torch-mlir/pull/1059

Does updating to the latest main branch fix the issue?

**Comment by wm901115nwpu** [comment]
ok, it works.
