### ISSUE TITLE
mlir_tblgen is broken for cross compile

### ISSUE THREAD

**Issue by powderluv** [llvm/torch-mlir#1094]
Upstream MLIR has some quirks exporting MLIR_TBLGEN into the CMake `PARENT_SCOPE`  https://github.com/llvm/llvm-project/blob/07b749800c5cd4105d49ab46be5f0a2079dd709a/mlir/CMakeLists.txt#L151-L156 

Some of the tools like `mlir-linalg-ods-yaml-gen`  do the right thing for cross compile with https://github.com/llvm/llvm-project/blob/27945f9282030136cb8b043b91b229ea2758c9ed/mlir/tools/mlir-linalg-ods-gen/CMakeLists.txt#L23-L35

We have some hacks on top of the "directly include tools/<tool> in the top level mlir/CMakeLists.txt" hack here: https://github.com/llvm/torch-mlir/blob/72dd04cdb36e2cabbc0e0d2b0f247aaf1b1076c1/CMakeLists.txt#L92-L98

This causes ARM64 cross compile for Apple M1 to fail on the MacOS Github Actions Runner like https://github.com/llvm/torch-mlir/runs/7441128393?check_suite_focus=true 

```
cd /Users/runner/work/torch-mlir/torch-mlir/build && /Users/runner/work/torch-mlir/torch-mlir/build/bin/mlir-tblgen -gen-pass-decls -DTORCH_MLIR_ENABLE_MHLO -I /Users/runner/work/torch-mlir/torch-mlir/include/torch-mlir/Conversion -I/Users/runner/work/torch-mlir/torch-mlir/build/include -I/Users/runner/work/torch-mlir/torch-mlir/externals/llvm-project/llvm/include -I/Users/runner/work/torch-mlir/torch-mlir/externals/mlir-hlo/include -I/Users/runner/work/torch-mlir/torch-mlir/build/tools/torch-mlir/mlir-hlo/include -I/Users/runner/work/torch-mlir/torch-mlir/externals/llvm-project/llvm/../mlir/include -I/Users/runner/work/torch-mlir/torch-mlir/build/tools/mlir/include -I/Users/runner/work/torch-mlir/torch-mlir/include -I/Users/runner/work/torch-mlir/torch-mlir/build/tools/torch-mlir/include /Users/runner/work/torch-mlir/torch-mlir/include/torch-mlir/Conversion/Passes.td --write-if-changed -o tools/torch-mlir/include/torch-mlir/Conversion/Passes.h.inc -d tools/torch-mlir/include/torch-mlir/Conversion/Passes.h.inc.d
/bin/sh: /Users/runner/work/torch-mlir/torch-mlir/build/bin/mlir-tblgen: Bad CPU type in executable 
```

**Comment by jpienaar** [comment]
And locally on an M1 this should repro with

```
mkdir build
  cd build
  cmake $GITHUB_WORKSPACE/externals/llvm-project/llvm -GNinja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_LINKER=lld \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
    -DPython3_EXECUTABLE=$(which python) \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DLLVM_ENABLE_PROJECTS=mlir \
    -DLLVM_EXTERNAL_PROJECTS="torch-mlir;torch-mlir-dialects" \
    -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR="$GITHUB_WORKSPACE" \
    -DLLVM_EXTERNAL_TORCH_MLIR_DIALECTS_SOURCE_DIR="${GITHUB_WORKSPACE}/external/llvm-external-projects/torch-mlir-dialects" \
    -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
    -DTORCH_MLIR_USE_INSTALLED_PYTORCH=OFF \
    -DCMAKE_OSX_ARCHITECTURES=arm6[4](https://github.com/llvm/torch-mlir/runs/7441128393?check_suite_focus=true#step:4:4) \
    -DMACOSX_DEPLOYMENT_TARGET=12.0 \
    -DLLVM_TARGETS_TO_BUILD=AArch[6](https://github.com/llvm/torch-mlir/runs/7441128393?check_suite_focus=true#step:4:6)4 \
    -DLLVM_USE_HOST_TOOLS=ON \
    -DLLVM_TARGETS_TO_BUILD=host
  ninja
```
?

**Comment by powderluv** [comment]
on an M1 you want to build x86_64 then :D  let me try on my m1 and post a command

**Comment by jpienaar** [comment]
Thanks!

**Comment by powderluv** [comment]
if you don't have Rosetta you can do: 
```
(mlir_venv) anush@MacBook-Pro build % cmake externals/llvm-project/llvm -B build -GNinja \                                                
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_LINKER=lld \
    -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
    -DPython3_EXECUTABLE=$(which python) \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DLLVM_ENABLE_PROJECTS=mlir \
    -DLLVM_EXTERNAL_PROJECTS="torch-mlir;torch-mlir-dialects" \
    -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR=`pwd` \
    -DLLVM_EXTERNAL_TORCH_MLIR_DIALECTS_SOURCE_DIR=`pwd`/external/llvm-external-projects/torch-mlir-dialects \
    -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
    -DTORCH_MLIR_USE_INSTALLED_PYTORCH=OFF \
    -DCMAKE_OSX_ARCHITECTURES=x86_64 \
    -DMACOSX_DEPLOYMENT_TARGET=12.0 \
    -DLLVM_TARGETS_TO_BUILD=X86 \
    -DLLVM_USE_HOST_TOOLS=ON
```
Disabling Rosetta 2 can be complicated I think. (from https://developer.apple.com/forums/thread/669486) 

```
Obtain a list of files/directories and LaunchAgents with: pkgutil --files com.apple.pkg.RosettaUpdateAuto
Save them in a way that you can access them in the recovery
Boot into recovery
Open terminal in recovery (btw to load recovery on M1 macs you long press the power button instead of holding CMD+R)
Run csrutil disable and confirm (temporary disable SIP)
Reboot
Delete the files listed at step 1 (in my case it was enough to delete/Library/Apple/usr/share/rosetta and /Library/Apple/usr/libexec with all their contents)
Reboot back to recovery terminal
Run csrutil enable and confirm
```

**Comment by powderluv** [comment]
Looks like the native tools are being built: 
```
(mlir_venv) anush@MacBook-Pro build % file NATIVE/bin/mlir-tblgen 
NATIVE/bin/mlir-tblgen: Mach-O 64-bit executable arm64
(mlir_venv) anush@MacBook-Pro build % file bin/mlir-tblgen 
bin/mlir-tblgen: Mach-O 64-bit executable x86_64

```

so may just need to set the right version when ` -DLLVM_USE_HOST_TOOLS=ON`

**Comment by jpienaar** [comment]
Great, I'm in a PC meeting today but will try checking soon. I looked a bit yesterday and did see add_tablegen considered cross compilation, so seems likely it is "nesting" where a different setting is needed.

**Comment by marbre** [comment]
Seems related to what is described in https://llvm.org/docs/HowToCrossCompileLLVM.html:

> The TableGen options are required to compile it with the host compiler, so you’ll need to compile LLVM (or at least llvm-tblgen) to your host platform before you start.

When cross-compiling IREE for bare-metal Arm, we need a two stage approach as well to compile the host tools and to compile for the target platform.

**Comment by powderluv** [comment]
@marbre yeah but it should be automatic for LLVM projects with ` -DLLVM_USE_HOST_TOOLS=ON ` . I think if we fix the "directly include tools/ in the top level mlir/CMakeLists.txt" hack  it should automatically work.

**Comment by marbre** [comment]
> Build torch-mlir with:
> 
> ```
> ubuntu:~/github/torch-mlir$ cmake -GNinja -Bbuild   -DCMAKE_BUILD_TYPE=Release   -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc   -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++   -DPython3_FIND_VIRTUALENV=ONLY   -DLLVM_ENABLE_PROJECTS=mlir   -DLLVM_EXTERNAL_PROJECTS="torch-mlir;torch-mlir-dialects"   -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR=`pwd`   -DLLVM_EXTERNAL_TORCH_MLIR_DIALECTS_SOURCE_DIR=`pwd`/externals/llvm-external-projects/torch-mlir-dialects   -DMLIR_ENABLE_BINDINGS_PYTHON=OFF -DTORCH_MLIR_USE_INSTALLED_PYTORCH=OFF  -DLLVM_TARGETS_TO_BUILD=AArch64 -DLLVM_USE_HOST_TOOLS=ON externals/llvm-project/llvm && cmake --build build --target check-torch-mlir-all
> ```

I am quite certain that this one has to fail, since you're passing `-DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc   -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++`.

> @marbre yeah but it should be automatic for LLVM projects with `-DLLVM_USE_HOST_TOOLS=ON` .

I would need to take a closer look to what is behind. I might have some time this evening.

> I think if we fix the "directly include tools/ in the top level mlir/CMakeLists.txt" hack it should automatically work.

Can you elaborate on this? Do suggest you shuffle https://github.com/llvm/llvm-project/blob/28e665fa054d62d4e2c777774cc83dea533dfe6e/mlir/CMakeLists.txt#L154 around?

**Comment by powderluv** [comment]
Yes the latter.  
```
I think you mean a fix similar to https://github.com/llvm/llvm-project/blob/27945f9282030136cb8b043b91b229ea2758c9ed/mlir/tools/mlir-linalg-ods-gen/CMakeLists.txt#L23-L35 for mlir-tblgen.
```

**Comment by jpienaar** [comment]
https://reviews.llvm.org/D130350 relevant here.

**Comment by powderluv** [comment]
I don't think that fixes the issue. With the ARM recreate above you still get:

```
FAILED: include/llvm/IR/IntrinsicsR600.h /home/anush/github/torch-mlir/build/include/llvm/IR/IntrinsicsR600.h 
cd /home/anush/github/torch-mlir/build && /home/anush/github/torch-mlir/build/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=r600 -I /home/anush/github/torch-mlir/externals/llvm-project/llvm/include/llvm/IR -I/home/anush/github/torch-mlir/build/include -I/home/anush/github/torch-mlir/externals/llvm-project/llvm/include /home/anush/github/torch-mlir/externals/llvm-project/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsR600.h -d include/llvm/IR/IntrinsicsR600.h.d
/bin/sh: 1: /home/anush/github/torch-mlir/build/NATIVE/bin/llvm-tblgen: Exec format error
ninja: build stopped: subcommand failed.
1 anush@nod-shared-a100-ubuntu:~/github/torch-mlir$ file /home/anush/github/torch-mlir/build/NATIVE/bin/llvm-tblgen
/home/anush/github/torch-mlir/build/NATIVE/bin/llvm-tblgen: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=eddee09609986fae38bfca74602ec8def8646241, for GNU/Linux 3.2.0, not stripped

```

**Comment by marbre** [comment]
> I don't think that fixes the issue. With the ARM recreate above you still get:

Do you still pass `-DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++`?

Anyway, I can offer to take over and look into the issue in more detail next week (oof tomorrow). I already digged into the cross-compiling mechanism LLVM relies on and into `add_tablegen()`.

**Comment by powderluv** [comment]
Yes I did pass that and still no luck

**Comment by powderluv** [comment]
Thank you for offering to take over.

**Comment by jpienaar** [comment]
Indeed, thanks!

**Comment by marbre** [comment]
> Yes I did pass that and still no luck

Well, one thing is that `arm-none-linux-gnueabihf-g++` won't be able to produce the native binaries for x86. It only supports Arm targets. So you will need to use a compiler that has target support for Arm + x86 (e.g. a Clang build with multiple targets enabled) or you'll need a multi-stage compilation.

Looking into solving this issue next week :)

**Comment by powderluv** [comment]
With the host tools flag set LLVM builds native tools (the mlir_linalg_ods_gen_yaml) handles this well.

**Comment by powderluv** [comment]
@marbre any luck with this issue ?

**Comment by u99127** [comment]
arm-linux-gnueabihf-gcc  produces AArch32 code from a cross compiler suitable for executing in AArch32 ISA state under a Linux environment with glibc. Is that what you are looking for here ? 

Ramana

**Comment by powderluv** [comment]
I think the arm-linux was just an easy repro case for folks to try out without requiring a macOS install. In all cases MLIR_TABLEGEN doesn't seem to respect `-DLLVM_USE_HOST_TOOLS=ON` like `mlir-linalg-ods-yaml-gen` does. That requires us to build host tools once (~3500+ files) and then use the host tools to cross compile (another ~3500 files).  

A fix was attempted with https://reviews.llvm.org/D130350 but that doesn't fix it.

**Comment by u99127** [comment]
Ah I see - sorry about the noise. 



Ramana

**Comment by marbre** [comment]
> @marbre any luck with this issue ?

I am still on it.

> In all cases MLIR_TABLEGEN doesn't seem to respect -DLLVM_USE_HOST_TOOLS=ON like mlir-linalg-ods-yaml-gen does.

What behavior exactly do you expect when setting `LLVM_USE_HOST_TOOLS` to `ON`? Even `mlir-linalg-ods-yaml-gen` calls `build_native_tool` and therefore should build the native tool.

**Comment by powderluv** [comment]
When `-DLLVM_USE_HOST_TOOLS=ON` any required host tools should be built with build_native_tool() and the cross-compile here: https://github.com/llvm/torch-mlir/issues/1094#issuecomment-1192347739 should just work and not fail.  The `mlir-linalg-ods-yaml-gen` tool is built correctly and works as expected using host tool and cross-compile. However `mlir_tblgen` sets up the NATIVE tools correctly but somehow it is not built correctly. 

So expected output of ```
ubuntu:~/github/torch-mlir$ cmake -GNinja -Bbuild   -DCMAKE_BUILD_TYPE=Release   -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc   -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++   -DPython3_FIND_VIRTUALENV=ONLY   -DLLVM_ENABLE_PROJECTS=mlir   -DLLVM_EXTERNAL_PROJECTS="torch-mlir;torch-mlir-dialects"   -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR=`pwd`   -DLLVM_EXTERNAL_TORCH_MLIR_DIALECTS_SOURCE_DIR=`pwd`/externals/llvm-external-projects/torch-mlir-dialects   -DMLIR_ENABLE_BINDINGS_PYTHON=OFF -DTORCH_MLIR_USE_INSTALLED_PYTORCH=OFF  -DLLVM_TARGETS_TO_BUILD=AArch64 -DLLVM_USE_HOST_TOOLS=ON externals/llvm-project/llvm && cmake --build build --target check-torch-mlir-all

```
Should pass and build for ARM but it will fail trying to run arm `mlir_tblgen` on x86_64.

**Comment by powderluv** [comment]
Ok I did some digging into it:

`-DLLVM_USE_HOST_TOOLS=ON` does the right thing for OSX and builds the NATIVE tools. It doesn't do the right thing on the linux recreate I posted above. I think that is because it expects a toolchain cmake file like: https://github.com/llvm/llvm-project/blob/main/llvm/cmake/platforms/Android.cmake. We can revisit the linux_x86_64 --> linux_arm64 later and test it with the correct toolchain.cmake. 

On OSX (the original issue reported here): I think it just comes down to `MLIR_TABLEGEN` being exposed to downstream projects. Setting the CACHE will help if we set it for all tools (like PDLL etc). I will give it a try and if it is easy will post a PR.

**Comment by jpienaar** [comment]
There is also patch under review that sets the install directories of these more correctly, could be unrelated, but seems many folks hitting related pains here. Setting pdll in cache SGTM.

**Comment by powderluv** [comment]
ok more debug info:

When we run cmake we set the correct values
```
...
-- Setting MLIR_TABLEGEN_EXE to /Users/anush/github/torch-mlir/build/NATIVE/bin/mlir-tblgen                                  
-- Setting MLIR_TABLEGEN_TARGET to MLIR-tablegen-host                                                                        
-- Setting MLIR_PDLL_TABLEGEN_EXE to /Users/anush/github/torch-mlir/build/NATIVE/bin/mlir-pdll   
```

and then when we are building the NATIVE tools it gets set again to 
```
-- Setting MLIR_TABLEGEN_EXE to mlir-tblgen                                                                                                                                                                                                               
-- Setting MLIR_TABLEGEN_TARGET to mlir-tblgen                                                                                                                                                                                                            
-- Setting MLIR_PDLL_TABLEGEN_EXE to mlir-pdll          
```

**Comment by stephenneuendorffer** [comment]
I've seen things happen like this with toolchain files, where information discovered from the outer build doesn't get passed to the inner build, including the toolchain file.  As a result, the inner build can discover a different set of information from the outer build.  This is an area where I think cmake recursion is very subtle and it's easy to shoot yerself in the foot.  I've tended to lean on the side of making all information used by a sub-build explicit, but this can be challenging when there is alot of information to be passed.

**Comment by marbre** [comment]
> So expected output of
> 
> ```
> ubuntu:~/github/torch-mlir$ cmake -GNinja -Bbuild   -DCMAKE_BUILD_TYPE=Release   -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc   -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++   -DPython3_FIND_VIRTUALENV=ONLY   -DLLVM_ENABLE_PROJECTS=mlir   -DLLVM_EXTERNAL_PROJECTS="torch-mlir;torch-mlir-dialects"   -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR=`pwd`   -DLLVM_EXTERNAL_TORCH_MLIR_DIALECTS_SOURCE_DIR=`pwd`/externals/llvm-external-projects/torch-mlir-dialects   -DMLIR_ENABLE_BINDINGS_PYTHON=OFF -DTORCH_MLIR_USE_INSTALLED_PYTORCH=OFF  -DLLVM_TARGETS_TO_BUILD=AArch64 -DLLVM_USE_HOST_TOOLS=ON externals/llvm-project/llvm && cmake --build build --target check-torch-mlir-all
> ```
> 
> Should pass and build for ARM but it will fail trying to run arm `mlir_tblgen` on x86_64.

* Thanks for clarifying. First of all, I don't know if the target `check-torch-mlir-all` can ever pass when cross-compiling (at least not the way it is right now). The necessary `torch-mlir-opt` is cross-compiled for the target (from a quick look a native versions won't be built) and thus the test cannot be executed. Anyway, we should be able to cross-compile those tools for the target :)

> `-DLLVM_USE_HOST_TOOLS=ON` does the right thing for OSX and builds the NATIVE tools. It doesn't do the right thing on the linux recreate I posted above.

* It shouldn't be necessary to set `LLVM_USE_HOST_TOOLS`. It is already set if an LLVM project is cross-compiled:
https://github.com/llvm/llvm-project/blob/0f5385b70eddfbcb26fed973a4d6e4cc01260930/llvm/CMakeLists.txt#L716-L718

* Further, I think it does the correct thing with [D130350](https://reviews.llvm.org/D130350) applied. I played around with [mlir-emitc](https://github.com/iml130/mlir-emitc) and had success with getting a native `mlir-tblgen` for an x86_64 Linux and a cross compiled on for an Arm Linux.
Unfortunately, I messed up my build-script and cannot share exactly what I did last Friday. Trying to reproduce and will afterwards test with torch-mlir.

> I think that is because it expects a toolchain cmake file like: https://github.com/llvm/llvm-project/blob/main/llvm/cmake/platforms/Android.cmake. We can revisit the linux_x86_64 --> linux_arm64 later and test it with the correct toolchain.cmake.

* You don't need a toolchain file to cross-compile. You can pass all the necessary flags via the command line or pass them via a script. I think the failure is rather related to wrong build args passed via CMake, especially for Linux to Linux cross-compiling (with Apple clang this might be different due to flags like `MACOSX_DEPLOYMENT_TARGET`). It is really tricky to get this done right and the Linux reproducer definitely misses `CMAKE_SYSTEM_NAME` to do a correct cross-compile. As promised, I am looking further into this.

> and then when we are building the NATIVE tools it gets set again to
> 
> ```
> -- Setting MLIR_TABLEGEN_EXE to mlir-tblgen                                                                                                                                                                                                               
> -- Setting MLIR_TABLEGEN_TARGET to mlir-tblgen                                                                                                                                                                                                            
> -- Setting MLIR_PDLL_TABLEGEN_EXE to mlir-pdll          
> ```

* Do you still set https://github.com/llvm/torch-mlir/blob/290d7755fb27396ea22d5ab489f20a889f048c2e/CMakeLists.txt#L105 ?

**Comment by powderluv** [comment]
> > `-DLLVM_USE_HOST_TOOLS=ON` does the right thing for OSX and builds the NATIVE tools. It doesn't do the right thing on the linux recreate I posted above.
> 
> * It shouldn't be necessary to set `LLVM_USE_HOST_TOOLS`. It is already set if an LLVM project is cross-compiled:
>   https://github.com/llvm/llvm-project/blob/0f5385b70eddfbcb26fed973a4d6e4cc01260930/llvm/CMakeLists.txt#L716-L718


So on my x86_64 macOS building with `-DCMAKE_OSX_ARCHITECTURES=arm64`  if `-DLLVM_USE_HOST_TOOLS=ON` is not set it doesn't attempt to build_native_tool() so I have to explicitly set it.  Maybe that is the root cause ? 


> * Further, I think it does the correct thing with [D130350](https://reviews.llvm.org/D130350) applied. I played around with [mlir-emitc](https://github.com/iml130/mlir-emitc) and had success with getting a native `mlir-tblgen` for an x86_64 Linux and a cross compiled on for an Arm Linux.
>   Unfortunately, I messed up my build-script and cannot share exactly what I did last Friday. Trying to reproduce and will afterwards test with torch-mlir.

[D130350](https://reviews.llvm.org/D130350)  is a good start but ideally we want to avoid pushing these into the cache which has unintended consequences if we recompile / change flags etc. Ideally we keep exporting out into PARENT_SCOPE until the top level has the variables we are about. That said add_tblgen() itself is pushing stuff into CACHE. 


> 
> > I think that is because it expects a toolchain cmake file like: https://github.com/llvm/llvm-project/blob/main/llvm/cmake/platforms/Android.cmake. We can revisit the linux_x86_64 --> linux_arm64 later and test it with the correct toolchain.cmake.
> 
> * You don't need a toolchain file to cross-compile. You can pass all the necessary flags via the command line or pass them via a script. I think the failure is rather related to wrong build args passed via CMake, especially for Linux to Linux cross-compiling (with Apple clang this might be different due to flags like `MACOSX_DEPLOYMENT_TARGET`). It is really tricky to get this done right and the Linux reproducer definitely misses `CMAKE_SYSTEM_NAME` to do a correct cross-compile. As promised, I am looking further into this.

Ok Thank you. 

> 
> > and then when we are building the NATIVE tools it gets set again to
> > ```
> > -- Setting MLIR_TABLEGEN_EXE to mlir-tblgen                                                                                                                                                                                                               
> > -- Setting MLIR_TABLEGEN_TARGET to mlir-tblgen                                                                                                                                                                                                            
> > -- Setting MLIR_PDLL_TABLEGEN_EXE to mlir-pdll          
> > ```
> 
> * Do you still set https://github.com/llvm/torch-mlir/blob/290d7755fb27396ea22d5ab489f20a889f048c2e/CMakeLists.txt#L105
>    ?

Yes I remove it locally. I will send a PR for this now that [D130350](https://reviews.llvm.org/D130350) has landed. 

@ashay  fyi since you updated the add_tblgen() recently.

**Comment by marbre** [comment]
> So on my x86_64 macOS building with `-DCMAKE_OSX_ARCHITECTURES=arm64` if `-DLLVM_USE_HOST_TOOLS=ON` is not set it doesn't attempt to build_native_tool() so I have to explicitly set it. Maybe that is the root cause ?

Honestly, IDK and I currently don't have a Mac available to test :/

> [D130350](https://reviews.llvm.org/D130350) is a good start but ideally we want to avoid pushing these into the cache which has unintended consequences if we recompile / change flags etc. Ideally we keep exporting out into PARENT_SCOPE until the top level has the variables we are about. That said add_tblgen() itself is pushing stuff into CACHE.

Yeah, I am not really sure if we should go with a cache variable or with explicitly exporting to parent scopes. And yes, you're right, `add_tablegen` sets a cache variable for `${project}_TABLEGEN` ([here](https://github.com/llvm/llvm-project/blob/1d1a56929b725f9a79d98877f12d0a14f8418b38/llvm/cmake/modules/TableGen.cmake#L158-L159)). However, it also pushes to the parent scope...

Anyway, I was able to cross-compile `torch-mlir-opt` for Arm. This requires the patches #1196, #1197 and https://github.com/tensorflow/tensorflow/pull/57054 (I locally modified the mlir-hlo submodule to make the build pass).

**Comment by powderluv** [comment]
What is your local command to cross-compile ?

**Comment by powderluv** [comment]
magically I am able to cross-compile on the GHA macos-12 runner https://github.com/llvm/torch-mlir/pull/1204  but not on my iMacPro.  If this works on GHA we can close this issue or make it low priority.

**Comment by marbre** [comment]
Let me try to get a running cross-compile from x86_64 Linux to Arm Linux with Clang (I used GCC so far). But I agree, we can than deprioritize.

**Comment by powderluv** [comment]
This is now fixed.
