### ISSUE TITLE
Can `torch-mlir` use NV GPU or AMD GPU device to execute the module?

### ISSUE THREAD

**Issue by wzzju** [llvm/torch-mlir#1143]
Can `torch-mlir` use NV GPU or AMD GPU device to execute the module?

**Comment by powderluv** [comment]
Torch-mlir only aims to provide a reference backend. For a real backend using torch-mlir please take a look at iree-torch (https://github.com/iree-org/iree-torch) or SHARK (https://github.com/nod-ai/SHARK) which supports hundreds of models across AMD, Nvidia and Apple GPUs

**Comment by silvasean** [comment]
+1 to what @powderluv said. You will need to find a backend that can target those devices, and then use Torch-MLIR to provide it input (Torch-MLIR can provide it in the form of Linalg, TOSA, or MHLO).

**Comment by powderluv** [comment]
Please create a new issue if you have any further issues / comments.
