### ISSUE TITLE
Document CMake hack better

### ISSUE THREAD

**Issue by silvasean** [llvm/torch-mlir#1149]
https://github.com/llvm/torch-mlir/blob/48ec3005865cb55b6e70a85ccf67f5e63d3c5b83/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/CMakeLists.txt#L13

Can we get an expanded explanation and use our common "TODO" tag here to track the remaining work. Also, it would be nice if we filed a new issue to track follow-on work post-LTC-landing.

**Comment by henrytwo** [comment]
I'll update the comment to link to the new issue I made, but here's a direct link: https://github.com/llvm/torch-mlir/issues/1154
