### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by rengolin** [llvm/torch-mlir#1173]
Just tried to build torch-mlir from [these instructions](https://github.com/llvm/torch-mlir/blob/main/development.md) (following the in-tree build) and got this error:

```
Traceback (most recent call last):
  File "/home/rengolin/devel/mlir/torch-mlir/mlir_venv/lib/python3.10/site-packages/torchgen/utils.py", line 34, in <module>
    from yaml import CSafeLoader as Loader
ModuleNotFoundError: No module named 'yaml'
```

Installed PyYaml and the build continues.

Shouldn't PyYaml be in `requirements.txt`?

**Comment by rengolin** [comment]
Not sure what happened, but PyYaml was installed on a new venv I created after this. I'll ignore this for now and can reopen if I find what I've done before and still have a problem.

**Comment by silvasean** [comment]
`torchgen` is the module which PyTorch uses for autogenerating various codes, which we use for LTC.

I believe that yaml is a transitive dependency of PyTorch. Let us know if you see this again.

**Comment by rengolin** [comment]
I have seen this again on a fresh container and fresh repo on my box with a fresh venv. Other developers are seeing that, too. I guess it doesn't hurt to add the req in the files anyway, I'll reopen the PR.
