### ISSUE TITLE
Constant folding on Torch Dialect

### ISSUE THREAD

**Issue by ZihengJiang** [llvm/torch-mlir#1182]
After converting a PyTorch model to Torch dialect, some parts are converted to this:

```
    %6 = torch.vtensor.literal(dense<5> : tensor<si64>) : !torch.vtensor<[],si64>
    ...
    %451 = torch.prim.NumToTensor.Scalar %int5 : !torch.int -> !torch.vtensor<[],si64>
    %452 = torch.aten.div.Tensor_mode %451, %6, %str : !torch.vtensor<[],si64>, !torch.vtensor<[],si64>, !torch.str -> !torch.vtensor<[],si64>
    %453 = torch.aten.Int.Tensor %452 : !torch.vtensor<[],si64> -> !torch.int
    %454 = torch.prim.ListConstruct %453, %int5, %int-1 : (!torch.int, !torch.int, !torch.int) -> !torch.list<int>
    %455 = torch.aten.view %450, %454 : !torch.vtensor<[5,2048],f32>, !torch.list<int> -> !torch.vtensor<[?,5,?],f32>
```

As you can see, most of them can be pre-computed since the inputs are all constant integers, then we can get a static shaped %455. 

Any idea for this?

**Comment by silvasean** [comment]
We already partially support this. It requires an extension for "div". We can generalize the logic here: https://github.com/llvm/torch-mlir/pull/935

**Comment by ZihengJiang** [comment]
This issue is solved by https://github.com/llvm/torch-mlir/pull/1209 . Thanks @Vremold .
