### ISSUE TITLE
clean up llvmtype / buildtype in Github workflows

### ISSUE THREAD

**Issue by powderluv** [llvm/torch-mlir#1207]
Tracking work items from the suggestion by @sjain-stanford https://github.com/llvm/torch-mlir/pull/1206#pullrequestreview-1067537720

**Comment by powderluv** [comment]
The hopefully final missing piece of the CI (macOS m1 cross compile) is now up https://github.com/llvm/torch-mlir/issues/1207.  It builds arm64 and x86 separately and tests on x86.  Once that is in we can re-org the matrix types and clean up / reduce superfluous ones

**Comment by sjain-stanford** [comment]
Perfect. I can work on this today. Did you also want me to include the last change we discussed [here](https://github.com/llvm/torch-mlir/pull/1204#issuecomment-1210900565)? 
> remove x86 build + tests for macos and only use arm64 build + tests

**Comment by powderluv** [comment]
yes please. btw just mentioned it on discord -- maybe we can kill one of the Ubuntu builds and leave the macos x86/arm64 since it is redundant. It will probably be longer but worth checking what the runtime it when fully cached.

**Comment by powderluv** [comment]
so if you address those comments I have no more changes in the pipeline. So we end up with three builds

1. macos x86 + arm64 builds and x86 tests (in-tree+pytorch src on macOS  x86 with tests and arm64 builds)
2. ubuntu in tree src build with pytorch binary (most used developer setup)
3. ubuntu out of tree src build with pytorch source (OOT is vendor used + pytorch source tests on Ubuntu)

What do you think ? This should help up us trim all the matrix combinations. Maybe even kill `targetarch` ?

**Comment by sjain-stanford** [comment]
Sounds good except it'd be nice to decouple the mac builds because combining them into one workflow doesn't give us any benefit. The tests are pretty fast so we can run them for both mac builds, it's the build which [hurts us](https://github.com/llvm/torch-mlir/pull/1204#pullrequestreview-1068527446) and combining means we'll require increasing ccache limit to beyond 2G which will hurt overall (given 10G restrictions). 

How about this? IMO this offers reasonable coverage by testing pytorch source with both in-tree and out-of-tree, and also tests macos for both x86 and arm64. WDYT?
```
Current: 
ubuntu - x86_64 - pytorch binary - in-tree - build+test
ubuntu - x86_64 - pytorch source - in-tree - build+test
ubuntu - x86_64 - pytorch binary - out-of-tree - build+test
macos - x86_64 - pytorch binary - in-tree - build + test
macos - arm64 - pytorch binary - in-tree - build only

Proposed:
ubuntu - x86_64 - pytorch binary - in-tree - build+test
ubuntu - x86_64 - pytorch source - out-of-tree - build+test
macos - x86_64 - pytorch source - in-tree - build+test
macos - arm64 - pytorch binary - in-tree - build+test
```

**Comment by powderluv** [comment]
I think we can trim further to just:

```
ubuntu - x86_64 - pytorch binary - in-tree - build+test    # most used dev flow and fastest signal 
ubuntu - x86_64 - pytorch source - out-of-tree - build+test  # most elaborate test
macos - arm64 - pytorch binary - in-tree - build only   # cant test arm64
```

**Comment by sjain-stanford** [comment]
> I think we can trim further to just:

This doesn't test pytorch source + in-tree. Is that OK?

**Comment by sjain-stanford** [comment]
.. and good point about not running arm64 tests!

**Comment by powderluv** [comment]
we could flip arm64 to `macos - arm64 - pytorch source - in-tree - build only   # cant test arm64`

**Comment by sjain-stanford** [comment]
Sounds good. 

```
ubuntu - x86_64 - pytorch binary - in-tree - build+test
ubuntu - x86_64 - pytorch source - out-of-tree - build+test
macos - arm64 - pytorch source - in-tree - build+test
```
Going 1... 2... 3... :D

**Comment by powderluv** [comment]
we could reduce the matrix like 
```
os: [ubuntu-x86_64, macOS-arm64]
pytorch_source: [ ON, OFF ]
clang_source: [ON, OFF]
suite: [build, test]
```

**Comment by powderluv** [comment]
with only three builds you can make the ccache larger too.

**Comment by sjain-stanford** [comment]
Thanks for the feedback @powderluv. Yes, I can streamline the matrix options now that we have aligned on the 3 workflows it should create:
```
ubuntu - x86_64 - pytorch binary - llvm in-tree - build+test     # most used dev flow and fastest signal 
ubuntu - x86_64 - pytorch source - llvm out-of-tree - build+test   # most elaborate test
macos - arm64 - pytorch source - llvm in-tree - build only     # cant test arm64
```

**Comment by powderluv** [comment]
with these changes you become the official maintainer of the CI :D

**Comment by sjain-stanford** [comment]
> with these changes you become the official maintainer of the CI :D

Not sure if I should be happy or sad, but in any case I'm glad to help with this :) 
(it does not mean you're off the hook though)
