### ISSUE TITLE
Reduce MHLO #ifdefs

### ISSUE THREAD

**Issue by silvasean** [llvm/torch-mlir#1227]
We try to avoid using #ifdefs because they make it impossible to test all the configurations easily.

I noticed two in TorchToMhlo that can be removed.

TORCH_MLIR_ENABLE_MHLO_STATIC_SHAPE
TORCH_MLIR_ENABLE_MHLO_TRUNC_DIMSIZE_TO_I32

https://github.com/llvm/torch-mlir/blob/9d6ee48661cefa677950bcd262fe2824a4fa9d17/lib/Conversion/TorchToMhlo/Basic.cpp#L412

We should add those as pass options to the convert-torch-to-mhlo pass, and pass them down to the patterns that need them.
(see here for how to add pass options: https://mlir.llvm.org/docs/PassManagement/#declarative-pass-specification)

cc @ZihengJiang @fortianyou

**Comment by fortianyou** [comment]
Sure! This is a good suggestion. I will try it out recently.

**Comment by silvasean** [comment]
Fixed in https://github.com/llvm/torch-mlir/pull/1315
