### ISSUE TITLE
About TensorRT Dialect

### ISSUE THREAD

**Issue by KangHe000** [llvm/torch-mlir#1239]
Hi, recently, my colleagues and I used torch-mlir as front-end tool to convert Huggingface's Bert model into TensorRT model. 
We  added some graph-opt passes(base on Torch Dialect) by using graph optimization tool of MLIR, and then used them together with TensorRT api and some customized TensorRT plugins, which achieved better performance than "torch-mlir + iree" and ONNX-TensorRT.
Here, I have two questions:
1. Will the Mlir community have any plans to support TensorRT Dialect in the future?
2. If we design a TensorRT Dialect, Is it necessary? Or will it be valuable? Are there any requirement if we want to contribute it to torch-mlir in the future?

**Comment by silvasean** [comment]
I'm glad you were able to make good use of Torch-MLIR! I think lots of people in the MLIR community would be interested in this, so I think it would be better if you post it in the MLIR discussion forums! https://discourse.llvm.org/c/mlir/31

**Comment by KangHe000** [comment]
OK.Torch-MLIR provide one more option for converting PyTorch model to TensorRT model, We learn a lot from Torch-MLIR Project! 
If there was a TensorRT Dialect, We can connect MLIR and TensorRT smoothly and may find more optimization opportunities.
We will post our question in the MLIR discussion forums. Thanks!

**Comment by silvasean** [comment]
Closing this issue as it has been moved to the forum.
