### ISSUE TITLE
Fix warnings in LTC code

### ISSUE THREAD

**Issue by ashay** [llvm/torch-mlir#1264]
In the clean build, clang (v11) produces about 150+ warnings when compiling the LTC code, with the following approximate distribution:

1 x `Wunneeded-internal-declaration`
2 x `Wunused-function`
2 x `Wunused-variable`
~150 x `Wc++98-compat-extra-semi`

These warnings make it difficult to get to, and resolve, warnings and errors in non-LTC code.  Please fix the code so that the compiler does not produce these warnings.

**Comment by henrytwo** [comment]
- `Wunneeded-internal-declaration` (https://github.com/llvm/torch-mlir/pull/1272)
- `Wunused-variable` (https://github.com/llvm/torch-mlir/pull/1272)
- `Wc++98-compat-extra-semi` (https://github.com/pytorch/pytorch/pull/83955)
- `Wunused-function` is still being investigated, but it is from upstream PyTorch

**Comment by henrytwo** [comment]
This issue has been resolved, with the exception of `Wunused-function`, for reasons explained in https://github.com/pytorch/pytorch/pull/83955
