### ISSUE TITLE
Unnecessary `tensor_static_info_cast` operators are inserted

### ISSUE THREAD

**Issue by ZihengJiang** [llvm/torch-mlir#1270]
I tried to lower a pytorch model into torch dialect but I found that unnecessary `tensor_static_info_cast` operators are inserted. For example, there is a code snippet like this:

```
  ...
  _17 = [torch.div(sum_embeddings, sum_mask0)]
  embedding_a = torch.cat(_17, 1)
  ...
  _25 = [torch.div(sum_embeddings0, sum_mask2)]
  embedding_b = torch.cat(_25, 1)
  d = torch.mul(embedding_a, embedding_b)
```

which is lowered to

```
    %910 = torch.prim.ListConstruct %909 : (!torch.vtensor<[1,768],f32>) -> !torch.list<vtensor>
    %911 = torch.aten.cat %910, %int1 : !torch.list<vtensor>, !torch.int -> !torch.vtensor<[1,768],f32>
    %912 = torch.tensor_static_info_cast %911 : !torch.vtensor<[1,768],f32> to !torch.vtensor<*,f32>
    %913 = torch.copy.to_tensor %912 : !torch.tensor<*,f32>
    ...
    %924 = torch.prim.ListConstruct %923 : (!torch.vtensor<[1,768],f32>) -> !torch.list<vtensor>
    %925 = torch.aten.cat %924, %int1 : !torch.list<vtensor>, !torch.int -> !torch.vtensor<[1,768],f32>
    %926 = torch.tensor_static_info_cast %925 : !torch.vtensor<[1,768],f32> to !torch.vtensor<*,f32>
    %927 = torch.copy.to_tensor %926 : !torch.tensor<*,f32>
    %928 = torch.copy.to_vtensor %913 : !torch.vtensor<*,f32>
    %929 = torch.copy.to_vtensor %927 : !torch.vtensor<*,f32>
    %930 = torch.aten.mul.Tensor %928, %929 : !torch.vtensor<*,f32>, !torch.vtensor<*,f32> -> !torch.vtensor<[1,768],unk>
```

Why does it convert `embedding_a` and `embedding_b` from static shape `[1, 768]` to the unknown shape `<*,f32>` before the `aten.mul.Tensor` operation? This looks pretty strange.

This also lead error like:
```
error: unsupported by backend contract: tensor with unknown rank
note: see current operation: %1200 = "torch.tensor_static_info_cast"(%1199) : (!torch.vtensor<[1,768],f32>) -> !torch.vtensor<*,f32>
note: this is likely due to a missing shape transfer function in shape_lib_gen.py
```

**Comment by silvasean** [comment]
In this case we need to somehow remove the non-value semantic tensors (`!torch.tensor` -- no "v"). It should all just work after that. Can you dig into why we do not convert the whole program to value semantics?

**Comment by ZihengJiang** [comment]
> In this case we need to somehow remove the non-value semantic tensors (`!torch.tensor` -- no "v"). It should all just work after that. Can you dig into why we do not convert the whole program to value semantics?

Do you have idea for which pass I should look into?

**Comment by silvasean** [comment]
MaximizeValueSemantics (or less likely, ReduceOpVariants)

**Comment by ZihengJiang** [comment]
Solved after add some new ops into the torch dialect
