### ISSUE TITLE
ImportError: lib_torch_mlir_ltc.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by silvasean** [llvm/torch-mlir#1271]
Installing from the nightly packages, I see a missing lib_torch_mlir_ltc.so

Is this intended to work? If not, is there some way to detect that it won't work so that we can avoid this kind of error

```
File "/opt/hostedtoolcache/Python/3.9.[13](https://github.com/iree-org/iree-torch/runs/7970725558?check_suite_focus=true#step:5:14)/x64/lib/python3.9/site-packages/torch_mlir_e2e_test/torchscript/configs/lazy_tensor_core.py", line 6, in <module>
    import torch_mlir.reference_lazy_backend._REFERENCE_LAZY_BACKEND as lazy_backend
ImportError: lib_torch_mlir_ltc.so: cannot open shared object file: No such file or directory
```
https://github.com/iree-org/iree-torch/runs/7970725558?check_suite_focus=true

cc @henrytwo @powderluv

**Comment by henrytwo** [comment]
Hmm, `lib_torch_mlir_ltc.so` should exist under `torch_mlir/base_lazy_backend` in the wheel. Can you confirm that this path is available at runtime + can be used for shared libs?

**Comment by henrytwo** [comment]
I can repro this locally, so I'll investigate further locally

**Comment by henrytwo** [comment]
Hm it looks like setting:
```
export LD_LIBRARY_PATH=venv/lib/python3.8/site-packages/torch_mlir/base_lazy_backend/
```
solves the issue. Is there anyway we can automate this?

**Comment by silvasean** [comment]
We put various shared libraries in `cmake_build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/_mlir_libs` -- I'm not sure how that plays into the bigger picture, but you can probably imitate the incantation we use to import those shared libraries. (libTorchMLIRAggregateCAPI.so in that directory is an example of a non-Python-extension shared library, if that is useful)
