### ISSUE TITLE
[RFC] Implementing (the static case of) cumsum

### ISSUE THREAD

**Issue by gpetters94** [llvm/torch-mlir#1277]
We need cumsum for OPT, but work on the implementation stalled in #478 after it became apparent we couldn't use linalg. If I understand the problem correctly we should be able to decompose it into a number of sum operations if the output and dim are statically known. Is this a special case we would like to handle, or would the resulting IR be too big?

Alternatively, is cumsum something we could implement in TMTensor?

**Comment by silvasean** [comment]
TMTensor_ScanOp is cumsum

**Comment by silvasean** [comment]
Fixed in https://github.com/llvm/torch-mlir/pull/1320
