### ISSUE TITLE
add slack integration with this repo

### ISSUE THREAD

**Issue by gglin001** [llvm/torch-mlir#1279]
hi, when I want to follow repo update in a slack channel, following the steps at

https://slack.github.com/
&
https://github.com/integrations/slack

but got error

<img width="1052" alt="Screen Shot 2022-08-25 at 3 03 44 PM" src="https://user-images.githubusercontent.com/13805221/186597688-cc5378e8-a9d9-41d6-bfb5-2c31c7e900b7.png">

seems needs repo admin connecting slack app with this repo. It would be great to be able to do so.

**Comment by silvasean** [comment]
@asl is it ok for me to install Slack integration on the llvm/torch-mlir github repo?

I see this screen:

![image](https://user-images.githubusercontent.com/24583347/186767569-aeba2c8a-a483-4349-88c9-fd31e3f8a924.png)

**Comment by silvasean** [comment]
@sqlbyme also

**Comment by asl** [comment]
Sure!

**Comment by silvasean** [comment]
@gglin001 -- I just gave access. Can you see if it works for you now?

**Comment by gglin001** [comment]
it works now! 🎉
