### ISSUE TITLE
Shape simplification failed for AtenArangeOp

### ISSUE THREAD

**Issue by Vremold** [llvm/torch-mlir#1305]
I am lowering a TS model to torch dialect. There is a `torch.aten.arange.start` op. And the shape simplification pipeline failed to reason out that its result should have a static shape.
This is the IR before shape simplification pipeline:
``` mlir
%none = torch.constant.none
%int0 = torch.constant.int 0
%int5 = torch.constant.int 5
%0 = torch.aten.arange.start %int0, %int5, %none, %none, %none, %none : !torch.int, !torch.int, !torch.none, !torch.none, !torch.none, !torch.none -> !torch.vtensor
```
And this is the IR after shape simplification pipeline:
```
%none = torch.constant.none
%int0 = torch.constant.int 0
%int5 = torch.constant.int 5
%0 = torch.aten.arange.start %int0, %int5, %none, %none, %none, %none : !torch.int, !torch.int, !torch.none, !torch.none, !torch.none, !torch.none -> !torch.vtensor<[?],unk>
```
The reason seems to be related to the shape-lib for `torch.aten.arange_start` op, which comes from `torch.jit._shape_functions` and accepts `Union[int, float]` as input. The following is the part of IR inserted during the shape calculation:
```
%0 = torch.shape.calculate {
  %2 = torch.aten.arange.start %int0, %int5, %none, %none, %none, %none : !torch.int, !torch.int, !torch.none, !torch.none, !torch.none, !torch.none -> !torch.vtensor<[?],unk>
  torch.shape.calculate.yield %2 : !torch.vtensor<[?],unk>
} shapes {
  %2 = torch.operator "aten.ge"(%float5.000000e00, %int0) : (!torch.float, !torch.int) -> !torch.bool
  torch.prim.If %2 -> () {
    torch.prim.If.yield
  } else {
    torch.prim.RaiseException %str, %none : !torch.str, !torch.none
    torch.prim.If.yield
  }
  %3 = torch.operator "aten.ge"(%float5.000000e00, %float0.000000e00) : (!torch.float, !torch.float) -> !torch.bool
  torch.prim.If %3 -> () {
    torch.prim.If.yield
  } else {
    torch.prim.RaiseException %str, %none : !torch.str, !torch.none
    torch.prim.If.yield
  }
  %4 = torch.operator "aten.sub"(%float5.000000e00, %float0.000000e00) : (!torch.float, !torch.float) -> !torch.number
  %5 = torch.operator "aten.ceil.Scalar"(%4) : (!torch.number) -> !torch.number
  %6 = torch.aten.Int.Scalar %5 : !torch.number -> !torch.int
  %7 = torch.prim.ListConstruct %6 : (!torch.int) -> !torch.list<int>
  torch.shape.calculate.yield.shapes %7 : !torch.list<int>
} : !torch.vtensor<[?],unk>
```
But for now, we do not register `aten.sub` (and other ops similar to it, for example, `aten.ne` in above example) in our ods or design folding strategy for them. This shortage leads to the problem above. The common feature of these ops is that they accept int and float input both. Do I understand it right and is there any plan to support it?

**Comment by ramiro050** [comment]
Hi @Vremold, your understanding sounds right to me. I don't think anyone right now is working on adding support for those ops, but it should be straight forward to add folders for them. In torch-mlir, the `Union[int, float]` type turns into a `!torch.number`, which will often get replaced with `!torch.int` or `!torch.float` (as shown in the last MLIR snippet in your comment), since in most cases we can tell the actual type at compile time. So, you don't need to worry about handling the `Union` type.

In the ODS gen script, the signature for `aten.sub` will be similar to

https://github.com/llvm/torch-mlir/blob/26231853ab6cce4b98949df059850003107e0fc1/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py#L590

Happy to help with any questions

**Comment by silvasean** [comment]
I agree. I think the correct fix here is to add support for aten::sub and all the other `Scalar` ops.

**Comment by Vremold** [comment]
> Hi @Vremold, your understanding sounds right to me. I don't think anyone right now is working on adding support for those ops, but it should be straight forward to add folders for them. In torch-mlir, the `Union[int, float]` type turns into a `!torch.number`, which will often get replaced with `!torch.int` or `!torch.float` (as shown in the last MLIR snippet in your comment), since in most cases we can tell the actual type at compile time. So, you don't need to worry about handling the `Union` type.
> 
> In the ODS gen script, the signature for `aten.sub` will be similar to
> 
> https://github.com/llvm/torch-mlir/blob/26231853ab6cce4b98949df059850003107e0fc1/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py#L590
> 
> Happy to help with any questions

Thanks a lot for the suggestions. But it seems to help little. I registered the `aten.sub` op which accepts `scalar` as inputs. 
```
emit("aten::add : (Scalar, Scalar) -> (Scalar)")
emit("aten::sub : (Scalar, Scalar) -> (Scalar)")
```
But after shape-lib generating, no changes happens in `@__torch__.torch.jit._shape_functions.arange_start`. The capture for `aten.sub` op still fails. And of course, the shape simplification fails, too.
```
func.func @__torch__.torch.jit._shape_functions.arange_start(%arg0: !torch.union<float, int>, %arg1: !torch.union<float, int>, %arg2: !torch.any, %arg3: !torch.any, %arg4: !torch.any, %arg5: !torch.any) -> !torch.list<int> {
  ...
  %2 = torch.operator "aten.sub"(%arg1, %arg0) : (!torch.union<float, int>, !torch.union<float, int>) -> !torch.number
  %3 = torch.operator "aten.ceil.Scalar"(%2) : (!torch.number) -> !torch.number
  %4 = torch.aten.Int.Scalar %3 : !torch.number -> !torch.int
  %5 = torch.prim.ListConstruct %4 : (!torch.int) -> !torch.list<int>
  return %5 : !torch.list<int>
}
```

**Comment by Vremold** [comment]
> Hi @Vremold, your understanding sounds right to me. I don't think anyone right now is working on adding support for those ops, but it should be straight forward to add folders for them. In torch-mlir, the `Union[int, float]` type turns into a `!torch.number`, which will often get replaced with `!torch.int` or `!torch.float` (as shown in the last MLIR snippet in your comment), since in most cases we can tell the actual type at compile time. So, you don't need to worry about handling the `Union` type.
> 
> In the ODS gen script, the signature for `aten.sub` will be similar to
> 
> https://github.com/llvm/torch-mlir/blob/26231853ab6cce4b98949df059850003107e0fc1/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py#L590
> 
> Happy to help with any questions

Thanks a lot for the suggestions.  I registered the `aten.sub` and `aten.ceil.Scalar` op which accepts `scalar` as inputs and design folder for `aten.sub`.
```
emit("aten::add : (Scalar, Scalar) -> (Scalar)") 
emit("aten::sub : (Scalar, Scalar) -> (Scalar)", has_folder=True) 
emit("aten::ceil.Scalar : (Scalar) -> (Scalar)")
```
After shape-lib generating, `@__torch__.torch.jit._shape_functions.arange_start` changes to something like this:
```
func.func @__torch__.torch.jit._shape_functions.arange_start(%arg0: !torch.union<float, int>, %arg1: !torch.union<float, int>, %arg2: !torch.any, %arg3: !torch.any, %arg4: !torch.any, %arg5: !torch.any) -> !torch.list<int> {
  ....
  %2 = torch.aten.sub %arg1, %arg0 : !torch.union<float, int>, !torch.union<float, int> -> !torch.number
  %3 = torch.operator "aten.ceil.Scalar"(%2) : (!torch.number) -> !torch.number
  %4 = torch.aten.Int.Scalar %3 : !torch.number -> !torch.int
  %5 = torch.prim.ListConstruct %4 : (!torch.int) -> !torch.list<int>
  return %5 : !torch.list<int>
```
As you can see, the capture for `aten.ceil.Scalar` op still fails. And the folder for `aten.sub` doesn't execute correctly, either. This may be because our materializeConstant doesn't support torch.number type. Of course, the shape simplification fails, too.
```
// IR inserted during shape calculation
%4 = torch.aten.sub %float5.000000e00, %float0.000000e00 : !torch.float, !torch.float -> !torch.number
%5 = torch.operator "aten.ceil.Scalar"(%4) : (!torch.number) -> !torch.number
%6 = torch.aten.Int.Scalar %5 : !torch.number -> !torch.int
%7 = torch.prim.ListConstruct %6 : (!torch.int) -> !torch.list<int>
torch.shape.calculate.yield.shapes %7 : !torch.list<int>
```

**Comment by silvasean** [comment]
Did you run update_torch_ods.sh and update_shape_lib.sh? There should be no `torch.operator "aten.ceil.Scalar"(%2) : (!torch.number) -> !torch.number` if there is `emit("aten::ceil.Scalar : (Scalar) -> (Scalar)")`.

**Comment by Vremold** [comment]
> Did you run update_torch_ods.sh and update_shape_lib.sh? There should be no `torch.operator "aten.ceil.Scalar"(%2) : (!torch.number) -> !torch.number` if there is `emit("aten::ceil.Scalar : (Scalar) -> (Scalar)")`.

It's my stupid mistake, I forget to run update_shape_lib.sh for aten.ceil.Scalar. Many thanks. But other problem still exists.

**Comment by silvasean** [comment]
I think you might be right about materializeConstant. In this case, the right materialization is to materialize either torch.constant.int or torch.constant.float and then a torch.derefine op to derefine the result to !torch.number

**Comment by Vremold** [comment]
> I think you might be right about materializeConstant. In this case, the right materialization is to materialize either torch.constant.int or torch.constant.float and then a torch.derefine op to derefine the result to !torch.number

This won't fix the problem. If materializeConstant returns a value with torch.number type created by torch.derefine op, it won't pass the check in `tryGetOrCreateConstant` function in FoldUtils.cpp. See [here](https://github.com/llvm/llvm-project/blob/d2613d5bb5dca0624833e4747f67db6fe3236ce8/mlir/lib/Transforms/Utils/FoldUtils.cpp#L339). Becuase we can't find any constant-like op registered in torch dialect that returns torch.number type. My local solution is returning value created by torch.constant.int or torch.contant.float directly and not converting it back to torch.number type. It looks not very elegant but indeed solves the problem. The codes looks like this:
```cpp
Operation *TorchDialect::materializeConstant(OpBuilder &builder, Attribute value, Type type, Location loc) {
...
  if (type.isa<Torch::NumberType>()) {
    if (auto floatValue = value.dyn_cast<FloatAttr>()) {
      return builder.create<Torch::ConstantFloatOp>(loc, floatValue);
    } else if (auto intValue = value.dyn_cast<IntegerAttr>()) {
      return builder.create<Torch::ConstantIntOp>(loc, intValue);
    }
  }
}
```
Will you accept this solution? If yes, I'd like to create a PR to strength the shape inference for aten.arange.start_step op.
Sorry for holding this issue so long.

**Comment by silvasean** [comment]
We should have torch.constant.number op and it should have a canonicalizer that unconditionally turns it into torch.constant.{int,float} + torch.derefine.

**Comment by Vremold** [comment]
> We should have torch.constant.number op and it should have a canonicalizer that unconditionally turns it into torch.constant.{int,float} + torch.derefine.

Thanks for the suggestions. I've opened a PR here #1367 to solve the problem.

**Comment by silvasean** [comment]
@Vremold can we close this issue?
