### ISSUE TITLE
Add a CI test to validate shapelib

### ISSUE THREAD

**Issue by powderluv** [llvm/torch-mlir#1317]
Currently CI has a test to 

```
    - name: Ensure generated files are up to date	
      if: ${{ matrix.os-arch == 'ubuntu-x86_64' && matrix.llvm-build == 'in-tree' }}	
      run: |	
        ./build_tools/update_torch_ods.sh	
        ./build_tools/update_shape_lib.sh	
        if ! git diff --quiet; then	
          echo "#######################################################"	
          echo "Generated files are not up to date (see diff below)"	
          echo ">>> Please run ./build_tools/update_torch_ods.sh and ./build_tools/update_shape_lib.sh <<<"	
          echo "#######################################################"	
          git diff --color=always	
          exit 1	
        fi
        ```

Add the equivalent in the Docker CI image.

**Comment by silvasean** [comment]
Is there a way that we can avoid duplicating the tests in build_linux_packages.sh and buildAndTest.yml? It seems redundant to specify in both.

**Comment by powderluv** [comment]
There should be no tests in buildAndTest.yml (for linux).

**Comment by powderluv** [comment]
So I would like to understand what is the expected behaviour of the test so we slot it in correctly:

When do you expect there to be a valid difference to fail the build ?  If latest PyTorch was updated we fail the local CI and ask the developer to update shape / torch ?

**Comment by silvasean** [comment]
Yes. For now, it will be like any breaking PyTorch change -- it will cause local builds to fail. The solution is to have a deliberate weekly PyTorch bump.

**Comment by silvasean** [comment]
We centralized this all to build_linux_packages.sh
