### ISSUE TITLE
Issue with `aten::_reshape_alias` op

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1348]
Hi, I'm working on supporting a model during which I encounter the `aten._reshape_alias` op as follows:
```
%355 = torch.aten._reshape_alias %352, %353, %354 : !torch.vtensor<[1,1,128],f32>, !torch.list<int>, !torch.list<int> -> !torch.vtensor<[16,1,128],f32>
```
It turns out that in the torch-mlir, we have a decomposition for this op: https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp#L2004-L2020.

This op was not getting lowered when I was compiling the model. When I debugged the issue, I discovered that the op takes three arguments: input, size, and stride resp. The value of the size and stride are as follows:
```
%353 = torch.prim.ListConstruct %int16, %int1, %int128 : (!torch.int, !torch.int, !torch.int) -> !torch.list<int>
%354 = torch.prim.ListConstruct %int128, %int128, %int1 : (!torch.int, !torch.int, !torch.int) -> !torch.list<int>
```
After seeing the size argument, we know that this can't just be decomposed into the `aten::view` since the no. of elements in the input and output are not equal. In some sense, the op for this particular use case extends the tensor's size. 

I have two questions to ask:
1.) How to support this kind of case for this op, since it can't be just decomposed into the view op?
2.) When I separately tested this op's validity, it threw the following error:
```
>>> a = torch.rand(1,1,128)
>>> torch.ops.aten._reshape_alias(a, size=(16, 1, 128), stride=(128, 128, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.8/site-packages/torch/_tensor.py", line 423, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.8/site-packages/torch/_tensor_str.py", line 602, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.8/site-packages/torch/_tensor_str.py", line 565, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.8/site-packages/torch/_tensor_str.py", line 327, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.8/site-packages/torch/_tensor_str.py", line 359, in get_summarized_data
    start = [self[i] for i in range(0, PRINT_OPTS.edgeitems)]
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.8/site-packages/torch/_tensor_str.py", line 359, in <listcomp>
    start = [self[i] for i in range(0, PRINT_OPTS.edgeitems)]
RuntimeError: setStorage: sizes [1, 128], strides [128, 1], storage offset 128, and itemsize 4 requiring a storage size of 1024 are out of bounds for storage of size 512
```
If this op's arguments are invalid, how does it get generated during the `TorchScript -> Torch-IR` pass?

**Comment by vivekkhandelwal1** [comment]
@silvasean @ramiro050 @makslevental PTAL

**Comment by silvasean** [comment]
This is probably better as a PyTorch bug against the upstream decomposition

**Comment by vivekkhandelwal1** [comment]
I'm closing this since the bug was with some other op.
