### ISSUE TITLE
Packages can't be fetched from releases page automatically

### ISSUE THREAD

**Issue by silvasean** [llvm/torch-mlir#1374]
It appears that Github changed their HTML for the [releases page](https://github.com/llvm/torch-mlir/releases) so that it loads the links via javascript.

This means that `pip install -f https://github.com/llvm/torch-mlir/releases` no longer sees any package links on that page, which makes it fail to install `torch-mlir`.

IREE has a similar packaging system, so roping in @GMNGeoffrey @stellaraccident since any solution there is probably shareable.

**Comment by ramiro050** [comment]
Github, as of yesterday, seems to have gone back to generating a `releases` page with all the links in the html, so this should no longer be an issue. As far as I know, this issue did not affect IREE's releases page.

It seems that this was affecting some repositories but not all of them. See: https://github.com/Homebrew/brew/issues/13853

**Comment by silvasean** [comment]
Thanks Ramiro, let's close this then! @dellis23 you should be able to go back to using the releases page for the install in your colab then.

**Comment by ramiro050** [comment]
> I just had to reopen [Homebrew/brew#13853](https://github.com/Homebrew/brew/issues/13853) due to this issue reappearing. Not sure if you all are affected at the moment, but it's something to be cognizant of.

Ha! I just tried it again right now and it is once again not working. Thanks for the heads-up

**Comment by powderluv** [comment]
We did a temporary workaround in the SHARK repo to find the expanded_assets link:

https://github.com/nod-ai/SHARK/blob/main/setup_venv.sh#L74-L79

Anyway to message Github about it?

**Comment by silvasean** [comment]
@asl does the LLVM Foundation have a way for us to message github about this issue?

**Comment by asl** [comment]
@silvasean Unfortunately, no :(

**Comment by ramiro050** [comment]
@GMNGeoffrey, this is now affecting IREE as well:

```shell
$ pip install iree-compiler --find-links https://github.com/iree-org/iree/releases --no-index
Looking in links: https://github.com/iree-org/iree/releases
ERROR: Could not find a version that satisfies the requirement iree-compiler (from versions: none)
ERROR: No matching distribution found for iree-compiler
```

The HTML for the `releases` page no longer has download links in it.

**Comment by stellaraccident** [comment]
We need to acquire/craft a script that generates a pip index file and then publish that. It is probably no more than ~a hundred lines of code. But I don't just have it handy...

**Comment by stellaraccident** [comment]
Index specification: https://peps.python.org/pep-0503/

The script should scrape the releases API and publish the set of files. We would need to figure out where to put them. Could be a cloud storage bucket, branch in the git repo served raw, or gh-pages

**Comment by dellis23** [comment]
I wrote a quick script to parse the releases page: https://gist.github.com/dellis23/eac78bdde36b7b22d58bc13f8a0608e6

It seems to install from the output page for me just fine.

**Comment by silvasean** [comment]
Thanks Daniel! Can you create a GitHub actions that runs that hourly and pushes that to a destination? Perhaps the gh-pages branch using GitHub pages to serve the HTML file.

You can model the action on this one, but running your script instead: https://github.com/llvm/torch-mlir/blob/main/.github/workflows/releaseSnapshotPackage.yml

**Comment by dellis23** [comment]
> Here is a quickstart for GH pages -- it is literally just a branch with some HTML files in it: https://docs.github.com/en/pages/quickstart

I created a branch, but I might be missing some permissions to set up the github pages repo.  Do you see this settings tab in your view?

![image](https://user-images.githubusercontent.com/1346302/191283413-a05f718b-0ceb-477d-adcf-15e06ee5363f.png)

**Comment by dellis23** [comment]
> Here is a quickstart for GH pages -- it is literally just a branch with some HTML files in it: https://docs.github.com/en/pages/quickstart

I think I might be missing some permissions on the repo.  Do you see a settings tab?

![image](https://user-images.githubusercontent.com/1346302/191284096-090406b1-bb83-46d5-af6f-8d80ca76173d.png)

**Comment by silvasean** [comment]
Hey Dan, can you try now? If not, I can set up the boilerplate.

**Comment by dellis23** [comment]
> Hey Dan, can you try now? If not, I can set up the boilerplate.

Yup, I've got a few new tabs now, thanks!  Will work on setting this up.

**Comment by dellis23** [comment]
Update: I now have the releases being autogenerated [here](https://github.com/llvm/torch-mlir/blob/github-pages/index.html.  Unfortunately I've run into a number of issues getting github pages to publish this correctly, and pip won't install directly from the file because the content type is `text/plain`.  Gonna keep trying to find a workaround.

**Comment by dellis23** [comment]
I've prepared a PR to automatically generate the releases page every hour.  It should be available at https://llvm.github.io/torch-mlir/

**Comment by powderluv** [comment]
awesome. Since we build only once a day it could be slower.

**Comment by dellis23** [comment]
Yeah, that would make the potential delay be up to a day though.  Unless there's a way to make this job downstream of the other or we can rely on consistent timing.  Either way, this is about as lightweight of a job as it gets, so I don't think it matters.

**Comment by p-linnane** [comment]
Update from GitHub support:

>I've heard back from the engineering team now.
>
>They confirm that we have indeed recently made some changes to render the asset lists on Releases collapsed by default, for performance reasons.
>
>It sounds like these projects have been doing some web scraping to find the asset download URLs, and now that web scraping has broken, because it isn't aware that the asset list will start out collapsed by default.
>
>Our recommended method of getting such a list would be to instead use the [Release assets API](https://docs.github.com/en/rest/releases/assets#list-release-assets) to programmatically obtain the list of asset download URLs. The API response would provide the download URLs that they want.
>
>I hope that is an acceptable solution, and it should lead to a more robust process, as APIs are not prone to refactoring in the same way web pages are.

**Comment by silvasean** [comment]
@p-linnane thsnk for digging into this! I don't think that the "Release assets API" works with the `-f ` flag on `pip`, so it doesn't solve the problem.

**Comment by p-linnane** [comment]
> @p-linnane thsnk for digging into this! I don't think that the "Release assets API" works with the `-f ` flag on `pip`, so it doesn't solve the problem.

Not trying to present it as a solution. Just wanted everyone to know GitHub's actual stance on this.

**Comment by GMNGeoffrey** [comment]
Thanks @p-linnane, I think it would be good to mention to them that this isn't some custom thing we've built, but rather leveraging a feature built-in to `pip`. So the GitHub releases go from "works directly with pip's `--find-links`" to "require some custom solution". Of course, that doesn't mean they need to support it, and indeed scraping webpages seems pretty brittle

**Comment by dellis23** [comment]
This should be installable from the releases page now.

e.g.:

```
pip install torch-mlir --find-links https://llvm.github.io/torch-mlir/package-index/
```

**Comment by GMNGeoffrey** [comment]
In https://github.com/iree-org/iree/issues/9532 we're discussing what to do about this long-term for IREE (I've made the same short-term fix as you did here). Of course, sticking with this approach is option 1 :-) If y'all have input/opinions, I would be happy to hear them. One thing that would be nice is to have some amount of standardization to reduce the cognitive load on users.

**Comment by dellis23** [comment]
Hmm.  The only other idea I have off the top of my head is to do this in a centralized fashion for all IREE repos so we don't have to keep reimplementing it for all the sub-projects.  Though this isn't an IREE repo, so I guess that wouldn't help this project!

The other tradeoff there is that we wouldn't be able to schedule it as a downstream job of a release being built.

**Comment by powderluv** [comment]
Can we just publish to PyPi and use the `--pre` channel for nightlies and non `--pre` for stable ones ?

**Comment by GMNGeoffrey** [comment]
Please see the linked issue 🙂 there are concerns about PyPI's storage limitations

**Comment by dellis23** [comment]
Isn't the main issue in that thread with storage only if we store nightlies on pypi?  It seems like @powderluv's solution would solve the storage issue since only stable releases would be pushed to pypi.

**Comment by GMNGeoffrey** [comment]
We (IREE) already upload our stable releases to PyPI. The original request was to also upload the unstable releases, which enables accessing them with the PyPI `--pre` flag. Perhaps torch isn't using PyPI at all right now? I'd certainly recommend using it for stable releases. To discuss what IREE should do with nightlies, please comment on that other issue though

**Comment by dellis23** [comment]
I see. Things are probably getting confusing because `torch-mlir` (this repo) isn't publishing to PyPI.  Torch proper does.

**Comment by powderluv** [comment]
I think we are ready to publish. @silvasean setup the pieces and now the CI is ready. @dellis23 lmk if you want to take a crack at it. You need access to the PyPI credentials in the project.

**Comment by silvasean** [comment]
@dellis23 what is your PyPI username? I can add you as a collaborator.

**Comment by DaveScream** [comment]
Still persists

Looking in links: https://llvm.github.io/torch-mlir/package-index/, https://nod-ai.github.io/SHARK-Runtime/pip-release-links.html, https://download.pytorch.org/whl/nightly/torch/
Obtaining file:///home/anton/SHARK
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Looking in links: https://llvm.github.io/torch-mlir/package-index/, https://nod-ai.github.io/SHARK-Runtime/pip-release-links.html, https://download.pytorch.org/whl/nightly/torch/
      Collecting setuptools>=42
        Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting packaging
        Using cached packaging-22.0-py3-none-any.whl (42 kB)
      Collecting numpy>=1.22.4
        Using cached numpy-1.24.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
      ERROR: Could not find a version that satisfies the requirement torch-mlir>=20221021.633 (from versions: none)
      ERROR: No matching distribution found for torch-mlir>=20221021.633
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Before running examples activate venv with:

**Comment by powderluv** [comment]
I think the venv is Python 3.8 and there are no binary packages for 3.8. We only support 3.10 (and hopefully 3.11 soon).
