### ISSUE TITLE
Support for Byte datatype

### ISSUE THREAD

**Issue by AmosLewis** [llvm/torch-mlir#1383]
I am trying to lower GPT2 torch model to linalg in this link:
[https://github.com/nod-ai/SHARK/pull/341](https://github.com/nod-ai/SHARK/pull/341)
[https://github.com/nod-ai/SHARK/issues/337](https://github.com/nod-ai/SHARK/issues/337)
but get the following bug.
```
File "torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 233, in compile
      mb.import_module(scripted._c, class_annotator, import_options)
  raise Exception(f"""
Exception: 
PyTorch TorchScript module -> torch-mlir Object Graph IR import failed with:
### Importer C++ Exception:
Unsupported import tensor type: (1,1,.,.) .....
[ CPUByteType{1,1,1024,1024} ]
```
I am planning to add a datatype of Byte just like this patch [https://github.com/llvm/torch-mlir/pull/1169](https://github.com/llvm/torch-mlir/pull/1169)?
Any suggestion @silvasean?

**Comment by silvasean** [comment]
SGTM!

**Comment by AmosLewis** [comment]
> SGTM!

Could you add me as a contributor, so I can PR my code?

**Comment by silvasean** [comment]
Can we close this? #1384 landed.
