### ISSUE TITLE
Build failing with "no matching function for call to 'convert'"

### ISSUE THREAD

**Issue by dellis23** [llvm/torch-mlir#1396]
See here: https://github.com/llvm/torch-mlir/actions/runs/3098310406/jobs/5016066081#step:4:41827

I _think_ this is the relevant error.

```
/main_checkout/torch-mlir/libtorch/include/c10/util/Optional.h:786:29: error: no matching function for call to 'convert'
    return *this ? **this : detail_::convert<T>(constexpr_forward<V>(v));
                            ^~~~~~~~~~~~~~~~~~~
/main_checkout/torch-mlir/build_oot/python/torch_mlir/csrc/base_lazy_backend/generated/LazyNativeFunctions.cpp:726:89: note: in instantiation of function template specialization 'c10::optional<long>::value_or<at::Tensor>' requested here
        LazyTensorPtr lazy_storage_offset = torch::lazy::TryGetLtcTensor(storage_offset.value_or(at::Tensor()));
```

**Comment by dellis23** [comment]
I think this particular issue is resolved now.  We may still be having occasionally other build issues, but I don't think the primary discussion is happening here.

Other issues I know of:

 * https://github.com/llvm/torch-mlir/issues/1434
 * https://github.com/llvm/torch-mlir/issues/1364

**Comment by silvasean** [comment]
We are now pinning the PyTorch revision and so this should happen a lot less.
