### ISSUE TITLE
Recommended tool `torch-mlir-opt` not found

### ISSUE THREAD

**Issue by dellis23** [llvm/torch-mlir#1404]
The exception from #1076 suggests using `torch-mlir-opt` to debug a problem.  When I try to do so, I get the following error, even when I have activated the environment `torch-mlir` is installed in:

```bash
(venv) $ torch-mlir-opt -pass-pipeline='torchscript-module-to-torch-backend-pipeline{backend-legal-ops=torch.aten.flatten.using_ints}' /tmp/MyModel.mlir
bash: torch-mlir-opt: command not found
```

**Comment by ramiro050** [comment]
The `torch-mlir-opt` tool should be located in `{TORCH_MLIR_BUILD_DIR}/bin/`.

**Comment by dellis23** [comment]
Yeah, it seems like we should either update the error to point to that directory or add it to the path when the user installs via pip (I believe via [`entry_points`](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html)).

**Comment by dellis23** [comment]
I didn't realize `torch-mlir-opt` was a compiled tool.  This should still be accomplishable (via `scripts` rather than `entry_points`).  I see we're already publishing wheels, so I think we'd just need to include the script in the generated wheel and then expose it at install time.  I'll look into how difficult this would be.

**Comment by silvasean** [comment]
torch-mlir-opt is a tool that should only be used by Torch-MLIR developers. Users of Torch-MLIR should not use `torch-mlir-opt` (unless they themselves are developers of Torch-MLIR). Maybe the error should say "*For developers of Torch-MLIR*, the error can be reproduced by ..."

**Comment by dellis23** [comment]
Sure, I can update the error message.
