### ISSUE TITLE
Enable VerifyBackendContract in base lazy backend.

### ISSUE THREAD

**Issue by GlebKazantaev** [llvm/torch-mlir#1460]
### Description
This issue is a remaining part of https://github.com/llvm/torch-mlir/pull/1412 (see discussions in this PR to understand the purpose of VerifyBackendContract pass in base lazy backend).

### Details
To enable `VerifyBackendContract` we have either to figure out how to detach MlirOperation from MlirModule after pass manager execution or update `TorchMlirComputation` and some other facilities to work with MlirModule. From my point of view the second option is more preferable as it looks more generic and detaching approach looks like workaround.

Assignee: @GlebKazantaev

**Comment by GlebKazantaev** [comment]
Hi @silvasean, I have some thoughts regarding out discussion about backend contract and LTC violations. I did more investigation about `ScalarImplicit` and `!torch.number` type which is unsupported by `satisfiesBackendContract` https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp#L146

So the first concern is that original LTC graph we are trying to convert to torch-mlir doesn't consist of any `!torch.number` types. The reason why we get them later is because in [our torch-mlir code during](https://github.com/llvm/torch-mlir/blob/main/python/torch_mlir/csrc/base_lazy_backend/mlir_node_lowering.cpp#L278-L284) `Scalar::Lower` we convert scalar value to tensor `at::scalar_tensor(value, options)`. So in cases when consumer of `Scalar` requires `Tensor` type, we just insert `prim::Constant[value={1}]()` and no additional type alignment happens. But when the `Scalar` consumer requires scalar literal but we return `Tensor` type, so the type [alignment mechanism start working](https://github.com/GlebKazantaev/pytorch/blob/master/torch/csrc/jit/frontend/schema_matching.cpp#L137) and insert `ScalarImplicit` operation with `!torch.number` type.
From my point of view this is rather torch-mlir issue than a PyTorch LTC violation. To avoid this type alignment we need to know consumers types inside `TorchMlirNode::Lower`. But unfortunately `lazy::Node` stores only operands, so we don't have an access to consumer types during lowering.

I also wonder, is it a real problem with `!torch.number` type? Can we just extend the list of scalar types here https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp#L33 with `NumberType` ? From backends perspective this is a normal type like others, so they can handle it.

**Comment by silvasean** [comment]
> So the first concern is that original LTC graph we are trying to convert to torch-mlir doesn't consist of any `!torch.number` types. The reason why we get them later is because in [our torch-mlir code during](https://github.com/llvm/torch-mlir/blob/main/python/torch_mlir/csrc/base_lazy_backend/mlir_node_lowering.cpp#L278-L284) `Scalar::Lower` we convert scalar value to tensor `at::scalar_tensor(value, options)`. So in cases when consumer of `Scalar` requires `Tensor` type, we just insert `prim::Constant[value={1}]()` and no additional type alignment happens. But when the `Scalar` consumer requires scalar literal but we return `Tensor` type, so the type [alignment mechanism start working](https://github.com/GlebKazantaev/pytorch/blob/master/torch/csrc/jit/frontend/schema_matching.cpp#L137) and insert `ScalarImplicit` operation with `!torch.number` type.

This sounds like an implementation detail of the current LTC code, not a fundamental architectural issue. Fundamentally, Scalar knows its type. Can you explain why it is so critical for LTC to lose that type information when lowering, that we are discussing a major architectural change to Torch-MLIR to work around it?

> I also wonder, is it a real problem with `!torch.number` type? Can we just extend the list of scalar types here https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp#L33 with `NumberType` ? From backends perspective this is a normal type like others, so they can handle it.

`!torch.number` is a Pythonism. In order to maintain a correctly layered system, lower level compilers should not be exposed to it.

**Comment by GlebKazantaev** [comment]
> Fundamentally, Scalar knows its type.

In `class Scalar: public TorchMlirNode` we have only two members: [c10::Scalar](https://github.com/pytorch/pytorch/blob/master/c10/core/Scalar.h#L35) and [c10::ScalarType](https://github.com/pytorch/pytorch/blob/master/c10/core/ScalarType.h) and they don't have any information that could help us to lower it either to tensor os scalar literal. That's why we use generic approach with [scalar_tensor](https://github.com/llvm/torch-mlir/blob/main/python/torch_mlir/csrc/base_lazy_backend/mlir_node_lowering.cpp#L284) which invokes type alignment when tensor consumer requires scalar literal.

> major architectural change to Torch-MLIR to work around it

It was just an assumption for `Scalar::Lowering` to make it more precise, and it is probably not worth it because of complexity and amount of changes. So I was thinking more about solution like this: https://github.com/llvm/torch-mlir/blob/main/python/torch_mlir/csrc/base_lazy_backend/mlir_lowering_context.cpp#L131 where we apply pass to the JIT graph. The same thing we can do with this `NumberType`. What do you think?

**Comment by silvasean** [comment]
I don't have any objection in principle to running JIT IR passes first, since that does not affect Torch-MLIR's architecture.

I still think that there must be some way to directly produce the correct IR (by avoiding this scalar_tensor/ScalarImplicit information loss), which I think is overall the best solution here. But I can sympathize if that would be a big change. The other advantage of directly producing the correct IR is that it would reduce compile time by avoiding running another pass.

**Comment by GlebKazantaev** [comment]
PR to PyTorch: https://github.com/pytorch/pytorch/pull/86692

**Comment by GlebKazantaev** [comment]
Some updates:
* JIT pass to handle ScalarImplicit https://github.com/pytorch/pytorch/pull/92095
* Enable `VerifyBackendContract` in TorchMLIR https://github.com/llvm/torch-mlir/pull/1798

**Comment by GlebKazantaev** [comment]
Changes were merged! https://github.com/llvm/torch-mlir/pull/1798
