### ISSUE TITLE
Compiled gradient function returns incorrect values

### ISSUE THREAD

**Issue by dellis23** [llvm/torch-mlir#1464]
There are a few repos involved here (IREE, torch-mlir, and iree-torch), and I don't exactly know for sure this is a `torch-mlir` problem.  I figure this is probably a good starting point for investigation.

Script to reproduce the issue:

```python
import argparse

import functorch
import iree_torch
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import torch
import torch_mlir


# Dataset
X, y, coef = make_regression(n_features=3, coef=True)
X, X_test, y, y_test = train_test_split(X, y)

# Weights
w = torch.zeros(X.shape[1:], dtype=torch.double)
b = torch.tensor(0., dtype=torch.double)


def forward(w, b, X):
    return torch.matmul(X, w) + b


def loss_fn(w, b, X, y):
    err = forward(w, b, X) - y
    return torch.mean(torch.square(err))


grad_fn = functorch.grad(loss_fn, argnums=(0, 1))


def update(w, b, grad_w, grad_b):
    updated_w = torch.tensor(list(map(
        lambda x: x[0] - 0.05 * x[1], zip(w, grad_w))), dtype=torch.double)
    updated_b = torch.tensor(b - 0.05 * grad_b, dtype=torch.double)
    return updated_w, updated_b


def train(w, b, X, y):
    grad_w, grad_b = grad_fn(w, b, X, y)
    return update(w, b, grad_w, grad_b)


def _get_argparse():
    parser = argparse.ArgumentParser(
        description="Train and run a regression model.")
    parser.add_argument("--iree-backend",
        default="llvm-cpu",
        help="See https://iree-org.github.io/iree/deployment-configurations/ "
             "for the full list of options.")
    return parser


def main():
    args = _get_argparse().parse_args()

    # Training
    print("Compiling training function with Torch-MLIR")
    train_args = (w, b,
        torch.tensor(X_test[:1], dtype=torch.double),
        torch.tensor(y_test[:1], dtype=torch.double))
    linalg_on_tensors_mlir = torch_mlir.compile(
        functorch.make_fx(train)(*train_args),
        train_args,
        output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,
        use_tracing=True)
    iree_vmfb = iree_torch.compile_to_vmfb(
        linalg_on_tensors_mlir, args.iree_backend)
    invoker = iree_torch.load_vmfb(iree_vmfb, args.iree_backend)

    print("Original output:")
    args = (torch.tensor([1.0, 2.0, 3.0], dtype=torch.double),
            torch.tensor(1.0, dtype=torch.double),
            torch.tensor([[1.0, 1.0, 1.0]], dtype=torch.double),
            torch.tensor([1.0], dtype=torch.double))
    print(train(*args))
    print()
    print("IREE output:")
    print(invoker.forward(*args))


if __name__ == "__main__":
    main()
```

The output:

```
Original output:
(tensor([0.4000, 1.4000, 2.4000], dtype=torch.float64), tensor(0.4000, dtype=torch.float64))

IREE output:
(tensor([ 3.0506e+06, 5.3238e-315,  0.0000e+00], dtype=torch.float64), tensor(1.5807e-314, dtype=torch.float64))
```

I'm happy to try debugging further if there's nothing I'm doing that's obviously wrong.

**Comment by ramiro050** [comment]
Nothing in the script looks odd to me. If you can copy the MLIR at the `OutputType.TORCH` and `OutputType.LINALG_ON_TENSORS` here, I can also take a look and see if anything stands out. (you can get the IR by doing `print(linalg_on_tensors_mlir)`)

**Comment by dellis23** [comment]
[Linalg on tensors output](https://gist.github.com/dellis23/2ebe6b559c18d1a74753964892ebf5be)

[Torch output](https://gist.github.com/dellis23/37aaec2e657fb146c115165463cc0ba2)

**Comment by ramiro050** [comment]
Regarding the first result from the graph, it is strange that the tensor [is hardcoded into the graph](https://gist.github.com/dellis23/2ebe6b559c18d1a74753964892ebf5be#file-output-py-L8) and no changes are made to it in the entire computation. Maybe using `use_tracing=True` is causing problems here.

**Comment by dellis23** [comment]
> Regarding the first result from the graph, it is strange that the tensor [is hardcoded into the graph](https://gist.github.com/dellis23/2ebe6b559c18d1a74753964892ebf5be#file-output-py-L8) and no changes are made to it in the entire computation. Maybe using `use_tracing=True` is causing problems here.

Interesting.  That would explain why the weights don't change with each iteration.

That being said, what syntax would I use to get this working without tracing?  I believe `use_tracing` is just a convenience wrapper around doing it manually.  If I skip that step altogether (i.e just do `use_tracing=False`), I get this error:

```python
Traceback (most recent call last):
  File "/usr/local/google/home/danielellis/iree-torch/examples/regression_repro.py", line 85, in <module>
    main()
  File "/usr/local/google/home/danielellis/iree-torch/examples/regression_repro.py", line 63, in main
    linalg_on_tensors_mlir = torch_mlir.compile(
  File "/usr/local/google/home/danielellis/venv.iree-torch/lib/python3.10/site-packages/torch_mlir/__init__.py", line 215, in compile
    scripted = torch.jit.script(model)
  File "/usr/local/google/home/danielellis/venv.iree-torch/lib/python3.10/site-packages/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/usr/local/google/home/danielellis/venv.iree-torch/lib/python3.10/site-packages/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/usr/local/google/home/danielellis/venv.iree-torch/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/usr/local/google/home/danielellis/venv.iree-torch/lib/python3.10/site-packages/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
attribute lookup is not defined on builtin:
  File "<eval_with_key>.0", line 6
def forward(self, w_1, b_1, X_1, y_1):
    x_1 = X_1
    mv = torch.ops.aten.mv.default(x_1, w_1)
         ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    add = torch.ops.aten.add.Tensor(mv, b_1);  mv = None
    sub = torch.ops.aten.sub.Tensor(add, y_1);  add = y_1 = None
```

**Comment by ramiro050** [comment]
`use_tracing=False` should work. However, you do need to remove the overloads from each op. See: https://github.com/pytorch/pytorch/issues/84494#issuecomment-1235955989

**Comment by ramiro050** [comment]
I think `strip_overloads` changes things in place. Can you try doing strip overloads on the graph, then passing that graph into `torch_mlir.compile`?

**Comment by dellis23** [comment]
Whoops, good catch.  It runs now, but with the same divergence in output, unfortunately:

```
Original output:
(tensor([0.4000, 1.4000, 2.4000], dtype=torch.float64), tensor(0.4000, dtype=torch.float64))

IREE output:
(tensor([ 2.3975e+05, 1.5930e-314,  0.0000e+00], dtype=torch.float64), tensor(1.5807e-314, dtype=torch.float64))
```

**Comment by ramiro050** [comment]
> `use_tracing=False` should work. However, you do need to remove the overloads from each op. See: [pytorch/pytorch#84494 (comment)](https://github.com/pytorch/pytorch/issues/84494#issuecomment-1235955989)

Ah never mind. The div op gets folded because it's division by 1.

**Comment by dellis23** [comment]
To help narrow things down further, it seems that running the traced graph directly gives the correct results (with and without doing `strip_overloads`:

```python
    dummy_args = (torch.tensor([1.0, 2.0, 3.0], dtype=torch.double),
            torch.tensor(1.0, dtype=torch.double),
            torch.tensor([[1.0, 1.0, 1.0]], dtype=torch.double),
            torch.tensor([1.0], dtype=torch.double))
    graph = functorch.make_fx(train)(*dummy_args)
    print("Graph output:")
    print(graph(*dummy_args))
```

This gives:

```python
Graph output:
(tensor([0.4000, 1.4000, 2.4000], dtype=torch.float64), tensor(0.4000, dtype=torch.float64))
```

**Comment by ramiro050** [comment]
I found an interesting bug that affects your program: https://github.com/iree-org/iree/issues/10663. If you change types to `torch.float` we should get closer to having things working.

Also, I did notice that if you run `torch.jit.script(graph)(*dummy_args)`, you get something that looks more like what the iree-compiled graph should be producing.

**Comment by dellis23** [comment]
I spoke too soon.  The same values were being returned, but we appear to still be just returning a constant from the graph.

https://gist.github.com/dellis23/2565ecc614ec1d4520ee8dc54d85abb1#file-output-py-L7

(Note the return of `cst`)

I get the following weights and biases after 30 training steps:

```python
tensor([0., 0., 0.]) tensor(0.)
tensor([0.4000, 1.4000, 2.4000]) tensor(-3.2475)
# ...
tensor([0.4000, 1.4000, 2.4000]) tensor(-86571.0859)
```

(Updated script [here](https://gist.github.com/dellis23/d425d50f7d678e25f95d6994f6d80d6b)).

**Comment by dellis23** [comment]
For posterity, I filed https://github.com/pytorch/functorch/issues/1046, since it seems the issue is upstream of `torch-mlir`.

**Comment by dellis23** [comment]
I believe I've ironed out the various issues here (see https://github.com/pytorch/functorch/issues/1046 for the resolution).  I found a couple more potential issues I'll file separately.
