### ISSUE TITLE
Failed to legalize operation 'torch.aten.empty_like' that was explicitly marked illegal

### ISSUE THREAD

**Issue by jimw567** [llvm/torch-mlir#1468]
I am trying to generate torch-mlir for my model, but torch-mlir-opt errors out with the message "Failed to legalize operation 'torch.aten.empty_like' that was explicitly marked illegal". I am able to create a small testcase to reproduce the issue. Run the command line below on the attached file to see the error

./build/bin/torch-mlir-opt --debug --debug --torch-decompose-complex-ops tinyyolov2-ir-after-decompose-complex-ops.mlir.txt

[tinyyolov2-ir-after-decompose-complex-ops.mlir.txt](https://github.com/llvm/torch-mlir/files/9722809/tinyyolov2-ir-after-decompose-complex-ops.mlir.txt)

Below is the log from my run:
Legalizing operation : 'torch.aten.empty_like'(0x8e2cab0) {
  %38 = "torch.aten.empty_like"(%37, %12, %13, %36, %11, %10) : (!torch.vtensor<*,f32>, !torch.int, !torch.int, !torch.Device, !torch.bool, !torch.none) -> !torch.vtensor<[1,3,224,224],f32>

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'torch.aten.empty_like -> ()' {
Trying to match "(anonymous namespace)::DecomposeAtenEmptyLikeOp"
    ** Insert  : 'torch.aten.size'(0x8e3e140)
    ** Insert  : 'torch.aten.empty.memory_format'(0x8e464d0)
    ** Replace : 'torch.aten.empty_like'(0x8e2cab0)
"(anonymous namespace)::DecomposeAtenEmptyLikeOp" result 1

    //===-------------------------------------------===//
    Legalizing operation : 'torch.aten.size'(0x8e3e140) {
      %38 = "torch.aten.size"(%37) : (!torch.vtensor<*,f32>) -> !torch.list<int>

      * Fold {
      } -> FAILURE : unable to fold

      * Pattern : 'torch.aten.size -> ()' {
Trying to match "(anonymous namespace)::DecomposeAtenSizeOp"
        ** Failure : Unimplemented: unranked tensor
"(anonymous namespace)::DecomposeAtenSizeOp" result 0
      } -> FAILURE : pattern failed to match
    } -> FAILURE : no matched legalization pattern
    //===-------------------------------------------===//
  } -> FAILURE : failed to legalize generated operation 'torch.aten.size'(0x0000000008E3E140)
} -> FAILURE : pattern failed to match
} -> FAILURE : no matched legalization pattern
//===-------------------------------------------===//
tinyyolov2-ir-after-decompose-complex-ops.mlir.txt:40:9: error: failed to legalize operation 'torch.aten.empty_like' that was explicitly marked illegal
  %14 = torch.aten.empty_like %13, %int6, %int0, %cpu, %false, %none : !torch.vtensor<*,f32>, !torch.int, !torch.int, !torch.Device, !torch.bool, !torch.none -> !torch.vtensor<[1,3,224,224],f32>
        ^
tinyyolov2-ir-after-decompose-complex-ops.mlir.txt:40:9: note: see current operation: %38 = "torch.aten.empty_like"(%37, %12, %13, %36, %11, %10) : (!torch.vtensor<*,f32>, !torch.int, !torch.int, !torch.Device, !torch.bool, !torch.none) -> !torch.vtensor<[1,3,224,224],f32>
ImplicitTypeIDRegistry::lookupOrInsert(mlir::detail::PreservedAnalyses::AllAnalysesType)

**Comment by ramiro050** [comment]
Hi @jimw567, I think we addressed this issue in office hours. Do you have any other questions regarding this issue?

**Comment by jimw567** [comment]
Thanks @ramiro050 ! I am all set with this issue.
