### ISSUE TITLE
Investigate UpSampleNearest2dDynamicFactor failure after PyTorch version update

### ISSUE THREAD

**Issue by ashay** [llvm/torch-mlir#1473]
The `UpSampleNearest2dDynamicFactor_basic` test fails on the refbackend and eager_mode backend after updating the PyTorch version to 1.14.0.dev20221010.  To reproduce the error:

1. Update the PyTorch version in pytorch-requirements.txt
2. Update PyTorch: `python3 -m pip install --user --upgrade -r requirements.txt`
3. Run the test on the reference backend: `python -m e2e_testing.main --config=refbackend -s -v --filter=UpSampleNearest2dDynamicFactor_basic`

Since the test fails after update the PyTorch version (and since the LLVM version is unchanged), it's likely that the oracle is incorrect, but if someone who is more knowledgeable of `torch._C._nn.upsample_nearest2d()` can confirm, then that would be very helpful.

**Comment by xgupta** [comment]
Not able to reproduce the issue, refbackend is not available - 

```
python -m e2e_testing.main --config=refbackend -s -v --filter=UpSampleNearest2dDynamicFactor_basic      
usage: main.py [-h] [-c {native_torch,torchscript,linalg,mhlo,tosa,lazy_tensor_core,torchdynamo}] [-f FILTER] [-v] [-s] [--crashing_tests_to_not_attempt_to_run_and_a_bug_is_filed TEST [TEST ...]]
main.py: error: argument -c/--config: invalid choice: 'refbackend' (choose from 'native_torch', 'torchscript', 'linalg', 'mhlo', 'tosa', 'lazy_tensor_core', 'torchdynamo')
```

**Comment by pashu123** [comment]
> Not able to reproduce the issue, refbackend is not available -
> 
> ```
> python -m e2e_testing.main --config=refbackend -s -v --filter=UpSampleNearest2dDynamicFactor_basic      
> usage: main.py [-h] [-c {native_torch,torchscript,linalg,mhlo,tosa,lazy_tensor_core,torchdynamo}] [-f FILTER] [-v] [-s] [--crashing_tests_to_not_attempt_to_run_and_a_bug_is_filed TEST [TEST ...]]
> main.py: error: argument -c/--config: invalid choice: 'refbackend' (choose from 'native_torch', 'torchscript', 'linalg', 'mhlo', 'tosa', 'lazy_tensor_core', 'torchdynamo')
> ```

There was a typo: I think it should be `--config=linalg`.

**Comment by xgupta** [comment]
It is passing  now-

python -m e2e_testing.main --config=linalg -s -v --filter=UpSampleNearest2dDynamicFactor_basic
Compiling UpSampleNearest2dDynamicFactor_basic...
Running UpSampleNearest2dDynamicFactor_basic...
PASS - "UpSampleNearest2dDynamicFactor_basic"

Summary:
    Passed: 1

**Comment by ashay** [comment]
Thanks @xgupta for trying it out!  It looks like this test has been re-enabled and has been running for a while now.  Closing the issue since the problem has been resolved.
