### ISSUE TITLE
Shape function issue with BLOOM float16

### ISSUE THREAD

**Issue by gpetters94** [llvm/torch-mlir#1474]
I'm working on getting BLOOM to work converted to fp16. I've managed to get the conversion working in pure PyTorch, but compiling to torch-mlir fails with the following:

```
/home/gap/SHARK/cuda_venv/lib/python3.10/site-packages/transformers/models/bloom/modeling_bloom.py:1015:0: error: 'func.call' op operand type mismatch: expected operand type '!torch.float', but provided '!torch.number' for operand number 0
/home/gap/SHARK/cuda_venv/lib/python3.10/site-packages/transformers/models/bloom/modeling_bloom.py:1015:0: note: see current operation: %1948 = "func.call"(%1906, %1944, %1945, %1946, %1947) {callee = @__torch_mlir_shape_fn.aten.arange} : (!torch.number, !torch.optional<int>, !torch.optional<int>, !torch.optional<Device>, !torch.optional<bool>) -> !torch.list<int>
```

[Here's](https://gist.github.com/gpetters94/61440f056218f31e9d3802df7a24c5e4) the MLIR I'm running this on - it looks like [this](https://gist.github.com/gpetters94/61440f056218f31e9d3802df7a24c5e4#file-bloomforsequenceclassificationunshrunk-mlir-L7047) is the op that is causing the error, namely that `aten.arange` is being passed a `torch.number` when it's expecting a `torch.float`.

This looks like it's happening in the torchscript to torch backend pipeline, and I'm not very familiar with that. I'm not even sure if this is our issue or if it's something we need to talk to PyTorch about. I'd appreciate if someone more familiar with this pipeline could take a look and see what's going on here.

**Comment by gpetters94** [comment]
Another possibility is that it's something to do with cuda. To get the model converted I had to use the cuda version of PyTorch which I know isn't what we currently support, but no cuda ops stood out in my readthrough of the MLIR.

**Comment by pashu123** [comment]
@gpetters94 Could you share the python script? I can take a look.

**Comment by silvasean** [comment]
This looks like a duplicate of this issue: https://github.com/llvm/torch-mlir/issues/1077
See my suggested fix there.

**Comment by gpetters94** [comment]
> This looks like a duplicate of this issue: #1077 See my suggested fix there.

Okay, that looks like it might've fixed it.
