### ISSUE TITLE
Make enabling asan easier

### ISSUE THREAD

**Issue by stellaraccident** [llvm/torch-mlir#150]
Dumping here repro steps that got asan working on a ubuntu 20.04 system. The default way that LLVM handles this does not seem to play well with shared libraries.

```
unset CC
unset CXX
export CC
export CXX

./build_tools/install_mlir.sh -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DLLVM_USE_SANITIZER=Address
./build_tools/cmake_configure.sh -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DLLVM_USE_SANITIZER=Address
cd build
ninja
export LSAN_OPTIONS=detect_leaks=0
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.5
ninja check
ninja check-frontends-pytorch
```

The issue with naively attempting it was as noted here: https://github.com/google/sanitizers/issues/796#issuecomment-294282364

I suspect that when building with clang, there should be a `-shared-libsan` on appropriate link lines.

**Comment by clemente0420** [comment]
still the issue

**Comment by hattafaiq** [comment]
if i use libasan in qt software and install LLVM cannot show spessific of page, just show memory address
