### ISSUE TITLE
[RFC] Introducing a formal ownership process

### ISSUE THREAD

**Issue by silvasean** [llvm/torch-mlir#1506]
As the community has been scaling, we now have various relatively disjoint parts of the project. I have found that often the burden of reviewing certain PR's falls on me as the "default", but often there is someone better in the community. I propose that we adopt a system similar to LLVM's [CODE_OWNERS.TXT](https://github.com/llvm/llvm-project/blob/main/llvm/CODE_OWNERS.TXT) or Clang's [CodeOwners.rst](https://github.com/llvm/llvm-project/blob/main/clang/CodeOwners.rst). This is in-line with Torch-MLIR's general adherence to LLVM's community conventions. The file would contain a snippet like this:

```
This file is a list of the people responsible for ensuring that
patches for a particular part of Torch-MLIR are reviewed,
either by themself or by someone else. They are also the
gatekeepers for their part of Torch-MLIR, with the final word
on what goes in or not.
```

Here is a proposal for an initial list of owners:

`torch` dialect and other core IR pieces:
Also, general fallback for anything not covered by anyone else (Python bindings/API, JIT IR importer):
Sean Silva (@silvasean)

TorchToLinalg, Shape inference, Dtype refinement, MaximizeValueSemantics:
Ramiro Leal-Cavazos (@ramiro050)

CI / Build system / Packaging:
Anush Elangovan (@powderluv)

TorchToTOSA:
Eric Kunze (GH: @eric-k256)

TorchToMHLO:
Tianyo Kwok (@tanyokwok) or Ziheng Jiang (@ZihengJiang) -- please advise on who you folks think is best

LTC:
Antonio Kim (@antoniojkim)

Bazel build:
Sambhav Jain (@sjain-stanford) or somebody else at Cruise? -- please advise

------------------------------------------

What do folks think?

**Comment by tanyokwok** [comment]
@silvasean I'm happy to be the owner or a co-owner of the TorchToMhlo module. cc @ZihengJiang

**Comment by antoniojkim** [comment]
I'm happy to be the owner for the LTC module. Can you also add @ke1337 as an owner for this as well?

**Comment by eric-k256** [comment]
Yes, I'm happy to own the TorchToTOSA piece.

**Comment by tanyokwok** [comment]
> Co-owning should be better in the MHLO case.

I couldn't agree more with @ZihengJiang 's proposal!

**Comment by powderluv** [comment]
Likewise happy to be responsible for CI / Build system / Packaging.  Thanks to @sjain-stanford @ashay @dellis23 @makslevental and others for their contributions so far.

**Comment by silvasean** [comment]
Thanks folks, I pushed a PR to add this: https://github.com/llvm/torch-mlir/pull/1512 PTAL!
