### ISSUE TITLE
move tools/e2e_test.sh to a Python script

### ISSUE THREAD

**Issue by powderluv** [llvm/torch-mlir#1517]
Now that we have torch-mlir working /  building on Windows it would be good to get rid of bash-isms and use Python so the tests can be run on Windows / Powershell in the same way.

**Comment by silvasean** [comment]
It is already just a wrapper around a Python script: https://github.com/llvm/torch-mlir/blob/0701464c47983b0e72bccf45efc1c46f618a6171/tools/e2e_test.sh#L12
