### ISSUE TITLE
Issue modifying layer weights

### ISSUE THREAD

**Issue by nithinsubbiah** [llvm/torch-mlir#1532]
Hi folks, I've been trying to modify the weight tensor values inside a custom pass at the TOSA level and I've been hitting some issues. 

The following is the PyTorch model where I registered `modify_weights` as a custom PyTorch op.
```
class SimpleModel(nn.Module):
    def __init__(self, input_dim, output_size):
        super().__init__()
        self.matmul = nn.Linear(input_dim, output_size)
        self.relu = nn.ReLU()

    def forward(self, x):
        torch.ops.custom_op.modify_weights(self.matmul.weight)
        matmul_out = self.matmul(x)
        relu_out = self.relu(matmul_out)
        return relu_out
```

In the TOSA pass for `modify_weights` op, I tried to replace the value of the input (constant) tensor with the new modified value. But the pass (TorchToTOSA) doesn't even get executed because the op seems to be folded away. I confirmed by printing out the Torch IR and checking that the op wasn't present. Is there a way to not let the pass get folded?

Alternatively, I tried assigning the return value of the op to the layer weight at the PyTorch level:
`self.matmul.weight = torch.ops.custom_op.modify_weights(self.matmul.weight)`

This change throws the following error:
```
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: unsupported by backend contract: module initializers
note: see current operation: "torch.initialize.global_slots"(%2) {slotSymNames = [@matmul.weight]} : (!torch.tensor<[2,2],f32>) -> ()
note: this is likely due to InlineGlobalSlots being unable to inline a global slot
```
Any pointers on solving the above would be appreciated, thanks!

**Comment by nithinsubbiah** [comment]
cc: @ramiro050

**Comment by ramiro050** [comment]
> But the pass (TorchToTOSA) doesn't even get executed because the op seems to be folded away.

It's possible that the op is being folded away by PyTorch rather than torch-mlir. Can you try doing

```python
print(torch.jit.script(SimpleModel(...)).graph)
```

to see what is being given to torch-mlir?

Also, can you paste the MLIR reproducer file generated during the second error as well as the command to reproduce the issue? It's hard to know what is happening without the full IR.

**Comment by nithinsubbiah** [comment]
> print(torch.jit.script(SimpleModel(...)).graph)
gives 
```
graph(%self : __torch__.SimpleModel,
      %x.1 : Tensor):
  %matmul : __torch__.torch.nn.modules.linear.Linear = prim::GetAttr[name="matmul"](%self)
  %matmul_out.1 : Tensor = prim::CallMethod[name="forward"](%matmul, %x.1) # /home/nithin/git_repos/nithin-torch-mlir/torch-mlir/scripts_d_matrix/sparsity.py:22:21
  %relu : __torch__.torch.nn.modules.activation.ReLU = prim::GetAttr[name="relu"](%self)
  %relu_out.1 : Tensor = prim::CallMethod[name="forward"](%relu, %matmul_out.1) # /home/nithin/git_repos/nithin-torch-mlir/torch-mlir/scripts_d_matrix/sparsity.py:23:19
  return (%relu_out.1)
```
Looks like the op is folded away by PyTorch.

For the second method:
When I try to dump the Torch IR I get a legalization error for `torch.aten.linear`:
``` 
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: failed to legalize operation 'torch.aten.linear' that was explicitly marked illegal
note: see current operation: %8 = "torch.aten.linear"(%arg0, %7, %0) : (!torch.vtensor<[2,2],f32>, !torch.vtensor, !torch.vtensor<[4],f32>) -> !torch.vtensor
```

**Comment by ramiro050** [comment]
> For the second method:
> When I try to dump the Torch IR I get a legalization error for torch.aten.linear:

When `torch_mlir.compile` fails, it should create a file in the `/tmp` directory with the MLIR to reproduce the error. You shouldn't need to dump anything. The error message should look like:

```
For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='torchscript-module-to-torch-backend-pipeline{backend-legal-ops=}' /tmp/MyModule.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
```

In my case, the `/tmp` file is `/tmp/MyModule.mlir`

**Comment by nithinsubbiah** [comment]
I've pasted it here in the gist - https://gist.github.com/nithinsubbiah/bfd466227f5e402448556edefddac911
I've also pinged you on discord with more details.

**Comment by nithinsubbiah** [comment]
The following solution worked for me - define the `modify_weights` op as a separate model and call it from the main model.
```
class ModWeights(nn.Module):
    def __init__(self):
        super().__init__()
        self.modify_weights = torch.ops.custom_op.modify_weights()
    
    def forward(self, x):
        return self.modify_weights(x)

class SimpleModel(nn.Module):
    def __init__(self, input_dim, output_size):
        super().__init__()
        self.w1 = Modweights()
        self.matmul = nn.Linear(input_dim, output_size)
        self.relu = nn.ReLU()

    def forward(self, x):
        self.w1(self.matmul.weight)
        matmul_out = self.matmul(x)
        relu_out = self.relu(matmul_out)
        return relu_out
 ```
 
 Thanks Ramiro for your help!
