### ISSUE TITLE
[RFC] Add lowering for `aten.randint.low` and `aten.randn` op

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1560]
Hi, I'm working on adding the lowering for [aten.randint.low](https://pytorch.org/docs/stable/generated/torch.randint.html) and [aten.randn](https://pytorch.org/docs/stable/generated/torch.randn.html) op. 
1.) The issue with the `aten.randint.low` is that it returns a tensor of random integers generated uniformly, but the current implementation of `AtenUniformOp` generates only floating-point type numbers.
2.) The `aten.randn` op, returns a tensor filled with random numbers from a normal distribution. But we don't currently support random number generation based on the normal distribution in Torch-MLIR.

I would like to know your views on how we can support this kind of ops.

@silvasean @ramiro050 @pashu123

**Comment by ramiro050** [comment]
1. I think for `aten.randint.low`, you can reuse most of the code for `aten.uniform`. The random numbers are actually generated as integers and then they are scaled to a float range. For `aten.randint.low` all that will change is the scaling performed:

https://github.com/llvm/torch-mlir/blob/2793a2bd417a58e1d5e060406aa094db055b659c/lib/Conversion/TorchToLinalg/Random.cpp#L143-L144

2. A common algorithm for generating random numbers in a normal distribution using a uniform distribution is the Box-Muller algorithm, so that could be used to implement `aten.randn`

**Comment by vivekkhandelwal1** [comment]
Hi @ramiro050, I have got the `aten.randint.low` working, thanks for the help. But I have a doubt regarding whether the lowering generated for `AtenUniformOp` can be run on `IREE` or not. Because the lowering also has this `TorchConversion::GetNextSeedOp`. https://github.com/llvm/torch-mlir/blob/2793a2bd417a58e1d5e060406aa094db055b659c/lib/Conversion/TorchToLinalg/Random.cpp#L108
Any thoughts on this?

**Comment by ramiro050** [comment]
Yeah, at the moment `GetNextSeedOp` only works with the refbackend. We need to do a similar lowering into `ml_program.global` in order to make it work with IREE.

cc: @silvasean

**Comment by vivekkhandelwal1** [comment]
> Yeah, at the moment `GetNextSeedOp` only works with the refbackend. We need to do a similar lowering into `ml_program.global` in order to make it work with IREE.
> 
> cc: @silvasean

Any thoughts on this? @silvasean

**Comment by vivekkhandelwal1** [comment]
Hi @ramiro050 @silvasean, I'm blocked on this `GetNextSeedOp`, the lowering for which doesn't exist in IREE. Any help on this would be highly appreciated.

**Comment by silvasean** [comment]
You can implement this with ml_program.global like Ramiro said. You just need to translate the code here to use ml_program.global instead of memref.global: https://github.com/llvm/torch-mlir/blob/a1d3afdba9f3baaa502654c2ab52fb86f358e6ec/lib/RefBackend/RefBackend.cpp#L268

**Comment by silvasean** [comment]
Yes, we would delete that code from RefBackend. One nit is that RefBackend doesn't handle ml_program.global, but it should be very easy to add some code that lowers a limited subset of ml_program.global (such as just i64 globals) to memref.global.

RefBackend should accept the same input contract as IREE and other similar backends.

So the code change would be:
move InsertRngGlobals to lib/Conversion/TorchConversionToMLProgram
Change RefBackend.cpp to delete createInsertRngGlobalsPass but add a pass LowerMLProgramGlobalToMemRefGlobal

**Comment by vivekkhandelwal1** [comment]
> Yes, we would delete that code from RefBackend. One nit is that RefBackend doesn't handle ml_program.global, but it should be very easy to add some code that lowers a limited subset of ml_program.global (such as just i64 globals) to memref.global.
> 
> RefBackend should accept the same input contract as IREE and other similar backends.
> 
> So the code change would be: move InsertRngGlobals to lib/Conversion/TorchConversionToMLProgram Change RefBackend.cpp to delete createInsertRngGlobalsPass but add a pass LowerMLProgramGlobalToMemRefGlobal

Okay, thanks. I will work on this from tomorrow.

**Comment by vivekkhandelwal1** [comment]
> So the code change would be: move InsertRngGlobals to lib/Conversion/TorchConversionToMLProgram Change RefBackend.cpp to delete createInsertRngGlobalsPass but add a pass LowerMLProgramGlobalToMemRefGlobal

Hi @silvasean, I'm working on this, I have added the `TorchConversionToMLProgramPass`. But while adding the `LowerMLProgramGlobalToMemRefGlobalPass`, I'm facing some issues. My question is before the conversion of `ml_program` ops to `memref` ops, bufferization has to be done for the `ml_program` ops. Does there exists any pass which does this and we need to add that in the `refbackend,py` or this pass has to be added?

**Comment by vivekkhandelwal1** [comment]
Also, where should be this pass `LowerMLProgramGlobalToMemRefGlobalPass` placed in the pipeline?

**Comment by silvasean** [comment]
I think you can have the LowerMLProgramGlobalToMemRefGlobalPass just be called mlprogram-bufferize and be part of the regular bufferization pipeline (for tensor-valued ml_program.global's).
