### ISSUE TITLE
AttributeError: 'torch._C.ScriptMethod' object has no attribute '__func__'

### ISSUE THREAD

**Issue by Abhishek-Varma** [llvm/torch-mlir#1582]
Prior to : [ExampleArgs](https://github.com/llvm/torch-mlir/commit/64914603fa9376468f0f303029b5b3a067c27b83) I was able to compile a model by sending the torchscript graph to the compile API :- 

```
fx_g = make_fx(model, ...)
ts_g = torch.jit.script(fx_g)
module = torch_mlir.compile(ts_g, inputs, torch_mlir.OutputType.LINALG_ON_TENSORS ...)
```

But it gives the following error now :- 
```
File "python_packages/torch_mlir/torch_mlir/__init__.py", line 313, in compile
    torch.jit.export(getattr(model, method_name).__func__)
AttributeError: 'torch._C.ScriptMethod' object has no attribute '__func__'
```

If I don't pass the torchscript graph and directly pass `fx_g` (as shown above) the error doesn't occur, i.e the following code runs  correctly :- 
```
fx_g = make_fx(model, ...)
module = torch_mlir.compile(fx_g, inputs, torch_mlir.OutputType.LINALG_ON_TENSORS ...)
```

Can someone tell me the reason behind this and if the above "workaround" is indeed a correct fix for this issue?

@silvasean @ramiro050

**Comment by silvasean** [comment]
This is unintended behavior. I will submit a fix when I'm back at my desk.
