### ISSUE TITLE
RuntimeError: method '__torch__.torch.fx.graph_module._lambda.forward' already defined.

### ISSUE THREAD

**Issue by JakopinA** [llvm/torch-mlir#1583]
Getting this error when trying to run the following script: https://gist.github.com/AmosLewis/df6feb5c9618bd4b5a843c3ce490a2f9

This script was working on [November 9th torch_mlir](https://github.com/AmosLewis/torch-mlir/tree/unsqueezeop). Here is the [comand line print](https://gist.github.com/AmosLewis/1c654721fcf9a974484bef178e8d449d) from that time.

The error comes from `module = torch_mlir.compile(` on line 89.

**Comment by silvasean** [comment]
Can you check if https://github.com/llvm/torch-mlir/pull/1588 fixes this?

**Comment by JakopinA** [comment]
__

> Can you check if #1588 fixes this?

Tried this, I'm getting a new error: 

```
Exception: 
PyTorch TorchScript module -> torch-mlir Object Graph IR import failed with:
### Importer C++ Exception:
required keyword attribute 'values' is undefined
### Importer Diagnostics:
```

**Comment by silvasean** [comment]
That looks like a regular PyTorch version error. Can you make sure you are running a consistent set of Torch-MLIR and PyTorch versions?

**Comment by JakopinA** [comment]
> That looks like a regular PyTorch version error. Can you make sure you are running a consistent set of Torch-MLIR and PyTorch versions?

Yep, I believe that was the issue. The PR fixes the error, thank you!
