### ISSUE TITLE
fatal error: 'ATen/native/quantized/cpu/packed_params.h' file not found

### ISSUE THREAD

**Issue by xinqiaozhang** [llvm/torch-mlir#1598]
Hi there,

I met an error when installing torch-mlir,  using:

cmake --build build --target tools/torch-mlir/all 

Can anyone help me with it?

System: Ubuntu 22.04, installed libtorch-dev

**Comment by silvasean** [comment]
You are probably using an older PyTorch version. You can see instructions here: https://github.com/llvm/torch-mlir/blob/main/docs/development.md#setup-your-python-virtualenvironment-and-dependencies

**Comment by xinqiaozhang** [comment]
Thanks for your reply. I was following the link you mentioned to install. Python==3.8.0 and PyTorch= 1.14.0.dev20221114+cpu

**Comment by silvasean** [comment]
Is it possible that you didn't activate your venv before configuring?

**Comment by xinqiaozhang** [comment]
No, I was in the anaconda environment On Nov 16, 2022, at 10:49 AM, Sean Silva ***@***.***> wrote:﻿
Is it possible that you didn't activate your venv before configuring?

**Comment by xinqiaozhang** [comment]
Hi,

I did not use python venv and I use anaconda venv istead. Would it be the reason?

**Comment by xinqiaozhang** [comment]
I found the reason why,

In my computer, it installed libtorch3-dev instead of libtorch-dev. And cpu/packed_params.h file only exists in libtorch-dev.

It is so strange. I have to reinstall libtorch-dev.

Then I was able to build. But got an error when testing:

`cmake --build build --target check-torch-mlir
[2/3] Running the torch-mlir regression tests
FAIL: TORCH_MLIR :: python/importer/jit_ir/ivalue_import/quantization.py (26 of 82)
******************** TEST 'TORCH_MLIR :: python/importer/jit_ir/ivalue_import/quantization.py' FAILED ********************
Script:
--
: 'RUN: at line 10';   /home/xinqiao/anaconda3/envs/mlir-venv/bin/python3.10 ...../torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py | ...../torch-mlir/build/bin/torch-mlir-opt | FileCheck ...../torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py
--
Exit Code: 1

Command Output (stderr):
--
...../torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py:22:11: error: CHECK: expected string not found in input
 # CHECK: %[[SCALE:.*]] = torch.constant.float
          ^
<stdin>:1:1: note: scanning from here
module {
^

Input file: <stdin>
Check file: ...../torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py

-dump-input=help explains the following input dump.

Input was:
<<<<<<
          1: module { 
check:22     X~~~~~~~~ error: no match found
          2: } 
check:22     ~~
          3:  
check:22     ~
>>>>>>

--

********************
FAIL: TORCH_MLIR :: python/importer/jit_ir/get_registered_ops.py (43 of 82)
******************** TEST 'TORCH_MLIR :: python/importer/jit_ir/get_registered_ops.py' FAILED ********************
Script:
--
: 'RUN: at line 9';   (/home/xinqiao/anaconda3/envs/mlir-venv/bin/python3.10 ...../torch-mlir/test/python/importer/jit_ir/get_registered_ops.py || true) | FileCheck ...../torch-mlir/test/python/importer/jit_ir/get_registered_ops.py
--
Exit Code: 2

Command Output (stderr):
--
Traceback (most recent call last):
  File "...../torch-mlir/test/python/importer/jit_ir/get_registered_ops.py", line 11, in <module>
    from torch_mlir._mlir_libs._jit_ir_importer import get_registered_ops
ImportError: /home/xinqiao/anaconda3/envs/mlir-venv/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ...../torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/_mlir_libs/libTorchMLIRAggregateCAPI.so)
FileCheck error: '<stdin>' is empty.
FileCheck command line:  FileCheck ...../torch-mlir/test/python/importer/jit_ir/get_registered_ops.py

--

********************
********************
Failed Tests (2):
  TORCH_MLIR :: python/importer/jit_ir/get_registered_ops.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/quantization.py


Testing Time: 12.15s
  Passed: 80
  Failed:  2
FAILED: tools/torch-mlir/test/CMakeFiles/check-torch-mlir ...../torch-mlir/build/tools/torch-mlir/test/CMakeFiles/check-torch-mlir 
cd ...../torch-mlir/build/tools/torch-mlir/test && /home/xinqiao/anaconda3/envs/mlir-venv/bin/python3.10 ...../torch-mlir/build/./bin/llvm-lit -sv ...../torch-mlir/build/tools/torch-mlir/test
ninja: build stopped: subcommand failed.
`

Does anyone has any idea?

**Comment by xinqiaozhang** [comment]
The issue has been solved, the reason is that the pytorch 1.14 update packed_params.h file to EmbeddingPackedParams.h

**Comment by silvasean** [comment]
Great! Will close the issue now.
