### ISSUE TITLE
MHLO E2E tests should run as part of CI

### ISSUE THREAD

**Issue by silvasean** [llvm/torch-mlir#1614]
We need to add a `--config=mhlo` line here: https://github.com/llvm/torch-mlir/blob/1d949f3ac27e89232ec376fe2d3b2ea6b5c33674/build_tools/python_deploy/build_linux_packages.sh#L262

When I run the MHLO e2e tests locally, it does not finish successfully. We have XFAIL's, but the compiler crashes (which cannot be caught by our xfail system) and needs to be fixed before enabling in the CI. E.g.:
```
./tools/e2e_test.sh -c mhlo -s -v -f AddSizeIntNegDimModule_basic
```

**Comment by tanyokwok** [comment]
The test crashed because we didn't handle a negative input dimension in the AtenSizeIntOp conversion correctly. I will fix it in the PR https://github.com/llvm/torch-mlir/pull/1620
