### ISSUE TITLE
Vision Model tests failing in eager_mode with the latest PyTorch release

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1618]
Hi, the three vision model tests namely, `MobilenetV3Module_basic, ResNet18Module_basic, ResNet18StaticModule_basic` are failing in eager_mode execution with the latest PyTorch release https://github.com/llvm/torch-mlir/actions/runs/3508295814/jobs/5876600953. As of now, I'm adding them to the xfail set (https://github.com/llvm/torch-mlir/pull/1617) so that the Roll PyTorch action runs successfully.

**Comment by makslevental** [comment]
What is the failure mode? How do I repro?
