### ISSUE TITLE
Handle `aten.view` op cases with `-1` as the shape value

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1635]
After, the replacement of `kDynamicSize` from `-1` -> `std::numeric_limit<int64_t>::min()`, in LLVM, some of the view op tests are not working. Specifically the ones with the value `-1` as an element of the output shape list. These cases need to be handled because if the `-1` is replaced with the `std::numeric_limit<int64_t>::min()` in the tests it throws a PyTorch error. And if we keep it as `-1`, then it crashes here: https://github.com/llvm/llvm-project/blob/main/mlir/lib/IR/BuiltinTypes.cpp#L315.

**Comment by vivekkhandelwal1** [comment]
@JakopinA

**Comment by silvasean** [comment]
Hey Vivek, is this something you could dig into? I don't think any of these changes to -1 require that much specific knowledge of the code in question. It should be mostly a matter of looking for uses of kDynamicSize or places where we copy "our sizes" into "mlir sizes" and inserting a conversion.

**Comment by vivekkhandelwal1** [comment]
> Hey Vivek, is this something you could dig into? I don't think any of these changes to -1 require that much specific knowledge of the code in question. It should be mostly a matter of looking for uses of kDynamicSize or places where we copy "our sizes" into "mlir sizes" and inserting a conversion.

I might be able to take a look at this probably by the end of this week or early next week. I don't have cycles to look into this immediately. Past and this week have already been utilized mostly in dealing with the bugs and llvm bump.

**Comment by silvasean** [comment]
This is part of the LLVM bump though, right?
