### ISSUE TITLE
add_library cannot create imported target "MKL::MKL" because another target   with the same name already exists.

### ISSUE THREAD

**Issue by zhping5678** [llvm/torch-mlir#1660]
When I execute " cmake -GNinja -Bbuild -DCMAKE_BUILD_TYPE=Release -DPython3_FIND_VIRTUALENV=ONLY -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_EXTERNAL_PROJECTS="torch-mlir;torch-mlir-dialects" -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR="$PWD" -DLLVM_EXTERNAL_TORCH_MLIR_DIALECTS_SOURCE_DIR="$PWD"/externals/llvm-external-projects/torch-mlir-dialects -DMLIR_ENABLE_BINDINGS_PYTHON=ON -DLLVM_TARGETS_TO_BUILD=host -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ externals/llvm-project/llvm", it reports this error.

CMake Error at /usr/local/lib/cmake/mkl-2021.4.0/MKLConfig.cmake:716 (add_library):
  add_library cannot create imported target "MKL::MKL" because another target with the same name already exists.
Call Stack (most recent call first):
  ~/anaconda3/envs/iree/lib/python3.9/site-packages/torch/share/cmake/Caffe2/public/mkl.cmake:1 (find_package)
  ~/anaconda3/envs/iree/lib/python3.9/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:113 (include)
  ~/anaconda3/envs/iree/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  ~/code/torch-mlir/python/torch_mlir/dialects/torch/importer/jit_ir/CMakeLists.txt:15 (find_package)

**Comment by powderluv** [comment]
This is an issue with upstream Torch's CMake trying to include MKL.  You can hand edit the installed TorchConfig.Cmake (will look like https://github.com/pytorch/pytorch/blob/b7c42b4066e3a77b2e15517bee57de5d71ee0f8a/cmake/TorchConfig.cmake.in#L119) and in your path it is in `~/anaconda3/envs/iree/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68`   or you can remove MKL for now.

**Comment by zhping5678** [comment]
Thanks！I comment lines about MKL in Caffe2Config.cmake, and then it successed.
