### ISSUE TITLE
Bazel build fails on mlir-hlo

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1666]
Hi, the bazel build is failing with the following issue: https://github.com/llvm/torch-mlir/actions/runs/3590673913/jobs/6044313718

**Comment by burmako** [comment]
Hi folks! Sorry for that - this was an oversight on the MLIR-HLO side on 11/17 fixed on 11/22, which resulted in a range of commits from https://github.com/tensorflow/mlir-hlo/commit/f56007837b21cb716f148e8f9cb079386ca4d6a9 to https://github.com/tensorflow/mlir-hlo/commit/1329205f873d97af2a1c51a8cc8b147af39dbd22 that have broken Bazel builds.

**Comment by vivekkhandelwal1** [comment]
Thanks for the info @burmako!

**Comment by sjain-stanford** [comment]
Thanks @vivekkhandelwal1 for the ping and @burmako for the heads-up! If I understand correct, this issue will self-fix itself in a week when we do our next check-out of MLIR-HLO. Is that right? If so, then we can leave it at that.

**Comment by burmako** [comment]
"If I understand correct, this issue will self-fix itself in a week when we do our next check-out of MLIR-HLO. Is that right?". Yes, I expect that will be the case.

**Comment by vivekkhandelwal1** [comment]
> Thanks @vivekkhandelwal1 for the ping and @burmako for the heads-up! If I understand correct, this issue will self-fix itself in a week when we do our next check-out of MLIR-HLO. Is that right? If so, then we can leave it at that.

Hi @sjain-stanford, this issue is fixed with this llvm bump: https://github.com/llvm/torch-mlir/commit/3fc27cf6cab4e25db15071a45812aefbaec97de3, but there exists another failure. https://github.com/llvm/torch-mlir/actions/runs/3613694203/jobs/6089617005
