### ISSUE TITLE
MHLO pipeline

### ISSUE THREAD

**Issue by FullZing** [llvm/torch-mlir#1701]
in the figure in https://github.com/llvm/torch-mlir,  
TorchScript -> TorchDialect -> MHLO dialect
in the case of MHLO dialect,   what's next step ?
-  Reference MLIR CPU runner
-  CPU Backends
-  GPU Backends

is there guide for how to run E2E MHLO pipeline ?

**Comment by silvasean** [comment]
Torch-MLIR does not provide this functionality (except the [RefBackend](https://github.com/llvm/torch-mlir/blob/main/docs/architecture.md#the-refbackend-reference-backend) which is horrible and only useful for testing).

There are other projects in the community that can run it though, for example https://github.com/alibaba/BladeDISC or https://github.com/iree-org/iree are MLIR-based backends that can run MHLO.

**Comment by FullZing** [comment]
> Torch-MLIR does not provide end-to-end execution functionality (except the [RefBackend](https://github.com/llvm/torch-mlir/blob/main/docs/architecture.md#the-refbackend-reference-backend) which is horrible and only useful for testing).
> 
> There are other projects in the community that can run it though, for example https://github.com/alibaba/BladeDISC or https://github.com/iree-org/iree are MLIR-based backends that can run MHLO.

thanks for answering.
i have one more question if you can help futher,
there is shape library in torch mlir,  but how pytorch-mlir handle dynamic shape if don't care about backend?

**Comment by tanyokwok** [comment]
> how pytorch-mlir handle dynamic shape

The input PyTorch program should guarantee that it can handle dynamic shapes. Then Torch-MLIR will choose to lower the computations carefully, which will preserve the dynamic shape capabilities. And yes, the backend code generations do matter.

**Comment by xgupta** [comment]
Just browsing the open issues, shall we close the issue if answer is satisfactory.
