### ISSUE TITLE
[RFC] Changes to grouped convolution needed for convolution_backward

### ISSUE THREAD

**Issue by gpetters94** [llvm/torch-mlir#1754]
@vivekkhandelwal1 and I are working on implementing `aten::convolution_backward` and I think it's going to require support for grouped convolutions with dynamic group size. Based on [this](https://github.com/pytorch/pytorch/blob/3a511e83549d86ce9a2a8de2b64be340d2a23e4e/torch/nn/utils/_expanded_weights/conv_utils.py#L168) the second return value is calculated by using the batch size as the group size. That should work with the current implementation when the batch size is statically known, but I think that won't be true of a lot of models. How much backend work will supporting non-constant groups be and do we think it's within the scope of the project?

**Comment by silvasean** [comment]
You should be able to use the linalg grouped convolution named op with a dynamic group size just fine. We will need to emit an assertion that the dynamic group size divides the number of channels dynamically though before reshaping.
