### ISSUE TITLE
[RFC] Add lowering for aten::new_empty_strided op

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1755]
Hi, I'm working on adding the lowering for `aten::new_empty_strided` op. I have a doubt regarding this. How can we create strided tensors in Torch-MLIR? Because the `tensor.empty` op doesn't take into account strides. But on the other hand, I can see strided memrefs in the mlir. So, what's the best way to support this op or create strided tensors?

**Comment by vivekkhandelwal1** [comment]
@silvasean @ramiro050 Any suggestions on this?

**Comment by ramiro050** [comment]
Hi @vivekkhandelwal1, can you also paste the example we were talking about where an error appears if you pass the output of `new_empty_strided` to a `copy` op?

**Comment by vivekkhandelwal1** [comment]
> Hi @vivekkhandelwal1, can you also paste the example we were talking about where an error appears if you pass the output of `new_empty_strided` to a `copy` op?

I don't have a Torch-MLIR example right now, but here's the torch example:
``` 
a = torch.randn((3, 4))
b = torch.ops.aten.new_empty_strided(a, size=[3, 4], stride=[1, 2])
b.copy_(a)
``` 

The resultant tensor you will get from here would not be the same as the one you will get if `b` was created using `new_empty` instead of `new_empty_strided` op.

**Comment by vivekkhandelwal1** [comment]
Hi @ramiro050, I see that the strides are represented differently in MLIR as compared to PyTorch. For ex: the tensor with shape `[2, 3, 4]` would have default strides `[12, 4, 1]` in PyTorch while MLIR treats them to be `[1, 1, 1]`. Also, the above example shared by me gets canonicalized in Torch-MLIR, and it would return `tensor a` assuming that the copying of `a` to `b` (a strided tensor) is equivalent to `a` itself.

**Comment by vivekkhandelwal1** [comment]
Here's the link to my WIP patch (https://github.com/vivekkhandelwal1/torch-mlir/commit/ca2f63d87a61bae61233fb54ff540dccc269b699), which contains an e2e test for this op. If you run this you will see that the `copy` op gets canonicalized.

**Comment by vivekkhandelwal1** [comment]
> @silvasean @ramiro050 Any suggestions on this?

Hi, @silvasean @ramiro050 did you get a chance to look at this issue?

**Comment by ramiro050** [comment]
> I don't have a Torch-MLIR example right now, but here's the torch example:
> 
> ```
> a = torch.randn((3, 4))
> b = torch.ops.aten.new_empty_strided(a, size=[3, 4], stride=[1, 2])
> b.copy_(a)
> ```
> 
> The resultant tensor you will get from here would not be the same as the one you will get if `b` was created using `new_empty` instead of `new_empty_strided` op.

Is the example above based on IR from a model? It doesn't seem to be a use of `new_empty_strided` that is meant to be supported. In particular, the specified stride leads to a tensor that is overlapped (different indices map to the same element in memory), which has undefined behavior. See warning here: https://pytorch.org/docs/stable/generated/torch.empty_strided.html

**Comment by vivekkhandelwal1** [comment]
> 

Yes, this sequence is generated in the IR. The aten.new_empty_strided op creates a new tensor on which copy op is performed. If we can't handle this in torch-mlir then we definitely need to fold it at the PyTorch level.

**Comment by ramiro050** [comment]
> Yes, this sequence is generated in the IR. The aten.new_empty_strided op creates a new tensor on which copy op is performed. If we can't handle this in torch-mlir then we definitely need to fold it at the PyTorch level.

With the same size and stride values? I would check the model definition to see where it is being created, since the example you gave has undefined behavior. It might be a bug. The issue is that since several different indices in `b` map to the same element in memory, the actual values in `b` *depend* on the order that `b` is traversed when copying into it the values of `a`. And in PyTorch and torch-mlir, the order in which tensor operations traverse tensors is not information available to users.

Since the example results in undefined behavior in PyTorch, there is no way to support it in torch-mlir.

**Comment by ramiro050** [comment]
> Yes, this sequence is generated in the IR. The aten.new_empty_strided op creates a new tensor on which copy op is performed. If we can't handle this in torch-mlir then we definitely need to fold it at the PyTorch level.

With the same size and stride values? I would check the model definition to see where it is being created, since the example you gave has undefined behavior. It might be a bug. The issue is that since several different indices in `b` map to the same element in memory, the actual values in `b` *depend* on the order that `b` is traversed when copying into it the values of `a`. And in PyTorch and torch-mlir, the order in which tensor operations traverse tensors is not information available to users.

Since the example results in undefined behavior in PyTorch, there is no way to support it in torch-mlir.

**Comment by vivekkhandelwal1** [comment]
> > Yes, this sequence is generated in the IR. The aten.new_empty_strided op creates a new tensor on which copy op is performed. If we can't handle this in torch-mlir then we definitely need to fold it at the PyTorch level.
> 
> With the same size and stride values? I would check the model definition to see where it is being created, since the example you gave has undefined behavior. It might be a bug. The issue is that since several different indices in `b` map to the same element in memory, the actual values in `b` _depend_ on the order that `b` is traversed when copying into it the values of `a`. And in PyTorch and torch-mlir, the order in which tensor operations traverse tensors is not information available to users.
> 
> Since the example results in undefined behavior in PyTorch, there is no way to support it in torch-mlir.

No. All the occurrences have default stride values. That's why I created this PR https://github.com/llvm/torch-mlir/pull/1776, to canonicalize the op when it has default strides. Right now, this should unblock us.

**Comment by vivekkhandelwal1** [comment]
This commit https://github.com/llvm/torch-mlir/commit/abf4f207cd502a72a1c9c9567f9b128ddce3836d, fixes the given issue.
