### ISSUE TITLE
[Feat] Is there a release for Python 3.8?

### ISSUE THREAD

**Issue by llCurious** [llvm/torch-mlir#1759]
Hey, guys.
I am trying to install torch-mlir from either Pypi or the scripts in this repo.
- pip install torch-mlir
- pip install --pre torch-mlir torchvision -f https://llvm.github.io/torch-mlir/package-index/ --extra-index-url https://download.pytorch.org/whl/nightly/cpu

However both approaches failed.

Environment:
- Centos
- Python 3.8

I check the release and i found that there is always a release for Python 3.7/3.9/3.10 and 3.8 is missing. How could i find the latest release for Python 3.8?

**Comment by ramiro050** [comment]
@powderluv, torch-mlir support Python 3.8, right?

**Comment by powderluv** [comment]
Yes we can build on anything after 3.6. However nightly builds are limited to 3.10 due to upstream torchvision whl availability. Please let us know if you can't build on 3.8

**Comment by ScottTodd** [comment]
Colab recently updated from Python 3.7 to 3.8, so providing regular 3.8 builds would be helpful: https://medium.com/google-colab/colab-updated-to-python-3-8-4922f9970a72

**Comment by powderluv** [comment]
yeah we dropped it since upstream hadn't added torchvision whl packages for 3.8.  @ashay fyi.

**Comment by ashay** [comment]
They seem to have added the 3.7-3.10 whl packages back for torchvision.  [Here](https://github.com/llvm/torch-mlir/pull/1827) is the patch to re-enable torch-mlir builds using Python 3.8.

**Comment by ashay** [comment]
Closing this issue because the WHL for torch-mlir with Python 3.8 on Linux is now available on https://llvm.github.io/torch-mlir/package-index.  Please re-open if there are problems using it.  Thanks!

**Comment by llCurious** [comment]
Sry for the delayed reply. Thanks to you guys! I will have a try according to your comments @ashay

**Comment by ashay** [comment]
No worries!  Thanks for reporting the problem.
