### ISSUE TITLE
Push for finishing transition to Python dtype functions

### ISSUE THREAD

**Issue by ramiro050** [llvm/torch-mlir#1807]
Hi everyone,

I would like to get some help from the community to finish up the transition from using [`RefineTypes.cpp`](https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/Torch/Transforms/RefineTypes.cpp) for encoding how to calculate the resulting dtypes of the tensors of all the ops to using dtype functions that are written in Python. For more information about the rationale behind this transition see the [Custom Op RFC](https://github.com/llvm/torch-mlir/issues/1462).

The transition will take place on the branch [`dtype-functions-staging`](https://github.com/llvm/torch-mlir/tree/dtype-functions-staging), so that it happens in a single go in `main`, otherwise many large workloads can fail to lower through Torch-MLIR. The reason things can fail is that if you have some ops being handled by `RefineTypes` and other ops using the Python dtype functions that get applied in the [`TorchDtypeRefinementPipeline`](https://github.com/llvm/torch-mlir/blob/4f94831fed2aa016f8d3f03b63f8841a064c4152/lib/Dialect/Torch/Transforms/Passes.cpp#L175), then the `RefineTypes` pass and the `TorchDtypeRefinementPipeline` will cycle over and over, each pass propagating dtype information until encountering an op that is not handled by the current pass. For workloads with many ops, the cycling of passes can easily reach the [iteration limit](https://github.com/llvm/torch-mlir/blob/4f94831fed2aa016f8d3f03b63f8841a064c4152/include/torch-mlir/Dialect/Torch/Transforms/Passes.td#L294) in the `LowerToBackendContract` pass, resulting in a failure when lowering through Torch-MLIR. Currently, there are only a few ops using dtype functions in `main`, and it is already [affecting some user workloads](https://github.com/llvm/torch-mlir/pull/1750#issuecomment-1375370220).

To avoid breaking workloads for users, or forcing users to increase the iteration limit affecting performance of Torch-MLIR, we will instead do the entire transition on the branch [`dtype-functions-staging`](https://github.com/llvm/torch-mlir/tree/dtype-functions-staging), where we can `XFAIL` complex tests temporarily as needed.

### The contribution process

1. Choose an item from the work list below and edit this issue by adding your name alongside the checklist item you're working on to avoid duplicate work
   - If you don't have edit access, just mention it as a comment, and I will update the issue
2. Make a new branch off of the [`dtype-functions-staging`](https://github.com/llvm/torch-mlir/tree/dtype-functions-staging) branch
3. Remove the op or ops linked in the checklist item from `RefineTypes.cpp`
4. Add dtypes functions with proper testing to the [abstract_interp_lib_gen.py](https://github.com/llvm/torch-mlir/blob/main/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py). See the [docs](https://github.com/llvm/torch-mlir/blob/main/docs/adding_abstract_interpretation_functions.md) for information on how two write a dtype function
5. Run `./build_tools/update_abstract_interp_lib.sh` to update abstract interp library
5. Your patch is **only** expected to pass the e2e tests that test a single op. If your patch causes tests that use many ops like `ResNet18` or `Mobilenet` to fail, mark those tests as `XFAIL`
6. Make a PR to merge your branch into `dtype-functions-staging` (see the [PR for ops that return `i1`s](https://github.com/llvm/torch-mlir/pull/1806) for reference)
7. Tag me (@ramiro050) for review
8. Once merged, mark the item in the work list as finished

### Work List

- [x] [dtype from first operand](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L646-L671) (@li-plus https://github.com/llvm/torch-mlir/pull/1895)
- [x] [dtype is always float32](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L676-L679) (@li-plus https://github.com/llvm/torch-mlir/pull/1813)
- [x] [dtype from second operand](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L693) (@li-plus https://github.com/llvm/torch-mlir/pull/1891#)
- [x] [dtype is always i1](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L703-L706) (@ramiro050 https://github.com/llvm/torch-mlir/pull/1806)
- [x] [dtype is always si64](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L715) (@ramiro050 https://github.com/llvm/torch-mlir/pull/1962)
- [x] [promote two dtypes assuming non-zero rank](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L725-L728) (@ramiro050 https://github.com/llvm/torch-mlir/pull/1831 https://github.com/llvm/torch-mlir/pull/1865)
- [x] [promote two dtypes assuming possibly zero rank](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L738-L741) (@ramiro050 https://github.com/llvm/torch-mlir/pull/1831)
- [x] [promote three dtypes](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L769) (@ramiro050 https://github.com/llvm/torch-mlir/pull/1962)
- [x] [promote LHS with scalar RHS](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L785-L787) (@ramiro050 https://github.com/llvm/torch-mlir/pull/1962)
- [x] [promote 2nd and 3rd operands](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L798-L840) (@ramiro050 https://github.com/llvm/torch-mlir/pull/1962)
- [x] [2 results take dtype from first operand](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L843) (@ramiro050 https://github.com/llvm/torch-mlir/pull/1967)
- [x] [3 results take dtype from first operand](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L857-L858) (@ramiro050 https://github.com/llvm/torch-mlir/pull/1967)
- [x] [Arange ops](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L890-L901) (@ramiro050 https://github.com/llvm/torch-mlir/pull/2057)
- [x] [Reduction ops](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L903-L986) and [another reduction op](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1133) (@ramiro050 https://github.com/llvm/torch-mlir/pull/2057)
- [x] [Scalar to tensor ops](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L988-L997) (@ramiro050 https://github.com/llvm/torch-mlir/pull/2057)
- [x] [Constant tensor allocation ops](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1004-L1045) (@ramiro050 https://github.com/llvm/torch-mlir/pull/2057)
- [x] [Type conversion ops](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1047-L1074) (@ramiro050 https://github.com/llvm/torch-mlir/pull/2057)
- [ ] [Embedding ops](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1090-L1101) (@gpetters94 https://github.com/llvm/torch-mlir/pull/1985)
- [ ] [Softmax ops](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1103-L1116) (@gpetters94 https://github.com/llvm/torch-mlir/pull/1987)
- [ ] [Binary scalar ops](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1123)(@gpetters94 https://github.com/llvm/torch-mlir/pull/1997)
- [x] [Rand ops](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1142-L1151) and [more rand ops](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1163-L1181) (@ramiro050 https://github.com/llvm/torch-mlir/pull/2089)
- [x] [VarMean ops](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1153-L1161) (@ramiro050 https://github.com/llvm/torch-mlir/pull/2089)
- [x] Miscellaneous ops: [AtenAtan2Op](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L753), [AtenLinearOp](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L779), [AtenMaxPool2dWithIndicesOp](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L876), [AtenTensorOp](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L999), [AtenCatOp](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1076), [Aten_ShapeAsTensorOp](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1081), [AtenScalarImplicitOp](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1128), [PrimNumToTensorScalarOp](https://github.com/llvm/torch-mlir/blob/8696752eb645eb42832c624ec7d2a56a48128918/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1118) (@ramiro050 https://github.com/llvm/torch-mlir/pull/2090)

Happy to help with any questions/issues!

**Comment by li-plus** [comment]
I'm willing to help. Could I take the the first 3 tasks?

**Comment by ramiro050** [comment]
> I'm willing to help. Could I take the the first 3 tasks?

Awesome! I've updated the work list

**Comment by powderluv** [comment]
@gpetters94 can you please help chip away at these ops too.

**Comment by gpetters94** [comment]
@ramiro050 I can take Embedding and Softmax for now.
