### ISSUE TITLE
Migration from MLIR-HLO to StableHLO

### ISSUE THREAD

**Issue by ashay** [llvm/torch-mlir#1835]
Currently, torch-mlir contains a lowering from the `torch` dialect to the `mhlo` dialect.  However, lowering to the StableHLO dialect seems beneficial for several reasons:

1. StableHLO supports versioning (thus forward and backward compatibility within major versions) and serialization.

2. StableHLO has a smaller codebase than MLIR-HLO, thus causing less churn in downstream projects like torch-mlir due to updates (e.g. reorganized directories, renamed targets).

3. Unlike the CI for the StableHLO repository, the CI for the MLIR-HLO repository does not use CMake (it uses Bazel), so the CMake build for MLIR-HLO breaks often.  I fix these breakages in the MHLO green commits, but it's recurring work to fix them and submit patches upstream:

 - https://github.com/tensorflow/tensorflow/pull/57484
 - https://github.com/tensorflow/tensorflow/pull/57504
 - https://github.com/tensorflow/tensorflow/pull/57655
 - https://github.com/tensorflow/tensorflow/pull/58880
 - https://github.com/tensorflow/tensorflow/pull/59019
 - https://github.com/tensorflow/tensorflow/pull/59187
 - https://github.com/tensorflow/tensorflow/pull/59219
 - https://github.com/tensorflow/tensorflow/pull/59495

So my questions for the TorchToMhlo maintainers are: (a) would there be any loss in functionality if we switched to using StableHLO and (b) would you (or someone familiar with that code) be willing to update the code to switch to StableHLO please?  Thanks!

**Comment by ashay** [comment]
cc: @tanyokwok, @ZihengJiang, @Vremold

**Comment by joker-eph** [comment]
> Unlike the CI for the StableHLO repository, the CI for the MLIR-HLO repository does not use CMake

Actually I'm pretty it does, before Bazel files were even added to this repo. I filed https://github.com/tensorflow/mlir-hlo/issues/58 to make it publicly visible.

> so the CMake build for MLIR-HLO breaks often.

This may be a coverage problem with the cmake configuration used by the CI, so in the same ticket as above I mentioned that open-sourcing the script used by the Kokoro CI (even if the runs aren't visible) may already help figuring out why you found issues that weren't uncovered by the CI?

**Comment by ashay** [comment]
My apologies, I wasn't aware of the CMake build for MHLO.  Thanks for creating the issue!  That should help me understand why my builds fail (or what else needs to be added to the existing build).

**Comment by ashay** [comment]
Here [https://github.com/llvm/torch-mlir/pull/1840] is an initial attempt at the migration.

**Comment by ashay** [comment]
Closing, since #1840 resolves this issue.
