### ISSUE TITLE
Custom Ops Sprint

### ISSUE THREAD

**Issue by silvasean** [llvm/torch-mlir#1963]
This issue is meant to track and help collaboration across the community to land the Custom Ops RFC in the next 2-3 weeks ideally: https://github.com/llvm/torch-mlir/issues/1462. This is a continuation of the discussion in https://github.com/llvm/torch-mlir/pull/1959

The main outstanding work items are the following:
1. [15 engineer-days] Porting the dtype functions (see https://github.com/llvm/torch-mlir/issues/1807). This is parallel to the other efforts.
2. [3 days] Implement splicing an MLIR file into the library: as in `torch-mlir-opt -pass-pipeline='torchscript-module-to-torch-backend-pipeline{extra-library=my_custom_ops.mlir}'` mentioned in the RFC. (unlike https://github.com/llvm/torch-mlir/pull/1959 we won't "namespace" torch.operator specially, since it comes from the same namespace source of truth -- the PyTorch op registry)
3. [2 days] Implement the ability to tag value-semantic ops in the library. This essentially augments the existing code in ReduceOpVariants so it would be good to put there. This would look something like `torch-mlir-opt -pass-pipeline='reduce-op-variants{extra-library=my_custom_ops.mlir}'`. The tentative design is a dummy function `__torch_mlir_has_value_semantics.foo.bar` which, if present in the library, indicates value semantics for the `foo.bar` op.
4. [5 days] implement `torch_mlir.compile` API.

The critical path here is 3+2+5 = 10 working days for the API design work (we could in theory parallelize this a bit more). We will need to port the dtype functions within that time in parallel (this work is parallelizable so we can have two people helping ideally).

The current open action items (this is a living list) are

- [ ] Figure out who is available to help with the dtype functions (1. above)
- [ ] 2. above
- [ ] 3. above
- [ ] 4. above

**Comment by ramiro050** [comment]
Thanks Sean for compiling the tasks. I'm happy to take on 2, 3, and 4. These tasks can be parallelized a little bit (3 can to some degree happen independently from 2, 4, but 2, 4 are quite dependent on one another), so if anyone is interested in taking 3 we can do that too.

For the sake of transparency and to help gauge expectations, my plan is to take these tasks as my highest priority items, meaning that I plan on spending most of my time getting them done. This should allow me to finish the tasks in accordance to the timeline outlined.

**Comment by powderluv** [comment]
This is awesome thanks @ramiro050 . I'll have @gpetters94  help on dtype conversion (task 1). If there is any part of that work that is required for other tasks please let us know.

LLaMA / Alpaca 4bit support here we come.

**Comment by makslevental** [comment]
I'll have a PR for 2 and 3 in ~15 minutes.

**Comment by powderluv** [comment]
Adding @gpetters94 to help with dtype transitions

**Comment by powderluv** [comment]
This is now complete. Please open new issues for anything that comes up.

**Comment by silvasean** [comment]
Wooo! Great work everyone :rocket:

**Comment by kon-pgk** [comment]
Hey as a beginner I wanted to ask if after this sprint there is a better way to register a custom op or should we still follow the custom-op-example ?

**Comment by makslevental** [comment]
> Hey as a beginner I wanted to ask if after this sprint there is a better way to register a custom op or should we still follow the custom-op-example ?

You should definitely use https://github.com/makslevental/torch-mlir/blob/main/test/python/custom_op_shape_dtype_fn.py instead.
