### ISSUE TITLE
ltc_backend_mnist example is not running

### ISSUE THREAD

**Issue by pralaydas** [llvm/torch-mlir#2030]
I have tried to run 
```bash
torch-mlir/examples/ltc_backend_mnist.py
```
but getting an error  
```bash
AttributeError: module 'torch_mlir._mlir_libs._REFERENCE_LAZY_BACKEND' has no attribute '_initialize'
```
how to resolve this issue?

**Comment by ramiro050** [comment]
Hi @pralaydas, are you setting `-DTORCH_MLIR_ENABLE_LTC=ON` in your `cmake` command? LTC is off by default when you build torch-mlir.
