### ISSUE TITLE
Lowering Torch Backend IR To TOSA Backend IR failed

### ISSUE THREAD

**Issue by peanutRen** [llvm/torch-mlir#2052]
When I tried to convert a model to mlir tosa, an error occurred and I don't know how to solve it.

I use `Torch` as the backend, there is no problem, but when I use `Tosa` or `Linalg-on-Tensors`, an error occurs.
## version
torch              2.0.0.dev20230220+cpu
torch-mlir         20230228.763

## net
```
        x = torch.relu(torch.max_pool2d(self.conv1(x), 2))
        x = torch.relu(torch.max_pool2d(self.conv2(x), 2))
        x = x.view(-1, 320)
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return torch.log_softmax(x, dim=1)
```

## Trace
1. `output_type="linalg-on-tensors"`
```
Segmentation fault (core dumped)
```

2. `output_type="tosa"`
```
Traceback (most recent call last):
  File "/home/renjw/compiler/frontend/torch-mlir/minist/translate.py", line 63, in <module>
    module = torch_mlir.compile(model, torch.ones(
  File "/root/anaconda3/envs/mlir/lib/python3.10/site-packages/torch_mlir/__init__.py", line 386, in compile
    run_pipeline_with_repro_report(
  File "/root/anaconda3/envs/mlir/lib/python3.10/site-packages/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> TOSA Backend IR failed with the following diagnostics:
error: 'tosa.max_pool2d' op attribute 'stride' failed to satisfy constraint: i64 dense array attribute with exactly 2 elements
note: see current operation: %33 = "tosa.max_pool2d"(%32) {kernel = array<i64: 2, 2>, pad = array<i64: 0, 0, 0, 0>, stride = array<i64>} : (tensor<1x24x24x10xf32>) -> tensor<1x23x23x10xf32>


For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torch-backend-to-tosa-backend-pipeline)' /tmp/Cnn.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
```

**Comment by ramiro050** [comment]
Hi @peanutRen, do you have a small python script that we can use to recreate the crash in `linalg-on-tensors`?

Regarding the tosa error, it seems that the lowering for `max_pool2d` in tosa does not properly handle the case where the stride is a single int rather than two ints. cc: @eric-k256

**Comment by eric-k256** [comment]
Yes, the single int version of stride is something we haven't implemented. I'll take a look, but using (2,2) strides for your max_pool2d operations as a workaround until that is fixed should work. (And may prove interesting for the `linalg-on-tensors` crash)

**Comment by peanutRen** [comment]
> Yes, the single int version of stride is something we haven't implemented. I'll take a look, but using (2,2) strides for your max_pool2d operations as a workaround until that is fixed should work. (And may prove interesting for the `linalg-on-tensors` crash)

Okay, the following test case can reproduce the error in linalg-on-tensors.

```
import torch.nn as nn
import torch
import torch_mlir

class Cnn(nn.Module):
    def __init__(self):
        super(Cnn, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)
 
    def forward(self, x):
        x = torch.relu(torch.max_pool2d(self.conv1(x), 2))
        x = torch.relu(torch.max_pool2d(self.conv2(x), 2))
        x = x.view(-1, 320)
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return torch.log_softmax(x, dim=1)



if __name__=="__main__":
    model = Cnn()
    module = torch_mlir.compile(model, torch.ones(
        1, 1, 28, 28),output_type="linalg-on-tensors")
```

**Comment by ramiro050** [comment]
Thanks for the simple reproducer. I have a fix for the linalg crash and the tosa handling of `stride` here: https://github.com/llvm/torch-mlir/pull/2065. Running your reproducer with that patch seems to lower to tosa and linalg without a problem. Let me know if you run into issues.

**Comment by peanutRen** [comment]
thanks @ramiro050 , your patch did work. https://github.com/llvm/torch-mlir/pull/2065
