### ISSUE TITLE
tensor_static_info_cast for slice/copy_

### ISSUE THREAD

**Issue by mgehre-amd** [llvm/torch-mlir#2156]
```
import torch
import torch_mlir

class Model(torch.nn.Module):
    def forward(self, arg0_1, clone):
        new_zeros = torch.ops.aten.new_zeros(arg0_1, [1, 12], pin_memory = False);  arg0_1 = None
        slice_3 = torch.ops.aten.slice(new_zeros, 0, 0, 9223372036854775807)
        slice_4 = torch.ops.aten.slice(slice_3, 1, 1, 9223372036854775807);  slice_3 = None
        copy_ = torch.ops.aten.copy_(slice_4, clone);  slice_4 = clone = None
        slice_5 = torch.ops.aten.slice(new_zeros, 0, 0, 9223372036854775807);  new_zeros = None
        return slice_5
        

model = Model() 
inps = (torch.ones(torch.Size([1, 12]), dtype=torch.int64), torch.ones(torch.Size([1, 11]), dtype=torch.int64), )
out = model(*inps)
torch_mlir.compile(model, inps, output_type='tosa')
```
gives
```
error: unsupported by backend contract: tensor with unknown rank
note: see current operation: %9 = "torch.tensor_static_info_cast"(%8) : (!torch.vtensor<[1,12],si64>) -> !torch.vtensor
```
with IR
```
// -----// IR Dump After LowerToBackendContract Failed (torch-lower-to-backend-contract) //----- //
module attributes {torch.debug_module_name = "Model"} {
  func.func @forward(%arg0: !torch.vtensor<[1,12],si64>, %arg1: !torch.vtensor<[1,11],si64>) -> !torch.vtensor {
    %int12 = torch.constant.int 12
    %int4 = torch.constant.int 4
    %none = torch.constant.none
    %false = torch.constant.bool false
    %int9223372036854775807 = torch.constant.int 9223372036854775807
    %int0 = torch.constant.int 0
    %int1 = torch.constant.int 1
    %0 = torch.prim.ListConstruct %int1, %int12 : (!torch.int, !torch.int) -> !torch.list<int>
    %1 = torch.aten.zeros %0, %int4, %none, %none, %false : !torch.list<int>, !torch.int, !torch.none, !torch.none, !torch.bool -> !torch.vtensor<[1,12],si64>
    %2 = torch.tensor_static_info_cast %1 : !torch.vtensor<[1,12],si64> to !torch.vtensor
    %3 = torch.copy.to_tensor %2 : !torch.tensor
    %4 = torch.aten.slice.Tensor %3, %int0, %int0, %int9223372036854775807, %int1 : !torch.tensor, !torch.int, !torch.int, !torch.int, !torch.int -> !torch.tensor<[1,12],unk>
    %5 = torch.tensor_static_info_cast %4 : !torch.tensor<[1,12],unk> to !torch.tensor
    %6 = torch.aten.slice.Tensor %4, %int1, %int1, %int9223372036854775807, %int1 : !torch.tensor<[1,12],unk>, !torch.int, !torch.int, !torch.int, !torch.int -> !torch.tensor<[1,11],unk>
    %7 = torch.aten.arange.start_step %int1, %int12, %int1, %none, %none, %none, %none : !torch.int, !torch.int, !torch.int, !torch.none, !torch.none, !torch.none, !torch.none -> !torch.vtensor<[11],si64>
    %8 = torch.copy.to_vtensor %5 : !torch.vtensor
    %9 = torch.prim.ListConstruct %7 : (!torch.vtensor<[11],si64>) -> !torch.list<optional<vtensor>>
    %10 = torch.aten._index_put_impl %8, %9, %arg1, %false, %false : !torch.vtensor, !torch.list<optional<vtensor>>, !torch.vtensor<[1,11],si64>, !torch.bool, !torch.bool -> !torch.vtensor<[1,12],unk>
    %11 = torch.tensor_static_info_cast %10 : !torch.vtensor<[1,12],unk> to !torch.vtensor
    torch.overwrite.tensor.contents %11 overwrites %5 : !torch.vtensor, !torch.tensor
    %12 = torch.aten.slice.Tensor %3, %int0, %int0, %int9223372036854775807, %int1 : !torch.tensor, !torch.int, !torch.int, !torch.int, !torch.int -> !torch.tensor<[1,12],unk>
    %13 = torch.tensor_static_info_cast %12 : !torch.tensor<[1,12],unk> to !torch.tensor
    %14 = torch.copy.to_vtensor %13 : !torch.vtensor
    return %14 : !torch.vtensor
  }
}
```
This is not fixed by #2150.
If someone can point me at the actual issue here, I could try to attempt a fix.
Currently I cannot make sense of all the tensor_static_info_cast / copy.to_vtensor, and `unk` dtypes to understand where the issue starts.

**Comment by Abhishek-TyRnT** [comment]
I tried to reproduce your error, I am getting this error
` python3: /usr/local/include/mlir/IR/StorageUniquerSupport.h:174: static ConcreteT mlir::detail::StorageUserBase<mlir::torch::Torch::ValueTensorType, mlir::torch::Torch::BaseTensorType, mlir::torch::Torch::detail::ValueTensorTypeStorage, mlir::detail::TypeUniquer>::get(mlir::MLIRContext *, Args...) [ConcreteT = mlir::torch::Torch::ValueTensorType, BaseT = mlir::torch::Torch::BaseTensorType, StorageT = mlir::torch::Torch::detail::ValueTensorTypeStorage, UniquerT = mlir::detail::TypeUniquer, Traits = <>, Args = <std::optional<llvm::ArrayRef<long> >, mlir::Type>]: Assertion succeeded(ConcreteT::verify(getDefaultDiagnosticEmitFn(ctx), args...)) failed.
Aborted `

**Comment by mgehre-amd** [comment]
> I tried to reproduce your error, I am getting this error `python3: /usr/local/include/mlir/IR/StorageUniquerSupport.h:174: static ConcreteT mlir::detail::StorageUserBase<mlir::torch::Torch::ValueTensorType, mlir::torch::Torch::BaseTensorType, mlir::torch::Torch::detail::ValueTensorTypeStorage, mlir::detail::TypeUniquer>::get(mlir::MLIRContext *, Args...) [ConcreteT = mlir::torch::Torch::ValueTensorType, BaseT = mlir::torch::Torch::BaseTensorType, StorageT = mlir::torch::Torch::detail::ValueTensorTypeStorage, UniquerT = mlir::detail::TypeUniquer, Traits = <>, Args = <std::optional<llvm::ArrayRef<long> >, mlir::Type>]: Assertion succeeded(ConcreteT::verify(getDefaultDiagnosticEmitFn(ctx), args...)) failed. Aborted`

Which git hash of torch_mlir are you using?

**Comment by Abhishek-TyRnT** [comment]
f0b7b63be06fc0ed5bdf43e02967cd47a53a24fc

**Comment by mgehre-amd** [comment]
@Abhishek-TyRnT, I can also see the crash on `https://github.com/llvm/torch-mlir/commit/f0b7b63be06fc0ed5bdf43e02967cd47a53a24fc`.
To reproduce the reported issue, you can use the branch of https://github.com/llvm/torch-mlir/pull/2150.
