### ISSUE TITLE
Unable to Install torch-mlir due to Conflicting Dependencies 

### ISSUE THREAD

**Issue by clw5710** [llvm/torch-mlir#2215]
I've been recieving the following error when trying to install the torch-mlir snapshot. I'm working on an Ubuntu machine with 20.04 and Python 3.10.11. I created a conda virtual environment and even tried to specify the latest torch-mlir version and torch==2.0.0 when installing however the issue persists. I don't understand the error because I have none of these packages installed currently.

![image](https://github.com/llvm/torch-mlir/assets/135144407/7168da5c-3191-4433-81f6-c51d10987f15)

**Comment by bet20ICL** [comment]
How did you solve this? Getting the same error :((

**Comment by clw5710** [comment]
Following these steps worked for me. You may need to use python3 instead of just python. Also, I was doing this on a Linux VM - specifically Ubuntu 20.04
```
$ python -m venv mlir_venv
$ source mlir_venv/bin/activate
$ python -m pip install --upgrade pip
$ pip install --pre torch-mlir torchvision -f https://llvm.github.io/torch-mlir/package-index/ --extra-index-url https://download.pytorch.org/whl/nightly/cpu
```
