### ISSUE TITLE
Error: Operand #0 does not dominate this issue

### ISSUE THREAD

**Issue by clw5710** [llvm/torch-mlir#2221]
I'm not sure where to start with this issue. Seems related to the linalg dialect or perhaps the sizing of the example tensor that was passed to `torch.compile()`. I specified the example argument using torch.ones(). 

Any insight would be appreciated.

![image](https://github.com/llvm/torch-mlir/assets/135144407/cddc68df-1955-4fab-a4cb-50465f77b571)

**Comment by ramiro050** [comment]
This error means that the first argument to `linalg.generic` might not be defined by the time the `linalg.generic` is reached. Torch-MLIR should not generate IR that results in such an error. Can you paste the full error, and if you have a small reproducer include that as well, and I can take a look.

**Comment by clw5710** [comment]
I am using torch-mlir through a tool called [scaleHLS](https://github.com/hanchenye/scalehls). The pyTorch model I am using is the well-known Iris dataset. 

Here are the steps I was following to use scaleHLS as per their README. 
`$ python -m venv mlir_venv
$ source mlir_venv/bin/activate
$ python -m pip install --upgrade pip
$ pip install --pre torch-mlir torchvision -f https://llvm.github.io/torch-mlir/package-index/ --extra-index-url https://download.pytorch.org/whl/nightly/cpu`

`$ cd samples/pytorch/Iris_compiled2

$ # Parse PyTorch model to LinAlg dialect (with Torch-MLIR mlir_venv activated).
$ python3 Iris_compiled2.py > Iris_compiled2.mlir

$ # Optimize the model and emit C++ code.
$ scalehls-opt Iris_compiled2.mlir \
    -scaleflow-pytorch-pipeline="top-func=forward loop-tile-size=8 loop-unroll-factor=4" \
    | scalehls-translate -scalehls-emit-hlscpp > Iris_compiled2.cpp`

This last line is when I get the error. There is no problem generating the `Iris_compiled2.mlir` file. Here is the relevant code to convert the **trained** model to mlir: 

`X,y,names,feature_names = load_data()
X_train,X_test,y_train,y_test = split_data(X,y)
model = train_model(X_train,X_test,y_train,y_test)
torch.save(model,"./weights.pt")
[data_row, data_cols] = X.shape
module = torch_mlir.compile(model, torch.ones(data_row, data_cols), output_type=torch_mlir.OutputType.LINALG_ON_TENSORS)

print(module)   #pipe compiled output to .mlir file `


This is the full error:
`scalehls-opt Iris_compiled2.mlir      -scaleflow-pytorch-pipeline="top-func=forward loop-tile-size=8 loop-unroll-factor=4"     | scalehls-translate -scalehls-emit-hlscpp > Iris_compiled2.cpp
Iris_compiled2.mlir:51:13: error: operand #0 does not dominate this use
    %17:2 = linalg.generic {indexing_maps = [#map, #map3, #map3], iterator_types = ["parallel", "reduction"]} ins(%12 : tensor<150x3xf32>) outs(%16, %14 : tensor<150x1xf32>, tensor<150x1xi64>) {
            ^
Iris_compiled2.mlir:51:13: note: see current operation: 
%13 = "linalg.generic"(%10#1, %12) ({
^bb0(%arg1: f32, %arg2: f32):
  %14 = "arith.maxf"(%arg1, %arg2) : (f32, f32) -> f32
  "linalg.yield"(%14) : (f32) -> ()
}) {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, 0)>], iterator_types = ["parallel", "reduction"], operand_segment_sizes = array<i32: 1, 1>} : (tensor<150x3xf32>, tensor<150x1xf32>) -> tensor<150x1xf32>
<unknown>:0: note: operand defined here (op in a parent region)`

**Comment by clw5710** [comment]
@ramiro050 I've also noticed a somewhat similar error when trying to use a pyTorch sample that was given by the scaleHLS creators. That code uses the following pretrained pyTorch model shown here: 
 
```
import sys
import torch
import torchvision.models as models
import torch_mlir

resnet18 = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
resnet18.train(False)
module = torch_mlir.compile(resnet18, torch.ones(
    1, 3, 32, 32), output_type=torch_mlir.OutputType.LINALG_ON_TENSORS)

print(module)
```

This error specifies an operand #2 error that is somewhat similar but much longer: 
`scalehls-opt resnet18_torchvision.mlir -scaleflow-pytorch-pipeline="top-func=forward loop-tile-size=8 loop-unroll-factor=4" | scalehls-translate -scalehls-emit-hlscpp > resnet18_torchvision.cpp <unknown>:0: error: operand #2 does not dominate this use <unknown>:0: note: see current operation:  "hls.dataflow.node"(<<UNKNOWN SSA VALUE>>, <<UNKNOWN SSA VALUE>>, <<UNKNOWN SSA VALUE>>, <<UNKNOWN SSA VALUE>>) ({ ^bb0(%arg0: memref<256x2x2xf32, 12>, %arg1: memref<512x256x3x3xf32, 12>, %arg2: memref<512xf32, 7>, %arg3: memref<512xf32, 7>): "affine.for"() ({ ^bb0(%arg4: index): "affine.for"() ({ ^bb0(%arg5: index): "affine.for"() ({ ^bb0(%arg6: index): "affine.for"() ({ ^bb0(%arg7: index): "hls.dataflow.schedule"(%arg4, %arg3, %arg2, %arg0, %arg1, %arg5, %arg7, %arg6) ({ ^bb0(%arg8: index, %arg9: memref<512xf32, 7>, %arg10: memref<512xf32, 7>, %arg11: memref<256x2x2xf32, 12>, %arg12: memref<512x256x3x3xf32, 12>, %arg13: index, %arg14: index, %arg15: index): %0 = "hls.dataflow.buffer"() {depth = 1 : i32} : () -> memref<8x8xf32, 7> %1 = "hls.dataflow.buffer"() {depth = 1 : i32} : () -> memref<8xf32, 7> "hls.dataflow.node"(%arg11, %1, %arg8, %arg13, %arg15) ({ ^bb0(%arg16: memref<256x2x2xf32, 12>, %arg17: memref<8xf32, 7>, %arg18: index, %arg19: index, %arg20: index): "affine.for"() ({ ^bb0(%arg21: index): %2 = "affine.load"(%arg16, %arg21, %arg18, %arg19, %arg20) {map = affine_map<(d0, d1, d2, d3) -> (d0 + d1 * 8, d2 - 1, d3 - 1)>} : (memref<256x2x2xf32, 12>, index, index, index, index) -> f32 "affine.store"(%2, %arg17, %arg21) {map = affine_map<(d0) -> (d0)>} : (f32, memref<8xf32, 7>, index) -> () "affine.yield"() : () -> () }) {lower_bound = affine_map<() -> (0)>, parallel, step = 1 : index, upper_bound = affine_map<() -> (8)>} : () -> () }) {inputTaps = [0 : i32], operand_segment_sizes = array<i32: 1, 1, 3>} : (memref<256x2x2xf32, 12>, memref<8xf32, 7>, index, index, index) -> () "hls.dataflow.node"(%arg12, %0, %arg13, %arg15, %arg14, %arg8) ({ ^bb0(%arg16: memref<512x256x3x3xf32, 12>, %arg17: memref<8x8xf32, 7>, %arg18: index, %arg19: index, %arg20: index, %arg21: index): "affine.for"() ({ ^bb0(%arg22: index): "affine.for"() ({ ^bb0(%arg23: index): %2 = "affine.load"(%arg16, %arg18, %arg19, %arg22, %arg20, %arg23, %arg21) {map = affine_map<(d0, d1, d2, d3, d4, d5) -> (d2 + d3 * 8, d4 + d5 * 8, d0, d1)>} : (memref<512x256x3x3xf32, 12>, index, index, index, index, index, index) -> f32 "affine.store"(%2, %arg17, %arg22, %arg23) {map = affine_map<(d0, d1) -> (d0, d1)>} : (f32, memref<8x8xf32, 7>, index, index) -> () "affine.yield"() : () -> () }) {lower_bound = affine_map<() -> (0)>, parallel, step = 1 : index, upper_bound = affine_map<() -> (8)>} : () -> () "affine.yield"() : () -> () }) {lower_bound = affine_map<() -> (0)>, parallel, step = 1 : index, upper_bound = affine_map<() -> (8)>} : () -> () }) {inputTaps = [0 : i32], operand_segment_sizes = array<i32: 1, 1, 4>} : (memref<512x256x3x3xf32, 12>, memref<8x8xf32, 7>, index, index, index, index) -> () "hls.dataflow.node"(%arg10, %1, %0, %arg9, %arg14, %arg15, %arg13, %arg8) ({ ^bb0(%arg16: memref<512xf32, 7>, %arg17: memref<8xf32, 7>, %arg18: memref<8x8xf32, 7>, %arg19: memref<512xf32, 7>, %arg20: index, %arg21: index, %arg22: index, %arg23: index): "affine.for"() ({ ^bb0(%arg24: index): "affine.for"() ({ ^bb0(%arg25: index): %2 = "affine.load"(%arg16, %arg25, %arg20) {map = affine_map<(d0, d1) -> (d0 + d1 * 8)>} : (memref<512xf32, 7>, index, index) -> f32 %3 = "affine.load"(%arg19, %arg25, %arg20) {map = affine_map<(d0, d1) -> (d0 + d1 * 8)>} : (memref<512xf32, 7>, index, index) -> f32 %4 = "hls.affine.select"(%arg22, %arg21, %arg24, %arg23, %2, %3) {condition = affine_set<(d0, d1, d2, d3) : (d2 + d3 * 8 == 0, d0 == 0, d1 == 0)>} : (index, index, index, index, f32, f32) -> f32 %5 = "affine.load"(%arg17, %arg24) {map = affine_map<(d0) -> (d0)>} : (memref<8xf32, 7>, index) -> f32 %6 = "affine.load"(%arg18, %arg25, %arg24) {map = affine_map<(d0, d1) -> (d0, d1)>} : (memref<8x8xf32, 7>, index, index) -> f32 %7 = "arith.mulf"(%5, %6) : (f32, f32) -> f32 %8 = "arith.addf"(%4, %7) : (f32, f32) -> f32 "affine.store"(%8, %arg19, %arg25, %arg20) {map = affine_map<(d0, d1) -> (d0 + d1 * 8)>} : (f32, memref<512xf32, 7>, index, index) -> () "affine.yield"() : () -> () }) {lower_bound = affine_map<() -> (0)>, parallel, point, step = 1 : index, upper_bound = affine_map<() -> (8)>} : () -> () "affine.yield"() : () -> () }) {lower_bound = affine_map<() -> (0)>, point, step = 1 : index, upper_bound = affine_map<() -> (8)>} : () -> () }) {inputTaps = [0 : i32, 0 : i32, 0 : i32], operand_segment_sizes = array<i32: 3, 1, 4>} : (memref<512xf32, 7>, memref<8xf32, 7>, memref<8x8xf32, 7>, memref<512xf32, 7>, index, index, index, index) -> () }) : (index, memref<512xf32, 7>, memref<512xf32, 7>, memref<256x2x2xf32, 12>, memref<512x256x3x3xf32, 12>, index, index, index) -> () "affine.yield"() : () -> () }) {lower_bound = affine_map<() -> (0)>, parallel, step = 1 : index, upper_bound = affine_map<() -> (64)>} : () -> () "affine.yield"() : () -> () }) {lower_bound = affine_map<() -> (0)>, step = 1 : index, upper_bound = affine_map<() -> (3)>} : () -> () "affine.yield"() : () -> () }) {lower_bound = affine_map<() -> (0)>, step = 1 : index, upper_bound = affine_map<() -> (3)>} : () -> () "affine.yield"() : () -> () }) {lower_bound = affine_map<() -> (0)>, step = 1 : index, upper_bound = affine_map<() -> (32)>} : () -> () }) {inputTaps = [0 : i32, 0 : i32, 0 : i32], operand_segment_sizes = array<i32: 3, 1, 0>} : (memref<256x2x2xf32, 12>, memref<512x256x3x3xf32, 12>, memref<512xf32, 7>, memref<512xf32, 7>) -> () <unknown>:0: note: operand defined here (op in the same block)`

**Comment by ramiro050** [comment]
> Thank you for the response @ramiro050 , I am using torch-mlir through a tool called [scaleHLS](https://github.com/hanchenye/scalehls). The pyTorch model I am using is the well-known Iris dataset.

This seems to be a bug in `scalehls-opt`. If `torch_mlir.compile` does not fail with any errors, that means the IR generated satisfied all the verifiers for the output dialect. The error you're getting on the `linalg.generic` must be from an invalid IR transformation happening after `torch_mlir.compile`.

**Comment by clw5710** [comment]
@ramiro050 Thank you for the reply. I'll close the issue after this last question. Is there a reason this invalid IR transformation occurs using trained PyTorch models? I've tried using untrained models and they successfully run.

**Comment by ramiro050** [comment]
> @ramiro050 Thank you for the reply. I'll close the issue after this last question. Is there a reason this invalid IR transformation occurs using trained PyTorch models? I've tried using untrained models and they successfully run.

I'm not sure. My guess is that they generate slightly different graphs, but it's difficult to say without looking at the IR being generated.

**Comment by clw5710** [comment]
I noticed this line in the MLIR output. Does this mean that currently the linalg dialect cannot represent a trained 2d convolution layer?

`%39 = linalg.conv_2d_nchw_fchw {dilations = dense<1> : vector<2xi64>, strides = dense<1> : vector<2xi64>} ins(%padded_109, %cst_53 : tensor<1x128x6x6xf32>, tensor<128x128x3x3xf32>) outs(%26 : tensor<1x128x4x4xf32>) -> tensor<1x128x4x4xf32>
    cf.assert %3, "training is not supported for now"`
