### ISSUE TITLE
access operand or result

### ISSUE THREAD

**Issue by maibaodexiaohangjiaya** [llvm/torch-mlir#2232]
Hi,
Is there any way for me to access the operands or results in the mlir code, I tried calling some methods in OperationBase, but it doesn't seem to work.
<img width="755" alt="mlir" src="https://github.com/llvm/torch-mlir/assets/115870155/d585aeb2-d223-4e47-8201-58710e03ec19">

**Comment by ramiro050** [comment]
I'm assuming you're using the MLIR Python bindings. They unfortunately take a bit of guesswork to use. If I remember correctly, you can turn an `OpOperandList` into an actual list of operands by doing `list(operand_list)`.
