### ISSUE TITLE
avg_pool1d function padding init value should be (0,)

### ISSUE THREAD

**Issue by JianzheXiao** [llvm/torch-mlir#2242]
Currently in JITOperatorRegistryDump.txt the padding in  avg_pool1d  has the value List[int] = (0), this vill cause an error that ask you provide a default value of type  List[int] on parameter padding, which should be (0,) or something else

shape_function_signature = def aten〇avg_pool1d〡shape(self: List[int], kernel_size: List[int], stride: List[int] = (), padding: List[int] = (0), ceil_mode: bool = False, count_include_pad: bool = True) -> List[int]:
  decomposition_function_signature = def aten〇avg_pool1d〡decomposition(self: Tensor, kernel_size: List[int], stride: List[int] = (), padding: List[int] = (0), ceil_mode: bool = False, count_include_pad: bool = True) -> Tensor:
  dtype_function_signature = def aten〇avg_pool1d〡dtype(self_rank_dtype: Tuple[int, int], kernel_size: List[int], stride: List[int] = (), padding: List[int] = (0), ceil_mode: bool = False, count_include_pad: bool = True) -> int:

**Comment by ramiro050** [comment]
Nice catch! I've made a patch fixing it: https://github.com/llvm/torch-mlir/pull/2258
