### ISSUE TITLE
[Build][Error] link error when building torch-mlir from source

### ISSUE THREAD

**Issue by Mookel** [llvm/torch-mlir#2334]
Hi, 

I encountered a link error when building torch-mlir from source by following the guide in https://github.com/llvm/torch-mlir/blob/main/docs/development.md:

`[3588/3609] Linking CXX executable bin/torch-mlir-capi-torch-test
FAILED: bin/torch-mlir-capi-torch-test
: && /usr/bin/c++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -Wl,-rpath-link,/workspace/torch-mlir/build/./lib  -Wl,--gc-sections tools/torch-mlir/test/CAPI/CMakeFiles/torch-mlir-capi-torch-test.dir/torch.c.o -o bin/torch-mlir-capi-torch-test  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libMLIRCAPIIR.a  lib/libMLIRCAPIRegisterEverything.a  lib/libTorchMLIRCAPI.a  lib/libMLIRCAPIIR.a  lib/libMLIRBytecodeWriter.a  lib/libMLIRBytecodeOpInterface.a  lib/libMLIRAffineTransformOps.a  lib/libMLIRAMDGPUTransforms.a  lib/libMLIRArithValueBoundsOpInterfaceImpl.a  lib/libMLIRAsyncTransforms.a  lib/libMLIRBufferizationTransformOps.a  lib/libMLIRGPUTransformOps.a  lib/libMLIRIRDL.a  lib/libMLIRLinalgTransformOps.a  lib/libMLIRMemRefTransformOps.a  lib/libMLIRNVGPUTransforms.a  lib/libMLIRSCFTransformOps.a  lib/libMLIRShapeOpsTransforms.a  lib/libMLIRSparseTensorPipelines.a  lib/libMLIRSparseTensorTransforms.a  lib/libMLIRSparseTensorUtils.a  lib/libMLIRSPIRVModuleCombiner.a  lib/libMLIRSPIRVTransforms.a  lib/libMLIRTensorInferTypeOpInterfaceImpl.a  lib/libMLIRTensorTransformOps.a  lib/libMLIRTransformPDLExtension.a  lib/libMLIRVectorTransformOps.a  lib/libMLIRTargetCpp.a  lib/libMLIREmitCDialect.a  lib/libMLIRSPIRVTranslateRegistration.a  lib/libMLIRSPIRVDeserialization.a  lib/libMLIRToLLVMIRTranslationRegistration.a  lib/libMLIRArmNeonToLLVMIRTranslation.a  lib/libMLIRArmSMEToLLVMIRTranslation.a  lib/libMLIRArmSVEToLLVMIRTranslation.a  lib/libMLIRAMXToLLVMIRTranslation.a  lib/libMLIRNVVMToLLVMIRTranslation.a  lib/libMLIROpenACCToLLVMIRTranslation.a  lib/libMLIROpenMPToLLVMIRTranslation.a  lib/libMLIRROCDLToLLVMIRTranslation.a  lib/libMLIRX86VectorToLLVMIRTranslation.a  lib/libMLIRFromLLVMIRTranslationRegistration.a  lib/libMLIRLLVMIRToLLVMTranslation.a  lib/libMLIRTargetLLVMIRImport.a  lib/libMLIRArmNeon2dToIntr.a  lib/libMLIRBufferizationToMemRef.a  lib/libMLIRComplexToLLVM.a  lib/libMLIRComplexToLibm.a  lib/libMLIRComplexToSPIRV.a  lib/libMLIRComplexToStandard.a  lib/libMLIRControlFlowToSPIRV.a  lib/libMLIRGPUToNVVMTransforms.a  lib/libMLIRGPUToROCDLTransforms.a  lib/libMLIRAMDGPUToROCDL.a  lib/libMLIRAMDGPUUtils.a  lib/libMLIRAMDGPUDialect.a  lib/libMLIRROCDLDialect.a  lib/libMLIRGPUToGPURuntimeTransforms.a  lib/libMLIRAsyncToLLVM.a  lib/libMLIRGPUToSPIRV.a  lib/libMLIRGPUToVulkanTransforms.a  lib/libMLIRSPIRVSerialization.a  lib/libMLIRSPIRVBinaryUtils.a  lib/libMLIRIndexToLLVM.a  lib/libMLIRLinalgToStandard.a  lib/libMLIRMathToFuncs.a  lib/libMLIRMathToLibm.a  lib/libMLIRMathToLLVM.a  lib/libMLIRMathToSPIRV.a  lib/libMLIRNVGPUToNVVM.a  lib/libMLIROpenACCToSCF.a  lib/libMLIROpenACCDialect.a  lib/libMLIROpenMPToLLVM.a  lib/libMLIRSCFToGPU.a  lib/libMLIRGPUTransforms.a  lib/libMLIRAsyncDialect.a  lib/libMLIRIndexDialect.a  lib/libMLIRBuiltinToLLVMIRTranslation.a  lib/libMLIRGPUToLLVMIRTranslation.a  lib/libMLIRLLVMToLLVMIRTranslation.a  lib/libMLIRExecutionEngineUtils.a  lib/libLLVMPasses.a  lib/libLLVMCoroutines.a  lib/libLLVMipo.a  lib/libLLVMVectorize.a  lib/libLLVMLinker.a  lib/libLLVMInstrumentation.a  lib/libLLVMCodeGen.a  lib/libLLVMCodeGenTypes.a  lib/libLLVMIRPrinter.a  lib/libLLVMObjCARCOpts.a  lib/libLLVMTarget.a  lib/libMLIRSCFToOpenMP.a  lib/libMLIROpenMPDialect.a  lib/libMLIRSCFToSPIRV.a  lib/libMLIRMemRefToSPIRV.a  lib/libMLIRShapeToStandard.a  lib/libMLIRSPIRVToLLVM.a  lib/libMLIRSPIRVUtils.a  lib/libMLIRTensorToLinalg.a  lib/libMLIRTensorToSPIRV.a  lib/libMLIRArithToSPIRV.a  lib/libMLIRFuncToSPIRV.a  lib/libMLIRTosaToArith.a  lib/libMLIRTosaToLinalg.a  lib/libMLIRTosaToSCF.a  lib/libMLIRTosaToTensor.a  lib/libMLIRVectorToGPU.a  lib/libMLIRNVGPUUtils.a  lib/libMLIRVectorToSPIRV.a  lib/libMLIRSPIRVConversion.a  lib/libMLIRSPIRVDialect.a  lib/libMLIRFuncAllExtensions.a  lib/libMLIRFuncInlinerExtension.a  lib/libMLIRCAPITransforms.a  lib/libTorchMLIRInitAll.a  lib/libTorchMLIRTorchConversionPasses.a  lib/libMLIRTosaTransforms.a  lib/libChloPasses.a  lib/libTorchMLIRTMTensorPasses.a  lib/libTorchMLIRConversionPasses.a  lib/libTorchMLIRTorchConversionToMLProgram.a  lib/libMLIRMLProgramDialect.a  lib/libTorchMLIRTorchToArith.a  lib/libTorchMLIRTorchToLinalg.a  lib/libTorchMLIRTorchToSCF.a  lib/libTorchMLIRTorchConversionDialect.a  lib/libTorchMLIRTorchToTMTensor.a  lib/libTorchMLIRTMTensorDialect.a  lib/libTorchMLIRTorchToTosa.a  lib/libMLIRTosaDialect.a  lib/libMLIRQuantUtils.a  lib/libTorchMLIRTorchToStablehlo.a  lib/libTorchMLIRConversionUtils.a  lib/libMLIRBufferTransforms.a  lib/libMLIRTransformDialectTransforms.a  lib/libMLIRTransformDialect.a  lib/libMLIRTransformDialectUtils.a  lib/libMLIRLinalgToLLVM.a  lib/libMLIRAffineToStandard.a  lib/libMLIRMemRefToLLVM.a  lib/libMLIRMemRefUtils.a  lib/libMLIRSCFToControlFlow.a  lib/libMLIRReconcileUnrealizedCasts.a  lib/libGmlStBufferizableOpInterface.a  lib/libMLIRHLOAnalysis.a  lib/libThloBufferizableOpInterface.a  lib/libTHLODialect.a  lib/libGmlStDialect.a  lib/libTorchMLIRRefBackend.a  lib/libMLIRMathTransforms.a  lib/libMhloPasses.a  lib/libMhloAnalysis.a  lib/libMhloScatterUtils.a  lib/libMhloToLinalg.a  lib/libMLIRLinalgTransforms.a  lib/libMLIRMemRefTransforms.a  lib/libMLIRArithTransforms.a  lib/libMLIRNVGPUDialect.a  lib/libMLIRSCFTransforms.a  lib/libMLIRTensorTilingInterfaceImpl.a  lib/libMLIRTensorTransforms.a  lib/libMLIRAffineTransforms.a  lib/libMLIRSCFUtils.a  lib/libMLIRVectorToLLVM.a  lib/libMLIRArmNeonDialect.a  lib/libMLIRArmSMETransforms.a  lib/libMLIRArmSMEDialect.a  lib/libMLIRArmSVETransforms.a  lib/libMLIRArmSVEDialect.a  lib/libMLIRAMXTransforms.a  lib/libMLIRAMXDialect.a  lib/libMLIRTargetLLVMIRExport.a  lib/libMLIRLLVMIRTransforms.a  lib/libMLIRNVVMDialect.a  lib/libMLIRTranslateLib.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMScalarOpts.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMTransformUtils.a  lib/libMLIRX86VectorTransforms.a  lib/libMLIRX86VectorDialect.a  lib/libMLIRFuncToLLVM.a  lib/libMLIRArithToLLVM.a  lib/libMLIRArithAttrToLLVMConversion.a  lib/libMLIRControlFlowToLLVM.a  lib/libMLIRLLVMCommonConversion.a  lib/libMLIRVectorToSCF.a  lib/libMLIRVectorTransforms.a  lib/libMLIRGPUDialect.a  lib/libMLIRDLTIDialect.a  lib/libMLIRVectorUtils.a  lib/libMLIRVectorDialect.a  lib/libMLIRMaskableOpInterface.a  lib/libMLIRMaskingOpInterface.a  lib/libMLIRVectorInterfaces.a  lib/libHloToLinalgUtils.a  lib/libLmhloDialect.a  lib/libLmhloStructuredInterface.a  lib/libMhloRngUtils.a  lib/libMLIRLinalgUtils.a  lib/libMLIRAffineUtils.a  lib/libMLIRAffineAnalysis.a  lib/libMLIRLinalgDialect.a  lib/libMLIRParser.a  lib/libMLIRBytecodeReader.a  lib/libMLIRTilingInterface.a  lib/libMLIRTensorUtils.a  lib/libMhloToArithmeticConversion.a  lib/libMLIRMathDialect.a  lib/libMLIRSCFDialect.a  lib/libMLIRControlFlowDialect.a  lib/libStablehloToMhlo.a  lib/libMLIRAsmParser.a  lib/libMhloTypeConversion.a  lib/libMLIRFuncTransforms.a  lib/libMLIRBufferizationTransforms.a  lib/libMLIRBufferizationDialect.a  lib/libMhloDialect.a  lib/libMLIRMhloUtils.a  lib/libMLIRLLVMDialect.a  lib/libLLVMBitWriter.a  lib/libLLVMAnalysis.a  lib/libLLVMProfileData.a  lib/libLLVMSymbolize.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMObject.a  lib/libLLVMIRReader.a  lib/libLLVMAsmParser.a  lib/libLLVMBitReader.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMTextAPI.a  lib/libChloOps.a  lib/libStablehloBroadcastUtils.a  lib/libHloOpsCommon.a  lib/libStablehloOps.a  lib/libMLIRSparseTensorDialect.a  lib/libStablehloTypeInference.a  lib/libStablehloAssemblyFormat.a  lib/libStablehloBase.a  lib/libMLIRQuantDialect.a  lib/libMLIRShapeDialect.a  lib/libMLIRTensorDialect.a  lib/libMLIRAffineDialect.a  lib/libMLIRMemRefDialect.a  lib/libMLIRComplexDialect.a  lib/libMLIRDialectUtils.a  lib/libMLIRArithUtils.a  lib/libMLIRArithDialect.a  lib/libMLIRInferIntRangeCommon.a  lib/libMLIRShapedOpInterfaces.a  lib/libMLIRValueBoundsOpInterface.a  lib/libMLIRDestinationStyleOpInterface.a  lib/libMLIRParallelCombiningOpInterface.a  lib/libMLIRCastInterfaces.a  lib/libMLIRDialect.a  lib/libTorchMLIRTorchPasses.a  lib/libTorchMLIRTorchDialect.a  lib/libMLIRFuncDialect.a  lib/libMLIRTransforms.a  lib/libMLIRTransformUtils.a  lib/libMLIRRewrite.a  lib/libMLIRPDLToPDLInterp.a  lib/libMLIRPass.a  lib/libMLIRAnalysis.a  lib/libMLIRCallInterfaces.a  lib/libMLIRControlFlowInterfaces.a  lib/libMLIRPresburger.a  lib/libMLIRLoopLikeInterface.a  lib/libMLIRViewLikeInterface.a  lib/libMLIRInferIntRangeInterface.a  lib/libMLIRDataLayoutInterfaces.a  lib/libMLIRPDLInterpDialect.a  lib/libMLIRPDLDialect.a  lib/libMLIRInferTypeOpInterface.a  lib/libMLIRSideEffectInterfaces.a  lib/libMLIRMemorySlotInterfaces.a  lib/libMLIRCopyOpInterface.a  lib/libMLIRRuntimeVerifiableOpInterface.a  lib/libMLIRIR.a  lib/libMLIRSupport.a  lib/libTorchMLIRTorchUtils.a  lib/libLLVMCore.a  lib/libLLVMBinaryFormat.a  lib/libLLVMTargetParser.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libLLVMSupport.a  -lrt  -ldl  -lm  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libtinfo.so  lib/libLLVMDemangle.a && :
/usr/bin/ld: lib/libTorchMLIRInitAll.a(InitAll.cpp.o): in function `mlir::torch::registerAllDialects(mlir::DialectRegistry&)':
InitAll.cpp:(.text._ZN4mlir5torch19registerAllDialectsERNS_15DialectRegistryE+0x1b1): undefined reference to `mlir::func::registerInlinerExtension(mlir::DialectRegistry&)'
collect2: error: ld returned 1 exit status
[3591/3609] Linking CXX shared library tools/torch-mlir/python_packages/torch_mlir/torch_mlir/_mlir_libs/libTorchMLIRAggregateCAPI.so
ninja: build stopped: subcommand failed.`

The only difference with the native build steps is that I used a conda environment instead.  Below are the reproducing steps: 
```bash
$ conda create -n torch-mlir python=3.10
$ conda activate torch-mlir
$ python -m pip install --upgrade pip
$ cd torch-mlir
$ python -m pip install -r requirements.txt
$ ./build_tools/build_standalone.sh
```

GCC version in host: 
```
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

 
System Information:
```
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

```

I tried building torch-mlir in CI docker as well and encountered same error: 
- **docker**: CI docker built by using Dockerfile provided by torch-mlir: `docker build -t your-name/torch-mlir-ci --no-cache .`
-  **python version**: python 3.10
- **build script**:  ./build_tools/build_standalone.sh
- **branch of torch-mlir**: main branch with commit id [fb4c54f](https://github.com/llvm/torch-mlir/commit/fb4c54fbef9d083d3cdbc218ffc71cc112082fd9) 

I will check this issue further but could anyone provide some hints? Thanks in advance.

**Comment by wonderzy** [comment]
same problem, any suggestion?

**Comment by Mookel** [comment]
The latest commit works well 991eba2b513d1434b10723cf3e1f456ae458a96c , just close this issue.
