### ISSUE TITLE
Non-value semantic ops should have stronger verifiers

### ISSUE THREAD

**Issue by stellaraccident** [llvm/torch-mlir#2490]
Currently, in-place ops are defined like:

```
def Torch_AtenTanh_Op : Torch_Op<"aten.tanh_", [
    IsTrailingUnderscoreInplaceVariant,
    AllowsTypeRefinement
  ]> {
  let summary = "Generated op for `aten::tanh_ : (Tensor) -> (Tensor)`";
  let arguments = (ins
    AnyTorchTensorType:$self
  );
  let results = (outs
    AnyTorchTensorType:$result
  );
  let hasCustomAssemblyFormat = 1;
  let extraClassDefinition = [{
    ParseResult AtenTanh_Op::parse(OpAsmParser &parser, OperationState &result) {
      return parseDefaultTorchOp(parser, result, 1, 1);
    }
    void AtenTanh_Op::print(OpAsmPrinter &printer) {
      printDefaultTorchOp(printer, *this, 1, 1);
    }
  }];
}
```

The result is that if a `!torch.vtensor` is inadvertently passed, bad things happen later during lowering. We should tighten up verification by one of:

1. Making the `IsTrailingUnderscoreInplaceVariant` trait perform stronger verification of the first argument/result type.
2. Teach the `torch_ods_gen.py` to emit the proper, more constrained types (vs `AnyTorchTensorType`).

Either would produce the correct result but 2 is more explicit and provides better documentation value. Doing that would require some minor refactoring of the `raw_emit_op` helper of `torch_ods_gen.py` so that it tweaks the types if the trait is present.

On the other hand, implementing in 1 would allow us to emit a much more friendly error message, which may help for exotic cases.

**Comment by stellaraccident** [comment]
It would be great to get a patch for this.

The primary complexity here is that the code in that TD file is generated from the pytorch op registry, so you have to teach torch_ods_gen.py how to do it.

I'm afk but I believe that there is a tablegen type for value tensors vs non value tensors. You probably don't need to further constrain these by style.

**Comment by gptsarthak** [comment]
Have a look at https://github.com/llvm/torch-mlir/pull/2519 when you have time. Thank you.

**Comment by ramiro050** [comment]
Can we close this, @stellaraccident @gptsarthak ?

**Comment by stellaraccident** [comment]
Yep. Looks fixed
