### ISSUE TITLE
How can I get LLVM IR after we compile torchscript

### ISSUE THREAD

**Issue by qzylalala** [llvm/torch-mlir#2533]
Hi, I'm new to torch-mlir and not that familia with mlir ecosystem.
I see, after we compile models from torch like below, we can get mlir file:
```python
module = torch_mlir.compile(resnet18, torch.ones(1, 3, 224, 224), output_type="linalg-on-tensors")
# or we convert to tosa
# module = torch_mlir.compile(resnet18, torch.ones(1, 3, 224, 224), output_type="tosa")
```
After this step, how can I get LLVM IR, so that I can use something like mlir-cpu-runner to run the mlir file.

Waiting for your reply.
Best wishes!

**Comment by qingyunqu** [comment]
You should run pipeline like https://github.com/llvm/torch-mlir/blob/main/projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py#L124 does.
BTW, torch-mlir does not target to generate well-optimized kernel. torch-mlir targets to provide conversion from torch to backend dialects.

**Comment by qzylalala** [comment]
> You should run pipeline like https://github.com/llvm/torch-mlir/blob/main/projects/pt1/python/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py#L124 does. BTW, torch-mlir does not target to generate well-optimized kernel. torch-mlir targets to provide conversion from torch to backend dialects.

Wow, thanks for your reply, it helps a lot!
