### ISSUE TITLE
[RFC] Adding Support for Adaptive Pooling Ops

### ISSUE THREAD

**Issue by zjgarvey** [llvm/torch-mlir#2578]
**Issue Context:** 

The current decomposition of AtenAdaptiveAvgPool(1/2)d to AtenAvgPool (near line 3967 of [DecomposeComplexOps.cpp](https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp)) only supports degenerate cases. The general case is problematic to implement with the current strategy, since the AtenAvgPool lowering, to linalg::PoolingNch(w)SumOp, does not support dynamic strides (see lines 400 and 51 of [Pooling.cpp](https://github.com/llvm/torch-mlir/blob/main/lib/Conversion/TorchToLinalg/Pooling.cpp)), which are inevitable when accepting dynamic input shapes to adaptive pooling ops. 

**My Request:** 

I am currently trying to add general support for AtenAdaptiveAvgPool(1/2/3)d and AtenAdaptiveMaxPool(1/2/3)d. Since I am new to contributing to this project, I'd like some advice on what kind of approach would be appropriate:

1. Hack-ily implement a more general decomposition of the adaptive pooling ops. This might need to be something like decomposing each element of the output tensor to some kind of Aten Average/Sum/Max op iteratively through a loop over the output shape (perhaps using AtenSliceTensorOp to access the corresponding pooling windows). I would be happy to prototype this if it seems like a reasonable approach.

2. Remove the current decompositions for AtenAdaptiveAvg, and instead directly implement lowerings of each AtenAdaptivePooling op to linalg (and/or other dialects if this is useful). 

3. Something else.

Edit: If it wasn't clear- the linalg pooling related ops, in general, do not allow dynamic strides.

**Comment by newling** [comment]
I took a look at the pytorch CPU implementation [here](https://github.com/pytorch/pytorch/blob/e360f4c6dd3f0c6a7b949a26cc3bf4fa03a6dd1b/aten/src/ATen/native/cpu/AdaptiveMaxPoolKernel.cpp#L16) to refresh my memory of what it does, and here are my thoughts... 

The pooling region size can be different for the different output pixels (pooling region determined by [start_index](https://github.com/pytorch/pytorch/blob/2efa89a388e2d6a20836655666232afa4d05a4ba/aten/src/ATen/native/AdaptivePooling.h#L21) and end_index.) For example if the output tensor has size 27 in dimension X and the input is size 10 in dimension X, the each output pixel might be the pooling of 2 or 3 pixels. 

So even if the input shape is statically known, it cannot in general be converted to a single pool op. There are cases where it can (when the input shape perfectly divides the output shape), and 2 of these have been implemented in DecomposeComplexOps.cpp (when output size is 1, and output size = input size). This could maybe be extended to other cases where input_size % output_size = 1, but that's still far from full support. 

Question: when you suggest iterating over the output elements in the decomposition, is that a loop in the IR, or a loop to generate IR? i.e. is the IR going to contain as many pool ops as there output pixels? That seems problematic, if so :D

I wonder if the pytorch CPU implementation could form the basis of a direct lowering to a linalg.generic op.

**Comment by zjgarvey** [comment]
Thanks for the reply! Yeah, the pooling is a bit awkward. In fact, the pooling strategy in the comments of the DecomposeComplexOps.cpp file is either outdated or incorrect, and even in those cases where it applies, it still wouldn't really dynamically lower to the standard linalg ops. 
 
To answer your question:

I agree that writing output-size many pooling ops directly into the IR would be ugly, but I also don't see anyone writing in an scf.for loop in the DecomposeComplexOps.cpp file either, which is kinda what I initially thought to do. Inside the scf.for loops (over the output shape), I would use something to view the appropriate window from the input tensor, do the operation there (average or max with kernel-size = window-size), then include it into a result tensor. 

My question is kinda like: At this point should I really just write a separate lowering to linalg (along the lines you were suggesting) for these ops directly? Since I'm pretty new here, I don't have a good intuition for what general strategy would be most performant and/or aesthetic.

**Comment by newling** [comment]
I'm not sure, although I also kinda think direct to linalg would be best. That said I'm not sure what it'd look like (I'm new to linalg and torch-mlir too)  as it's not just a case of choosing the reduction dimensions like the pooling ops currently implemented in linalg: https://github.com/llvm/llvm-project/blob/9824040ad56103e350e6edbd59f05c606227c2c5/mlir/include/mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.yaml#L4411

Maybe it's possible to have both -- decompose when possible, so that the optimized path can be taken for some cases, but still have a lowering to linalg when not.

**Comment by zjgarvey** [comment]
Yeah, that's a good idea. 

For now, I'll go ahead and write a lowering to linalg directly, then. If it works and everything looks nice, I'll separate the current decomposition into cases to try and use the original destination op when possible.

**Comment by zjgarvey** [comment]
Here is a rough sketch of what the linalg IR might look like for AtenAdaptiveAvgPool1dOp, with channels and batches as one dynamic dimension and an output size of 7 (specified by a test module). 

As you can see with the second linalg.generic op written here, I'm needing to access the elements of the input tensor using tensor.extract, since the access pattern to the input elements does not have constant strides. 

My questions:

1. Is the given approach reasonable? If so, I'll test the lowering and try to implement the pass. 
2. Is it reasonable to nest linalg ops? For example, one linalg op looping over the output shape, and the inner linalg op doing an average over a (prior loop determined) slice shape?
3. Is it possible to use scf loops directly when lowering torch ops?

```
func.func @forward(%arg0: tensor<?x?xf32>) -> tensor<?x7xf32> {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    // number of batches*channels
    %N = tensor.dim %arg0, %c0 : tensor<?x?xf32> 
    // length of input tensors
    %lin = tensor.dim %arg0, %c1 : tensor<?x?xf32>
    //length of output tensors
    %lout = arith.constant 7 : index 
    %Kmax = arith.ceildivsi %lin, %lout : index 
    //an empty tensor to use for iterating over each window (maximum size = lin)
    %Kiter = tensor.empty(%Kmax) : tensor<?xi1> 
    // 0 or -inf dep. on whether doing avg or max, resp.
    %buffval = arith.constant 0.0 : f32 
    //buffering the input since otherwise the output loop will try to access %arg0 out of bounds
    %buffdinput = tensor.pad %arg0 low[0,0] high[0,1] {
        ^bb0(%arg7: index, %arg8 : index):
            tensor.yield %buffval : f32
        } : tensor<?x?xf32> to tensor<?x?xf32> 
    //start index for each window: start_index(i) = (i/lout)*lin + ((i%lout)*lin)/lout = (i*lin)/lout
    %st_init = tensor.empty(%lout) : tensor<?xindex> 
    //end index for each window: end_index(i) = 1 + ((i + 1)*lin - 1)/lout
    %en_init = tensor.empty(%lout) : tensor<?xindex> 
    %st , %en = linalg.generic {
        indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>], 
        iterator_types = ["parallel"]} outs(%st_init, %en_init: tensor<? x index>, tensor<?xindex>) {
            ^bb0(%arg1 : index, %arg2 : index):
                %l = linalg.index 0 : index
                %s3 = arith.muli %l, %lin : index
                %s4 = arith.floordivsi %s3, %lout : index
                %e2 = arith.addi %l, %c1 : index
                %e3 = arith.muli %e2, %lin : index
                %e4 = arith.subi %e3, %c1 : index
                %e5 = arith.floordivsi %e4, %lout : index
                %e6 = arith.addi %c1, %e5 : index
                linalg.yield %s4, %e6 : index, index
    } -> (tensor<?xindex>, tensor<? x index>)
    %init = tensor.empty(%lin) : tensor<?x7xf32> 
    //pool op result over windows [st,en] in arg0 (in this case, does a sum pool)
    %output = linalg.generic{
        indexing_maps = [affine_map<(d0,d1,d2) -> (d1)>, affine_map<(d0,d1,d2) -> (d1)>, affine_map<(d0,d1,d2) -> (d2)>, affine_map<(d0,d1,d2) -> (d0,d1)>],
        iterator_types = ["parallel","parallel","reduction"]} ins(%st, %en, %Kiter: tensor<?xindex>, tensor<?xindex>, tensor<?xi1>) outs(%init: tensor<?x7xf32>) {
            ^bb0(%arg3 : index, %arg4 : index, %arg5 : i8, %arg6 : f32):
                %ind0 = linalg.index 0 : index
                %ind2 = linalg.index 2 : index
                %sum = arith.addi %arg3, %ind2 : index
                %inelt = tensor.extract %buffdinput [%ind0, %sum] : tensor<?x?xf32>
                %cond = arith.cmpi ult, %ind2, %arg4 : index 
                %outelt1 = arith.select %cond, %inelt, %buffval : f32
                //replace with maxf for adaptive max
                %outelt2 = arith.addf %arg6, %outelt1 : f32 
                linalg.yield %outelt2 : f32
    } -> tensor<?x7xf32>
    //for avg, need to add loop to float-divide %output, elementwise in dim 1, by (%en - %st).
    return %output : tensor<?x7xf32>
}
```

**Comment by newling** [comment]
Seems good to me. Sorry for not replying earlier, I was hoping someone with more experience would comment. Glad it's moving along nicely on https://github.com/llvm/torch-mlir/pull/2661 now!
