### ISSUE TITLE
Incomplete command to re-generate GeneratedTorchOps.td

### ISSUE THREAD

**Issue by frederik-h** [llvm/torch-mlir#2608]
The documentation in this file claims that it can be re-generated by running `python -m torch_mlir.jit_ir_importer.build_tools.torch_ods_gen`. But this does not work for me:

```
$ python -m torch_mlir.jit_ir_importer.build_tools.torch_ods_gen
usage: generate_ods [-h] --torch_ir_include_dir TORCH_IR_INCLUDE_DIR [--debug_registry_dump DEBUG_REGISTRY_DUMP] [--pytorch_op_extensions PYTORCH_OP_EXTENSIONS]
generate_ods: error: the following arguments are required: --torch_ir_include_dir
```

The script `build_tools/update_torch_ods.sh` seems to perform the invocation correctly. It is also recommended in the [docs](https://github.com/llvm/torch-mlir/blob/main/docs/Torch-ops-E2E-implementation.md#step-2-update-ods).

I suppose it makes sense to recommend the use of the script in GeneratedTorchOps.td or could it be that it is sometimes preferable not to use the script?

**Comment by stellaraccident** [comment]
I think this is just out of date comments. Approved your patch.
