### ISSUE TITLE
Some linalg tests failing on Conv2d grouped/dilation for PyTorch nightly after LLVM bump

### ISSUE THREAD

**Issue by stellaraccident** [llvm/torch-mlir#2622]
In the LLVM bump (https://github.com/llvm/torch-mlir/pull/2619), we started seeing these three tests failing for linalg and dynamo:

```
        "Conv2dWithPaddingDilationStrideStaticModule_grouped",
        "Conv2dWithPaddingDilationStrideStaticModule_grouped_multiplier",
        "ConvolutionModule2DGroups_basic",
```

I added them to the LINALG_XFAIL_SET and TORCHDYNAMO_XFAIL_SET for PyTorch nightly (denoted by version >= 2.2.0.dev20231204). These work on stable.

These are failing with numerical issues, and I do not immediately understand how bumping the LLVM version in isolation would result in *just* the PyTorch nightly failing and not the stable. Possibly something subtly different that is sending it down a bad path. Should be triaged and fixed.

**Comment by ubfx** [comment]
Might this have to do with this PR: https://github.com/llvm/llvm-project/pull/73855 ?

I will try and submit a patch for the grouped conv2d lowering in torch-mlir.
