### ISSUE TITLE
Implement lowering of torch.aten.cosh to linalg.

### ISSUE THREAD

**Issue by godot73** [llvm/torch-mlir#2631]
torch.aten.cosh is in the [op-to-implement list](https://github.com/nod-ai/SHARK-Turbine/issues/119#issue-1971327299).

**Comment by godot73** [comment]
@vivekkhandelwal1  @frederik-h

**Comment by vivekkhandelwal1** [comment]
> @vivekkhandelwal1 @frederik-h

Hi @godot73, I didn't understand your comment.

**Comment by frederik-h** [comment]
> > @vivekkhandelwal1 @frederik-h
> 
> Hi @godot73, I didn't understand your comment.

I assume @godot73 just wanted to bring this issue to our attention.
@godot73 I would assume that the implementation of this operator should be pretty similar to what I did here https://github.com/llvm/torch-mlir/pull/2614.

**Comment by godot73** [comment]
Merged https://github.com/llvm/llvm-project/pull/75153  at llvm/llvm-project.

**Comment by godot73** [comment]
Merged https://github.com/llvm/torch-mlir/pull/2645

**Comment by godot73** [comment]
Merged the lowering implementation: https://github.com/llvm/torch-mlir/pull/2635
