### ISSUE TITLE
torch.operator "onnx.LeakyRelu"

### ISSUE THREAD

**Issue by muwys518** [llvm/torch-mlir#2684]
error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %103 = torch.operator "onnx.LeakyRelu"

**Comment by muwys518** [comment]
onnx.Clip

**Comment by vivekkhandelwal1** [comment]
Leakyrelu and clip both are added.

**Comment by vivekkhandelwal1** [comment]
> c1.mlir:112:12: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal %109 = torch.operator "onnx.Clip"(%106, %107, %108) : (!torch.vtensor<[1,32,112,112],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32> ^ c1.mlir:112:12: note: see current operation: %123 = "torch.operator"(%120, %121, %122) <{name = "onnx.Clip"}> : (!torch.vtensor<[1,32,112,112],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32>
> 
> ```
> import-onnx  support on onnx.Clip but --convert-torch-onnx-to-torch  failed
> ```

The message that you posted doesn't make things clear. Please add a descriptive comment. Also, for the error you shared, I tried to lower the op and it worked. Here's the Onnx IR:
```
func.func @test_clip_example(%arg0: !torch.vtensor<[1,32,112,112],f32>, %arg1: !torch.vtensor<[],f32>, %arg2: !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32> attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 13 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
  %0 = torch.operator "onnx.Clip"(%arg0, %arg1, %arg2) : (!torch.vtensor<[1,32,112,112],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32>
  return %0 : !torch.vtensor<[1,32,112,112],f32>
}

Here's the converted IR:
```
  func.func @test_clip_example(%arg0: !torch.vtensor<[1,32,112,112],f32>, %arg1: !torch.vtensor<[],f32>, %arg2: !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32> attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 13 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
    %0 = torch.aten.clamp.Tensor %arg0, %arg1, %arg2 : !torch.vtensor<[1,32,112,112],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],f32> -> !torch.vtensor<[1,32,112,112],f32>
    return %0 : !torch.vtensor<[1,32,112,112],f32>
  }
```

I'm not sure why you're getting the error.

**Comment by muwys518** [comment]
> > c1.mlir:112:12: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal %109 = torch.operator "onnx.Clip"(%106, %107, %108) : (!torch.vtensor<[1,32,112,112],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32> ^ c1.mlir:112:12: note: see current operation: %123 = "torch.operator"(%120, %121, %122) <{name = "onnx.Clip"}> : (!torch.vtensor<[1,32,112,112],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32>
> > ```
> > import-onnx  support on onnx.Clip but --convert-torch-onnx-to-torch  failed
> > ```
> 
> The message that you posted doesn't make things clear. Please add a descriptive comment. Also, for the error you shared, I tried to lower the op and it worked. Here's the Onnx IR:
> 
> ```
> func.func @test_clip_example(%arg0: !torch.vtensor<[1,32,112,112],f32>, %arg1: !torch.vtensor<[],f32>, %arg2: !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32> attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 13 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
>   %0 = torch.operator "onnx.Clip"(%arg0, %arg1, %arg2) : (!torch.vtensor<[1,32,112,112],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32>
>   return %0 : !torch.vtensor<[1,32,112,112],f32>
> }
> ```
> 
> Here's the converted IR:
> 
> ```
>   func.func @test_clip_example(%arg0: !torch.vtensor<[1,32,112,112],f32>, %arg1: !torch.vtensor<[],f32>, %arg2: !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32> attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 13 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
>     %0 = torch.aten.clamp.Tensor %arg0, %arg1, %arg2 : !torch.vtensor<[1,32,112,112],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],f32> -> !torch.vtensor<[1,32,112,112],f32>
>     return %0 : !torch.vtensor<[1,32,112,112],f32>
>   }
> ```
> 
> I'm not sure why you're getting the error.
My order of operations is
```shell
  torch-mlir-import-onnx model.onnx -o c1.mlir
  torch-mlir-opt --convert-torch-onnx-to-torch  c1.mlir -o c2.mlir
``` 
then I get 
```shell
c1_2.mlir:112:12: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %109 = torch.operator "onnx.Clip"(%106, %107, %108) : (!torch.vtensor<[1,32,112,112],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32>
           ^
c1_2.mlir:112:12: note: see current operation: %123 = "torch.operator"(%120, %121, %122) <{name = "onnx.Clip"}> : (!torch.vtensor<[1,32,112,112],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],f32>) -> !torch.vtensor<[1,32,112,112],f32>
```

**Comment by vivekkhandelwal1** [comment]
> ```shell
> torch.vtensor<[1,32,112,11
> ```

How and from where are you getting this model.onnx?

**Comment by muwys518** [comment]
> > ```shell
> > torch.vtensor<[1,32,112,11
> > ```
> 
> How and from where are you getting this model.onnx?

mobilenetv2
https://s3.amazonaws.com/onnx-model-zoo/mobilenet/mobilenetv2-1.0/mobilenetv2-1.0.onnx

**Comment by muwys518** [comment]
> > > ```shell
> > > torch.vtensor<[1,32,112,11
> > > ```
> > 
> > 
> > How and from where are you getting this model.onnx?
> 
> mobilenetv2 https://s3.amazonaws.com/onnx-model-zoo/mobilenet/mobilenetv2-1.0/mobilenetv2-1.0.onnx

  torch-mlir-import-onnx efficientNet.onnx -o c1.mlir
  torch-mlir-opt --convert-torch-onnx-to-torch  c1.mlir -o c2.mlir
see error，model is efficientNet.onnx
