### ISSUE TITLE
ONNX Gemm and LeakyRelu have wrong from version

### ISSUE THREAD

**Issue by stellaraccident** [llvm/torch-mlir#2700]
Both of these can be `1`, not the latest version. Figuring out the version to set the pattern to requires some judgment. In this case, I consulted these docs:

* https://onnx.ai/onnx/operators/text_diff_Gemm_1_13.html : Shows that there is nothing that changed in the op that the pattern can't handle as-is.
* https://onnx.ai/onnx/operators/text_diff_LeakyRelu_1_16.html : Just some commenting and an added dtype

(found when running some stuff in the test suite)

**Comment by renxida** [comment]
On it!
