### ISSUE TITLE
Importing llama2 ONNX model into torch-mlir generates invalid MLIR

### ISSUE THREAD

**Issue by kumardeepakamd** [llvm/torch-mlir#2765]
Issue: func.func @<>() in imported torch onnx MLIR

Have ability to get llama2 model. I do following, but you can follow your own way that works.
pip install huggingface-cli huggingface-hub
Run huggingface-cli login and enter your HF token
Login to a machine with NVIDIA GPU and latest drivers.
#Set Hugging Face Home, an example below, change path to your own
export HF_HOME=<your path with enough disk space>/HF_HOME
Save following file as model.py
```
from transformers import LlamaForCausalLM, LlamaTokenizer
import torch

class optModel(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.model = LlamaForCausalLM.from_pretrained(
            "meta-llama/Llama-2-7b-hf")
        self.model.eval()

    def forward(self, tokens):
        attention_mask = torch.ones(tokens.shape, dtype=torch.long)
        return self.model.forward(input_ids=tokens, attention_mask=attention_mask)

tokenizer = LlamaTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf")
test_input = tokenizer.encode("The Manhattan bridge", return_tensors="pt")

model = optModel()
onnx_program = torch.onnx.export(model, test_input, "llama-7b.onnx")
```
The last line export ONNX mode, in case you use a different script, stick in last line to your setup.

run: 'python ./model.py'
run: 'python -m torch_mlir.tools.import_onnx llama-7b.onnx -o llama-7b.torch-onnx.mlir'
Examine (head llama-7b.torch-onnx.mlir) you will see that mlir has func.func @<>() and body of the function is missing.

**Comment by daveliddell** [comment]
Hi @vivekkhandelwal1 , I have a fix for this, working on getting into a PR now

**Comment by kumardeepakamd** [comment]
@vivekkhandelwal1 assigning it back to you for you to fix the crash in torch MLIR, use Dave's PR of course to be able to get to crash stage.

**Comment by vivekkhandelwal1** [comment]
> @vivekkhandelwal1 assigning it back to you for you to fix the crash in torch MLIR, use Dave's PR of course to be able to get to crash stage.

Hi @kumardeepakamd, this issue is fixed by: https://github.com/llvm/torch-mlir/pull/2803.

**Comment by vivekkhandelwal1** [comment]
Closing this issue since the PR is merged.

**Comment by daveliddell** [comment]
@kumardeepakamd Do I need to reopen?

**Comment by kumardeepakamd** [comment]
reopend

**Comment by daveliddell** [comment]
Fixed merged!
