### ISSUE TITLE
Please update projects/examples/pt1

### ISSUE THREAD

**Issue by CPA872** [llvm/torch-mlir#2923]
Hi, the default tutorials in projects/examples/pt1 do not work. If we install by the recommended method in the Readme, It cannot import `torchscript` from `torch_mlir`. Please update to reflect the current repo.

**Comment by DarkenStar** [comment]
I can not import fx
`File "/code/torch-mlir/test/python/fx_importer/basic_test.py", line 16, in <module>
    from torch_mlir import fx
ImportError: cannot import name 'fx' from 'torch_mlir'`

**Comment by marbre** [comment]
I tested the instructions given in [docs/development.md#testing-mlir-output-in-various-dialects](https://github.com/llvm/torch-mlir/blob/main/docs/development.md#testing-mlir-output-in-various-dialects). With a complete build of torch-mlir and the `PYTHONPATH` correctly set the instructions work and seem up-to-date.

Feel free to re-open if you're still facing issues!
