### ISSUE TITLE
Question about RefinePublicReturnPass

### ISSUE THREAD

**Issue by hunbssfy** [llvm/torch-mlir#295]
This pass is fairly simple: it gives `return` ops in public functions a refined type and changes its non-value semantic tensor operands to value semantic tensors.

My question is about pass descriptions in the table gen file:
it says:

>     This pass effectively encodes an assumption by the pass pipeline author that
>     the public calling convention of the module can have its types refined,
>     without causing ABI mismatches.

Why this change doesn't cause ABI mismatches? it also says:

>     This is frequently true -- for example, in
>     many systems, `!torch.vtensor<[?,?],f32>`, `!torch.vtensor<[3,3],f32>` and
>     `!torch.vtensor` are all the same data structure on calling
>     convention boundaries.

Is there an example of this kind of ABI definition?

**Comment by silvasean** [comment]
In most systems, `!torch.vtensor<[?,?],f32>`, `!torch.vtensor<[3,3],f32>` and
`!torch.vtensor` are all the same data structure on calling
convention boundaries. For example, in IREE, they are all passed as hal.buffer_view. That's why it's ok to refine the static type, since it doesn't cause ABI mismatches.

**Comment by hunbssfy** [comment]
And the caller and callee will produce the same ABI even if they have different `vtensor` representation (say caller has shape/type information but callee doesn't). `vtensor` will always be lowered to `hal.buffer_view` and because the argument type isn't changed, the ABI matches. Is this logic right?

**Comment by hunbssfy** [comment]
Is it possible that there could be some kind of Attribute when altered, could change the result of the function signature and cause ABI mismatch?

**Comment by silvasean** [comment]
> And the caller and callee will produce the same ABI even if they have different `vtensor` representation (say caller has shape/type information but callee doesn't). `vtensor` will always be lowered to `hal.buffer_view` and because the argument type isn't changed, the ABI matches. Is this logic right?

Correct.



> Is it possible that there could be some kind of Attribute when altered, could change the result of the function signature and cause ABI mismatch?

It is possible. I try to avoid function attributes (for `std.func`). If we actually need something that is semantically load-bearing it is better to define `torch.func` that knows about it rather than attaching a random attribute to `std.func`.
