### ISSUE TITLE
Can't pass unit test and Python regression tests 

### ISSUE THREAD

**Issue by DarkenStar** [llvm/torch-mlir#3050]
I followed the [https://github.com/llvm/torch-mlir/blob/main/docs/development.md](url) to build the project (in tree), but when I run unit test the command
`cmake --build build --target check-torch-mlir`

errors occured like
`********************
********************
Failed Tests (7):
  TORCH_MLIR :: python/compile.py
  TORCH_MLIR :: python/fx_importer/basic_test.py
  TORCH_MLIR :: python/fx_importer/sparse_test.py
  TORCH_MLIR :: python/fx_importer/special_forms_test.py
  TORCH_MLIR :: python/fx_importer/v2.3/mutation_import.py
  TORCH_MLIR :: python/onnx_importer/command_line_test.py
  TORCH_MLIR :: python/onnx_importer/import_smoke_test.py

Testing Time: 9.53s

Total Discovered Tests: 92
  Passed: 85 (92.39%)
  Failed:  7 (7.61%)
FAILED: tools/torch-mlir/test/CMakeFiles/check-torch-mlir /code/torch-mlir/build/tools/torch-mlir/test/CMakeFiles/check-torch-mlir 
cd /code/torch-mlir/build/tools/torch-mlir/test && /root/miniconda3/envs/torch-mlir/bin/python3.11 /code/torch-mlir/build/./bin/llvm-lit -sv /code/torch-mlir/build/tools/torch-mlir/test
ninja: build stopped: subcommand failed.`

For the python regression test
`cmake --build build --target check-torch-mlir-python`

errors occured like
`********************
********************
Failed Tests (15):
  TORCH_MLIR_PYTHON :: compile_api/already_scripted.py
  TORCH_MLIR_PYTHON :: compile_api/already_traced.py
  TORCH_MLIR_PYTHON :: compile_api/backend_legal_ops.py
  TORCH_MLIR_PYTHON :: compile_api/basic.py
  TORCH_MLIR_PYTHON :: compile_api/make_fx.py
  TORCH_MLIR_PYTHON :: compile_api/multiple_methods.py
  TORCH_MLIR_PYTHON :: compile_api/output_type_spec.py
  TORCH_MLIR_PYTHON :: compile_api/tracing.py
  TORCH_MLIR_PYTHON :: dynamo_fx_importer/basic.py
  TORCH_MLIR_PYTHON :: torchscript_e2e_test/basic.py
  TORCH_MLIR_PYTHON :: torchscript_e2e_test/compilation_failure.py
  TORCH_MLIR_PYTHON :: torchscript_e2e_test/error_reports.py
  TORCH_MLIR_PYTHON :: torchscript_e2e_test/non_tensor_values.py
  TORCH_MLIR_PYTHON :: torchscript_e2e_test/runtime_failure.py
  TORCH_MLIR_PYTHON :: torchscript_e2e_test/submodule.py

Testing Time: 2.31s

Total Discovered Tests: 17
  Passed:  2 (11.76%)
  Failed: 15 (88.24%)
FAILED: tools/torch-mlir/projects/pt1/python/test/CMakeFiles/check-torch-mlir-python /code/torch-mlir/build/tools/torch-mlir/projects/pt1/python/test/CMakeFiles/check-torch-mlir-python 
cd /code/torch-mlir/build/tools/torch-mlir/projects/pt1/python/test && /root/miniconda3/envs/torch-mlir/bin/python3.11 /code/torch-mlir/build/./bin/llvm-lit -sv /code/torch-mlir/build/tools/torch-mlir/projects/pt1/python/test
ninja: build stopped: subcommand failed.`

And when I test the MLIR output to torch dialect by
`export PYTHONPATH=`pwd`/build/tools/torch-mlir/python_packages/torch_mlir:`pwd`/test/python/fx_importer
python test/python/fx_importer/basic_test.py`

errors occured like
`traceback (most recent call last):
  File "/code/torch-mlir/test/python/fx_importer/basic_test.py", line 16, in <module>
    from torch_mlir import fx
ImportError: cannot import name 'fx' from 'torch_mlir' (/root/miniconda3/envs/torch-mlir/lib/python3.11/site-packages/torch_mlir/__init__.py)`

What should I do? Thanks a lot!

**Comment by penguin-wwy** [comment]
Do you have an old version of torch_mlir in your Python environment `/root/miniconda3/envs/torch-mlir/lib/python3.11/site-packages`?

I think, `fx` should import from `/build/tools/torch-mlir/python_packages/torch_mlir`

**Comment by DarkenStar** [comment]
I once deletet the files and  

> Do you have an old version of torch_mlir in your Python environment `/root/miniconda3/envs/torch-mlir/lib/python3.11/site-packages`?
> 
> I think, `torch_mlir.fx` should import from `/build/tools/torch-mlir/python_packages/torch_mlir`


I once deleted the file and git again yesterday, I create a new environment and try again. Thanks s a lot!

**Comment by DarkenStar** [comment]
It works thanks！
