### ISSUE TITLE
[RFC] Mixed Quantized Types in Matmul Not Supported

### ISSUE THREAD

**Issue by zjgarvey** [llvm/torch-mlir#3090]
Hi, 

I'd like to support any quint8-qint8-argument combinations in matmul, and would like some advice on what the best way to implement this would be. Here are some ideas:

1. Write a generic op in the matmul conversion in the case where any quantized types are unsigned (this would be relatively easy).
2. Write named ops for each combination of signed-ness (seems somewhat clunky, but maybe there is a better route through named ops).

Related: [PR#3089](https://github.com/llvm/torch-mlir/pull/3089)

Using the changes made in the above PR, running

```
./projects/pt1/tools/e2e_test.sh -f QuantizedSingleLayer_basic -v -c onnx
```

yields an error:

```
python exception: Failure while executing pass pipeline:
        error: "/layers/0/Gemm": failed to legalize operation 'torch.aten.mm' that was explicitly marked illegal
        note: "/layers/0/Gemm": see current operation: %52 = "torch.aten.mm"(%32, %51) : (!torch.vtensor<[1,16],!torch.quint8>, !torch.vtensor<[16,8],!torch.qint8>) -> !torch.vtensor<[1,8],!torch.qint32>
```

which is due to the match failure:

```
  * Pattern : 'torch.aten.mm -> ()' {
Trying to match "(anonymous namespace)::ConvertAtenMmOp"
    ** Failure : unsupported: aten.mm with different input element types
"(anonymous namespace)::ConvertAtenMmOp" result 0
  } -> FAILURE : pattern failed to match
```

**Comment by zjgarvey** [comment]
Also for reference:

[named_ops.py](https://github.com/llvm/llvm-project/blob/d83271b093ec206c2f47a9c636a5727cf63cad5e/mlir/python/mlir/dialects/linalg/opdsl/ops/core_named_ops.py#L278).

**Comment by MaheshRavishankar** [comment]
Is the issue that there is no Linalg op to lower to... if you were going to lower to a linalg.generic directly what would that look like?

**Comment by zjgarvey** [comment]
> Is the issue that there is no Linalg op to lower to... if you were going to lower to a linalg.generic directly what would that look like?

I was originally going to figure out how to convert i8's that are treated as unsigned in arith to i32's that are treated as signed and just include that in the payload. The rest would be identical to the payload for linalg::quantized_matmul. 

I might instead just write a higher level pass (e.g. in FuseQuantizedOps.cpp) to change quint8 quantization to an equivalent qint8 quantization for matmul.

**Comment by zjgarvey** [comment]
Oh and the zeropoint in the generic would have to be shifted as well, I suppose.

**Comment by zjgarvey** [comment]
Evidently arith::extsi will convert an unsigned i8 to a signed i32, so I think everything is fine. See #3122
