### ISSUE TITLE
Regression in onnx.PRelu

### ISSUE THREAD

**Issue by stellaraccident** [llvm/torch-mlir#3092]
While integrating to torch-mlir HEAD, IREE's test suite caught a regression:

https://github.com/openxla/iree/actions/runs/8515624855/job/23323678533?pr=16940

```
________ IREE compile and run: test_prelu_broadcast::cpu_llvm_sync_test ________
[gw62] linux -- Python 3.11.8 /home/runner/work/iree/iree/venv/bin/python
Error invoking iree-compile
Error code: 1
Stderr diagnostics:
model.mlir:4:10: error: failed to legalize operation 'torch.aten.mul.Tensor' that was explicitly marked illegal
    %0 = torch.operator "onnx.PRelu"(%arg0, %arg1) : (!torch.vtensor<[3,4,5],f32>, !torch.vtensor<[5],f32>) -> !torch.vtensor<[3,4,5],f32> 
         ^
model.mlir:4:10: note: see current operation: %1 = "torch.aten.mul.Tensor"(%arg0, %arg1) : (!torch.vtensor<[3,4,5],f32>, !torch.vtensor<[5],f32>) -> !torch.vtensor


Invoked with:
  cd /home/runner/work/iree/iree/SHARK-TestSuite/iree_tests/onnx/node/generated/test_prelu_broadcast && iree-compile model.mlir --iree-hal-target-backends=llvm-cpu -o model_cpu_llvm_sync_test.vmfb
```

Can someone please have a look?

**Comment by zjgarvey** [comment]
Might be due to changes in [#3069](https://github.com/llvm/torch-mlir/commit/40008b025a40e8bab1f362edc1ed0ee551b5e7a3) from a few days ago. I'll take a look.

**Comment by zjgarvey** [comment]
I think I have a fix, but I need to figure out how to test locally. For reference: [branch](https://github.com/zjgarvey/torch-mlir/tree/prelufix)

**Comment by zjgarvey** [comment]
So, it might be the case that the pass pipeline used in the iree tests does not include shape and dtype calculations. The result type of the mul.Tensor op should have been inferred before reaching this error. 

Running the following on the mlir file in the corresponding test suite folder for prelu_broadcast:

```
torch-mlir-opt --convert-torch-onnx-to-torch --torch-decompose-complex-ops --torch-backend-to-linalg-on-tensors-backend-pipeline
```

will reproduce the error; however,

```
torch-mlir-opt --convert-torch-onnx-to-torch --torch-lower-to-backend-contract --torch-backend-to-linalg-on-tensors-backend-pipeline
```

will generate valid linalg ir. 

I'm happy to specify the shape and dtype for the decomposition, as in the branch I linked, but it might be a good idea to have a more robust pass pipeline for the regression tests. 

For ease of reproduction: here is the MLIR file for this test:

```MLIR
module {
  func.func @test_prelu_broadcast(%arg0: !torch.vtensor<[3,4,5],f32>, %arg1: !torch.vtensor<[5],f32>) -> !torch.vtensor<[3,4,5],f32> attributes {torch.onnx_meta.ir_version = 8 : si64, torch.onnx_meta.opset_version = 17 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
    %none = torch.constant.none
    %0 = torch.operator "onnx.PRelu"(%arg0, %arg1) : (!torch.vtensor<[3,4,5],f32>, !torch.vtensor<[5],f32>) -> !torch.vtensor<[3,4,5],f32> 
    return %0 : !torch.vtensor<[3,4,5],f32>
  }
}
```

and the terminal outputs of the two pipelines:

```
(mlir.venv) zjgar@AUS-L-ZAGARVEY:~/code/torch-mlir$ torch-mlir-opt --convert-torch-onnx-to-torch --torch-decompose-complex-ops --torch-backend-to-linalg-on-tensors-backend-pipeline prelu_broadcast.onnx.torch.mlir 
prelu_broadcast.onnx.torch.mlir:4:10: error: failed to legalize operation 'torch.aten.mul.Tensor' that was explicitly marked illegal
    %0 = torch.operator "onnx.PRelu"(%arg0, %arg1) : (!torch.vtensor<[3,4,5],f32>, !torch.vtensor<[5],f32>) -> !torch.vtensor<[3,4,5],f32> 
         ^
prelu_broadcast.onnx.torch.mlir:4:10: note: see current operation: %1 = "torch.aten.mul.Tensor"(%arg0, %arg1) : (!torch.vtensor<[3,4,5],f32>, !torch.vtensor<[5],f32>) -> !torch.vtensor
(mlir.venv) zjgar@AUS-L-ZAGARVEY:~/code/torch-mlir$ torch-mlir-opt --convert-torch-onnx-to-torch --torch-lower-to-backend-contract --torch-backend-to-linalg-on-tensors-backend-pipeline prelu_broadcast.onnx.torch.mlir 
#map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
#map1 = affine_map<(d0, d1, d2) -> (d2)>
module {
  ml_program.global private mutable @global_seed(dense<0> : tensor<i64>) : tensor<i64>
  func.func @test_prelu_broadcast(%arg0: tensor<3x4x5xf32>, %arg1: tensor<5xf32>) -> tensor<3x4x5xf32> {
    %cst = arith.constant 0.000000e+00 : f32
    %0 = tensor.empty() : tensor<3x4x5xf32>
    %1 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%arg0, %arg1 : tensor<3x4x5xf32>, tensor<5xf32>) outs(%0 : tensor<3x4x5xf32>) {
    ^bb0(%in: f32, %in_0: f32, %out: f32):
      %5 = arith.mulf %in, %in_0 : f32
      linalg.yield %5 : f32
    } -> tensor<3x4x5xf32>
    %2 = tensor.empty() : tensor<3x4x5xi1>
    %3 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%arg0 : tensor<3x4x5xf32>) outs(%2 : tensor<3x4x5xi1>) {
    ^bb0(%in: f32, %out: i1):
      %5 = arith.cmpf ult, %in, %cst : f32
      linalg.yield %5 : i1
    } -> tensor<3x4x5xi1>
    %4 = linalg.generic {indexing_maps = [#map, #map, #map, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%3, %1, %arg0 : tensor<3x4x5xi1>, tensor<3x4x5xf32>, tensor<3x4x5xf32>) outs(%0 : tensor<3x4x5xf32>) {
    ^bb0(%in: i1, %in_0: f32, %in_1: f32, %out: f32):
      %5 = arith.select %in, %in_0, %in_1 : f32
      linalg.yield %5 : f32
    } -> tensor<3x4x5xf32>
    return %4 : tensor<3x4x5xf32>
  }
}
```

**Comment by ScottTodd** [comment]
> but it might be a good idea to have a more robust pass pipeline for the regression tests.

This is the pipeline IREE uses: https://github.com/openxla/iree/blob/6ef1cfe4fe47dadacca62b5bfc96ac5a3a9c4dbf/compiler/plugins/input/Torch/InputConversion/Passes.cpp#L29-L84

The tests just run the user-facing `iree-compile model.mlir --iree-hal-target-backends=llvm-cpu -o model_cpu_llvm_sync_test.vmfb`, not an explicit list of passes like those `torch-mlir-opt` commands. Looks like we could sync that pipeline with https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/TorchConversion/Transforms/Passes.cpp

**Comment by ScottTodd** [comment]
> How is the model.mlir getting converted from torch-onnx to torch with iree?

`model.onnx` is going through this code to get converted into `model.mlir`: https://github.com/nod-ai/SHARK-TestSuite/blob/9464d503ddf37e658cf267254ac65a3d1f143344/iree_tests/onnx/import_tests.py#L66-L157 . That's mostly `iree-import-onnx model.onnx -o model.mlir`, which runs this code: https://github.com/openxla/iree/blob/main/compiler/bindings/python/iree/compiler/tools/import_onnx/__main__.py (roughly equivalent to https://github.com/llvm/torch-mlir/blob/main/python/torch_mlir/tools/import_onnx/__main__.py)

Once in MLIR, the file goes through the pipeline I linked above (iree/compiler/plugins/input/Torch/)

Does that answer your question?

**Comment by zjgarvey** [comment]
> > How is the model.mlir getting converted from torch-onnx to torch with iree?
> 
> `model.onnx` is going through this code to get converted into `model.mlir`: https://github.com/nod-ai/SHARK-TestSuite/blob/9464d503ddf37e658cf267254ac65a3d1f143344/iree_tests/onnx/import_tests.py#L66-L157 . That's mostly `iree-import-onnx model.onnx -o model.mlir`, which runs this code: https://github.com/openxla/iree/blob/main/compiler/bindings/python/iree/compiler/tools/import_onnx/__main__.py (roughly equivalent to https://github.com/llvm/torch-mlir/blob/main/python/torch_mlir/tools/import_onnx/__main__.py)
> 
> Once in MLIR, the file goes through the pipeline I linked above (iree/compiler/plugins/input/Torch/)
> 
> Does that answer your question?

It might. I'm just not sure where the --convert-torch-onnx-to-torch is coming in, so I'll take a look. For now, I'm just going to put a PR up for explicitly specifying the shape and dtypes, and I'd like to look into the pass pipeline structure a bit more later on. 

In the meantime, I would like to double check that this fix works. Is there an efficient way to build IREE with a local version of torch-mlir? Or should I just run the relevant passes with torch-mlir and then compile from linalg with IREE?

**Comment by ScottTodd** [comment]
> It might. I'm just not sure where the --convert-torch-onnx-to-torch is coming in

Ah. Here: https://github.com/openxla/iree/blob/6ef1cfe4fe47dadacca62b5bfc96ac5a3a9c4dbf/compiler/plugins/input/Torch/PluginRegistration.cpp#L58-L80

> In the meantime, I would like to double check that this fix works. Is there an efficient way to build IREE with a local version of torch-mlir? Or should I just run the relevant passes with torch-mlir and then compile from linalg with IREE?

You can set IREE's torch-mlir submodule to a commit of your choosing. There are various git workflows for that. Stella uses worktrees. I typically use git remotes (push to github from one folder, pull from github in another -- local remotes are possible too).
