### ISSUE TITLE
buildAndTest.yml lacking trigger causes a bunch of notifications

### ISSUE THREAD

**Issue by renxida** [llvm/torch-mlir#3144]
Looks like it's caused by all the triggers being commented out in
`.github/workflows/buildAndTest.yml`

```yaml
on:
  # pull_request:
  #   branches: [main]
  # push:
  #   branches: [main]
  # workflow_dispatch:
```

![image](https://github.com/llvm/torch-mlir/assets/10362952/ee975cc5-26d1-468d-b11f-d136d5181485)

@stellaraccident because ci

**Comment by stellaraccident** [comment]
Hmm. If you see a way to fix it, go for it.
