### ISSUE TITLE
Strange issue related to `pyproject.toml` when building release wheels

### ISSUE THREAD

**Issue by sjain-stanford** [llvm/torch-mlir#3258]
Hitting this strange error when building release wheels ([GHA](https://github.com/llvm/torch-mlir-release/actions/runs/8867130596/job/24345347030)): 
```
    File "/tmp/pip-build-env-j1c2adup/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-j1c2adup/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line [230](https://github.com/llvm/torch-mlir-release/actions/runs/8867130596/job/24345347030#step:4:231), in <module>
  ModuleNotFoundError: No module named 'torch'
```

Bisected it to https://github.com/llvm/torch-mlir/pull/3200, specifically seems related to the recently added `pyproject.toml`:
```
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py38']
```

I'm not too familiar with the setup here to know how exactly to adapt the setup.py / build_linux_packages.sh to this change. @stellaraccident would you know?

Backtrace:
```
Collecting setuptools
    Downloading setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
  Collecting wheel
    Downloading wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
  Downloading setuptools-69.5.1-py3-none-any.whl (894 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 894.6/894.6 kB 22.0 MB/s eta 0:00:00
  Downloading wheel-0.43.0-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 21.6 MB/s eta 0:00:00
  Installing collected packages: wheel, setuptools
  Successfully installed setuptools-69.5.1 wheel-0.43.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "/opt/python/cp311-cp311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/python/cp311-cp311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/python/cp311-cp311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-j1c2adup/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-j1c2adup/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-j1c2adup/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line [230](https://github.com/llvm/torch-mlir-release/actions/runs/8867130596/job/24345347030#step:4:231), in <module>
  ModuleNotFoundError: No module named 'torch'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```

**Comment by sjain-stanford** [comment]
This seems related: https://github.com/pypa/pip/issues/8437#issuecomment-649880505

**Comment by stellaraccident** [comment]
I was wondering if that may catch us out. setuptools works differently based on whether under the supervision of the pyproject.toml build system (new way) or loose invocation of setup.py old way. When configured to use the "setuptools" build system via pyproject.toml, it builds in a dedicated venv-like thing that requires its dependencies *to run setup.py* be explicitly declared vs just inherited from the environment. See, for example: https://github.com/iree-org/iree/blob/main/runtime/pyproject.toml

That's usually basic build system level stuff vs anything too extreme, but the way we are depending on binary torch packages means that we would need to list torch there and arrange to get the right one. I'd rather not fix this if we can avoid it (vs just continuing to move to a world where the Python wheels don't have a binary dependency on torch).

Some possible ways out:

* Remove the [build-system] section entirely.
* Invoke `pip wheel` with `--no-build-isolation` to disable this isolation.
* Delete pyproject.toml entirely and find another way to configure black.

**Comment by stellaraccident** [comment]
Reading a few more threads, it sounds like pip builds with `--no-build-isolation` gets us back to normal.

**Comment by sjain-stanford** [comment]
> I'd rather not fix this if we can avoid it 

Agree, switching to pyproject.toml for building torch-mlir wheels seems like something we can defer for now until there's a strong need.

>  it sounds like pip builds with --no-build-isolation gets us back to normal.

This addresses the issue, thanks! PR: https://github.com/llvm/torch-mlir/pull/3266

The first option (`Remove the [build-system] section entirely.`) didn't seem to resolve it, but removing `pyproject.toml` entirely did help. In the past I've used black using `setup.cfg`, which might be an alternative here, but since the `-no-build-isolation` seems to workaround this, I'm okay leaving this as such for now, until we encounter more pain. @stellaraccident LMK if you disagree.
