### ISSUE TITLE
Update version pin to onnx 1.16

### ISSUE THREAD

**Issue by stellaraccident** [llvm/torch-mlir#3310]
onnx 1.16 includes support for Python 3.12. We should upgrade. Based on a user report, there may need to be some cleanup.

**Comment by zjgarvey** [comment]
Just to verify, you would like me to

1. pin onnx==1.16.0 in test-requirements.txt
2. check for e2e test regressions with config onnx and fix them
3. setup building nightly python wheels for python version 3.12
4. anything else?

**Comment by stellaraccident** [comment]
That's it.

**Comment by zjgarvey** [comment]
Sounds good. Thanks.

**Comment by zjgarvey** [comment]
Closing since we updated to 1.16.1.
