### ISSUE TITLE
[onnx] Attempting to lower onnx mlir with elided attributes causes crash

### ISSUE THREAD

**Issue by renxida** [llvm/torch-mlir#3394]
Initial repro with big model ir: https://asciinema.org/a/VczS2zrlf7qBm1TDdxgZDrd6q

This is caused by having something like 
```
    %2205 = torch.operator "onnx.Constant"() {torch.onnx.value = dense_resource<__1445> : tensor<f32>} : () -> !torch.vtensor<[],f32> 
```

in the ir, but no corresponding `_1445` in the dialect_resources section at the end of the file. This causes a null pointer exception.

Zach's solution is supposed to modify the lowering for onnx.Constant to handle null pointers by returning a ValueTensorLIteralOp with dense_resource<__elided__>, but there wasn't a way to generate a dense_resource<__elided__> (it's done in ASMPrinter).

I found [some code](https://github.com/llvm/llvm-project/blob/1e5f29af81a5f6fda308074f6345b9fba4faa71c/mlir/include/mlir/IR/DialectResourceBlobManager.h#L195) that suggests that maybe if I provided a null blob to the DenseResoruceAttribute constructor, it would give me something that would corresponds to parsing a `dense_resource<__elided__>`

```
  /// Return the blob referenced by this handle if the underlying resource has
  /// been initialized. Returns nullptr otherwise.
  AsmResourceBlob *getBlob() { return this->getResource()->getBlob(); }
  const AsmResourceBlob *getBlob() const {
    return this->getResource()->getBlob();
  }
```

**Comment by renxida** [comment]
https://gist.github.com/renxida/a54a28f04ead40bb0700581a3e6f9023

Some more notes from fumbling around tryna figure this out

**Comment by renxida** [comment]
when lowering
```mlir
func.func @test_func() -> !torch.vtensor<[1,1,384],f32> {
    %22 = torch.vtensor.literal(dense_resource<boo> : tensor<1x1x384xf32>) : !torch.vtensor<[1,1,384],f32>
    return %22 : !torch.vtensor<[1,1,384],f32>
}
```

we get
```mlir
module {
  func.func @test_func() -> !torch.vtensor<[1,1,384],f32> {
    %cst = arith.constant dense_resource<boo> : tensor<1x1x384xf32>
    %0 = torch_c.from_builtin_tensor %cst : tensor<1x1x384xf32> -> !torch.vtensor<[1,1,384],f32>
    return %0 : !torch.vtensor<[1,1,384],f32>
  }
}
```

Which means that there's definitely a way to just represent a DenseElementsAttr with a string to replace the contents of the dense resource. All I have to do now is to find it. I think it's accessed with `DenseResourceElementsAttr.getRawHandle()`. So I just need to figure out a way to generate it.

**Comment by renxida** [comment]
[this](https://github.com/renxida/torch-mlir/blob/848788c6913659ed4efeb6dc3f28a8a9e96b3cd8/lib/Conversion/TorchToArith/TorchToArith.cpp#L198) is where the magic happens
  ```cpp
        rewriter.replaceOpWithNewOp<arith::ConstantOp>(
              op, DenseResourceElementsAttr::get(shapedType,
                                                 elements.getRawHandle()));
```

just need to do something like this, except we replace the `elements.getRawHandle` with some code that gives a handle to a raw blob.

**Comment by renxida** [comment]
we need a DenseResourceElementsHandle, which is actually defined as
`using DenseResourceElementsHandle = DialectResourceBlobHandle<BuiltinDialect>;`

**Comment by renxida** [comment]
Looking at how DenseResourceElements are parsed.

**Comment by renxida** [comment]
Looks like this would work if i put in a
```
DenseResourceElementsAttr::get(shapedType,
                                                 elements.getRawHandle()
```
where the RawHandle is not a nullpointer but it points to a null blob.

**Comment by zjgarvey** [comment]
Closing since PR was merged. Thanks, @renxida
