### ISSUE TITLE
Re-enable the disabled sparse tests due to roll PyTorch

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#3418]
Some of the sparse tensor tests have been disabled https://github.com/llvm/torch-mlir/pull/3340 in order to get the Roll PyTorch done. It would be better if we can work on the actual issues related to these tests and get them re-enabled.

CC: @stellaraccident @aartbik

**Comment by aartbik** [comment]
Note that since there was some obvious confusion on this, I added a bit more documentation to the pass description.
https://github.com/llvm/llvm-project/pull/96331
