### ISSUE TITLE
Failed to lower "torch.aten.sum.dim_IntList" to linalg

### ISSUE THREAD

**Issue by josel-amd** [llvm/torch-mlir#3423]
Hi all,

I need to convert `torch.aten.sum.dim_IntList` into linalg. There seems to be support for it but only if the dimension is static. Otherwise, I'm getting the following error message:  `dim argument must be a constant int list or None`. The expected behavior here would be getting the conversion to linalg.

**Command to reproduce:**

`torch-mlir-opt --torch-backend-to-linalg-on-tensors-backend-pipeline  reproducer.mlir -debug`

The code for the reproducer is in [1]

**Observed error message:**

```
//===-------------------------------------------===//
Legalizing operation : 'torch.aten.sum.dim_IntList'(0x561e4791b540) {
  %17 = "torch.aten.sum.dim_IntList"(%6, %16, %2, %1) : (!torch.vtensor<[3,2,2],f32>, !torch.list<int>, !torch.bool, !torch.none) -> !torch.vtensor<[3,2],f32>

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'torch.aten.sum.dim_IntList -> ()' {
Trying to match "(anonymous namespace)::ConvertAtenScalarToTensorLike"
    ** Failure : not a supported Scalar to Tensor like op
"(anonymous namespace)::ConvertAtenScalarToTensorLike" result 0
  } -> FAILURE : pattern failed to match

  * Pattern : 'torch.aten.sum.dim_IntList -> ()' {
Trying to match "(anonymous namespace)::ConvertElementwiseOp"
    ** Failure : not a supported elementwise op
"(anonymous namespace)::ConvertElementwiseOp" result 0
  } -> FAILURE : pattern failed to match

  * Pattern : 'torch.aten.sum.dim_IntList -> ()' {
Trying to match "(anonymous namespace)::ConvertReductionOp"
    ** Failure : `dim` argument must be a constant int list or None
"(anonymous namespace)::ConvertReductionOp" result 0
  } -> FAILURE : pattern failed to match
} -> FAILURE : no matched legalization pattern
//===-------------------------------------------===//
<unknown>:0: error: failed to legalize operation 'torch.aten.sum.dim_IntList' that was explicitly marked illegal
<unknown>:0: note: see current operation: %17 = "torch.aten.sum.dim_IntList"(%6, %16, %2, %1) : (!torch.vtensor<[3,2,2],f32>, !torch.list<int>, !torch.bool, !torch.none) -> !torch.vtensor<[3,2],f32>
```

[1]
```
#loc = loc(unknown)
module attributes {
  llvm.data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128",
  llvm.target_triple = "x86_64-unknown-linux-gnu",
  "onnx-mlir.symbol-postfix" = "onnxmodel.onnx.mlir"} {
  func.func @forward(%arg0: tensor<3x2x2xf32> {onnx.name = "data"} loc(unknown), %arg1: tensor<1xi64> {onnx.name = "axes"} loc(unknown)) -> (tensor<3x2xf32> {onnx.name = "reduced"}) attributes {
    torch.onnx_meta.opset_version = 19 : si64} {
    %int1 = torch.constant.int 1 loc(#loc)
    %none = torch.constant.none loc(#loc)
    %false = torch.constant.bool false loc(#loc)
    %int3 = torch.constant.int 3 loc(#loc)
    %int0 = torch.constant.int 0 loc(#loc)
    %0 = torch_c.from_builtin_tensor %arg0 : tensor<3x2x2xf32> -> !torch.vtensor<[3,2,2],f32> loc(#loc)
    %1 = torch_c.from_builtin_tensor %arg1 : tensor<1xi64> -> !torch.vtensor<[1],si64> loc(#loc)
    %2 = torch.aten.squeeze.dim %1, %int0 : !torch.vtensor<[1],si64>, !torch.int -> !torch.vtensor<[1],si64> loc(#loc)
    %3 = torch.aten.item %2 : !torch.vtensor<[1],si64> -> !torch.int loc(#loc)
    %4 = torch.aten.lt.int %3, %int0 : !torch.int, !torch.int -> !torch.bool loc(#loc)
    %5 = torch.aten.Int.bool %4 : !torch.bool -> !torch.int loc(#loc)
    %6 = torch.aten.mul.int %5, %int3 : !torch.int, !torch.int -> !torch.int loc(#loc)
    %7 = torch.aten.add.int %3, %6 : !torch.int, !torch.int -> !torch.int loc(#loc)
    %8 = torch.prim.ListConstruct %7 : (!torch.int) -> !torch.list<int> loc(#loc)
    %9 = torch.aten.sum.dim_IntList %0, %8, %false, %none : !torch.vtensor<[3,2,2],f32>, !torch.list<int>, !torch.bool, !torch.none -> !torch.vtensor<[3,2],f32> loc(#loc)
    %10 = torch.aten.size.int %0, %7 : !torch.vtensor<[3,2,2],f32>, !torch.int -> !torch.int loc(#loc)
    %11 = torch.aten.mul.int %int1, %10 : !torch.int, !torch.int -> !torch.int loc(#loc)
    %12 = torch.aten.div.Scalar %9, %11 : !torch.vtensor<[3,2],f32>, !torch.int -> !torch.vtensor<[3,2],f32> loc(#loc)
    %13 = torch_c.to_builtin_tensor %12 : !torch.vtensor<[3,2],f32> -> tensor<3x2xf32> loc(#loc)
    return %13 : tensor<3x2xf32> loc(#loc)
  } loc(#loc)
} loc(#loc)
```

**Comment by jinchen62** [comment]
Hi @josel-amd , yes we currently only support static dims unless the numbers of input shape are distinct because we can't generate a generic op with reduction dims where we don’t know which dims are being reduced. Did you get this case from running a model that passes dims as arg input?

**Comment by jinchen62** [comment]
Created a smaller repro here https://gist.github.com/jinchen62/a42ed005a06c90c048843fcb4dc5b174

command: `torch-mlir-opt repro.mlir -convert-torch-to-linalg`

**Comment by josel-amd** [comment]
Hi @jinchen62, I can't discuss much publicly, but we're trying to get coverage for a wide number of operators that we think might come our way, independent if they are in a model or not. That is important for us. In that spirit, I've created a lot of similar issues to this one. The use case does not sound very exotic in this case and I could imagine that there might be other operators suffering from the same problem? It could also be that this requires a broader approach.

Any suggestions on what the approach should be moving forward?

Thanks for taking an interest! :)

**Comment by stellaraccident** [comment]
While it is possible to multi version such a program, it is effectively a graph that cannot be optimized. In the few cases I've seen like this (mostly from very old tensor flow graphs), if you look at the whole thing, you'll either find that it is a contrived example or an entire polymorphic program that should really be multiple graphs (ie. Even if you fixed the one reduction, it will just become under defined at the next op). I don't even think modern torch lets you capture a graph like this as it would fail to have a shape inference solution. 

Usually, when I've seen programs like this, they've been partially reduced from something else and the complicated sub graph of small tensor manipulations have been the result of some older style shape expressions that didn't properly fold or something.

It is actually fairly exotic to have graphs that induce rank or axis dynamism. If you tried this in torch dynamo, I'm almost certain it would graph break and fail to compile across such a sequence of ops because any program at or after this point would have a completely different loop/fusion structure and would be useless to try to optimize. 

There are a variety of ways to allow such dynamism, but in general the frameworks and tools are going the other way and forbidding it.

**Comment by stellaraccident** [comment]
If this were running under an eager framework like torch.compile or turbine, it would probably specialize on the value of arg1 and emit a guard/variation for every version or sees -- effectively never trying to compile a single graph that expresses this kind of dynamism. That's typically the best a compiler can do in these cases, outside of a handful of mostly contrived outliers.

A similar strategy could be employed here but would require knowing in what context this was being compiled/run.

**Comment by josel-amd** [comment]
Thank you for giving the overall picture on how and where this issue is handled at! Indeed, I'm taking a parallel route and trying to import an onnx model that's not necessarily generated from pytorch. I would then categorize this issue as somewhat artificial. Since we haven't observed this in a model and together with what you said above, we'll adapt the test and I'm closing the issue. Thank you!
