### ISSUE TITLE
Failed to lower 'torch.operator "onnx.AveragePool"' to torch (dilation)

### ISSUE THREAD

**Issue by josel-amd** [llvm/torch-mlir#3428]
Hi all,

I need to convert 'torch.operator "onnx.AveragePool"' to torch but it fails with `dilation is not supported by torch.aten.avgpool op`

Command to reproduce:

```
torch-mlir-opt --allow-unregistered-dialect --convert-torch-onnx-to-torch dilation.mlir -debug;
```

Observed behavior
See [0]

It might be useful: I tracked the implementation back to this [PR](https://github.com/llvm/torch-mlir/pull/2672).

[0]

```
//===-------------------------------------------===//
Legalizing operation : 'torch.operator'(0x560591ccb250) {
  %1 = "torch.operator"(%arg0) <{name = "onnx.AveragePool"}> {torch.onnx.ceil_mode = 1 : si64, torch.onnx.dilations = [2 : si64, 2 : si64], torch.onnx.kernel_shape = [2 : si64, 2 : si64], torch.onnx.strides = [1 : si64, 1 : si64]} : (!torch.vtensor<[1,1,4,4],f32>) -> !torch.vtensor<[1,1,2,2],f32>

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'torch.operator -> ()' {
Trying to match ""
    ** Failure : dilation is not supported by torch.aten.avgpool op
: conversion failed to apply: "onnx.AveragePool", sinceVersion=11
    ** Failure : no matching versioned converter
"" result 0
  } -> FAILURE : pattern failed to match
} -> FAILURE : no matched legalization pattern
//===-------------------------------------------===//
dilation.mlir:4:10: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %0 = torch.operator "onnx.AveragePool"(%arg0) {torch.onnx.ceil_mode = 1 : si64, torch.onnx.dilations = [2 : si64, 2 : si64], torch.onnx.kernel_shape = [2 : si64, 2 : si64], torch.onnx.strides = [1 : si64, 1 : si64]} : (!torch.vtensor<[1,1,4,4],f32>) -> !torch.vtensor<[1,1,2,2],f32>
         ^
dilation.mlir:4:10: note: see current operation: %1 = "torch.operator"(%arg0) <{name = "onnx.AveragePool"}> {torch.onnx.ceil_mode = 1 : si64, torch.onnx.dilations = [2 : si64, 2 : si64], torch.onnx.kernel_shape = [2 : si64, 2 : si64], torch.onnx.strides = [1 : si64, 1 : si64]} : (!torch.vtensor<[1,1,4,4],f32>) -> !torch.vtensor<[1,1,2,2],f32>
ImplicitTypeIDRegistry::lookupOrInsert(mlir::detail::PreservedAnalyses::AllAnalysesType)
```

**Comment by AmosLewis** [comment]
There is no dilation support in pytorch nowadays, so it's not doable in torch-mlir @vivekkhandelwal1 @josel-amd 
https://discuss.pytorch.org/t/more-dilation-support-for-maxpool-avgpool/188052
https://github.com/pytorch/pytorch/issues/14907

**Comment by AmosLewis** [comment]
@josel-amd  Could you also share the dilation.mlir your are working on?

**Comment by vivekkhandelwal1** [comment]
> There is no dilation support in pytorch nowadays, so it's not doable in torch-mlir @vivekkhandelwal1 @josel-amd https://discuss.pytorch.org/t/more-dilation-support-for-maxpool-avgpool/188052 [pytorch/pytorch#14907](https://github.com/pytorch/pytorch/issues/14907)

I think you can add the support conditionally. I mean atleast for the default dilation value we can remove the failure.

**Comment by AmosLewis** [comment]
> I think you can add the support conditionally. I mean atleast for the default dilation value we can remove the failure.

As you can see from the error, they are targeting ` torch.onnx.dilations = [2 : si64, 2 : si64]` which is not the default.

**Comment by mgehre-amd** [comment]
I wonder whether this could be lowered using Col2Im, which seems to have dilation support.

**Comment by AmosLewis** [comment]
zach mentioned we can use the con which has dilation support. It looks doable.
```
import torch

class ConvVsAvgPoolModule(torch.nn.Module):
    def __init__(self, kernel_size, stride, padding, num_channels):
        self.kernel_size = kernel_size
        self.channels = num_channels
        self.padding = padding
        self.stride = stride
        super().__init__()
        self.avg_pool = torch.nn.AvgPool2d(kernel_size=kernel_size, stride=stride, padding=padding)
        weight_shape = (self.channels, 1, kernel_size[0], kernel_size[1])
        self.weight = torch.ones(weight_shape)
        self.weight = self.weight
    
    def forward(self, input):
        ap = self.avg_pool(input)
        c = torch.nn.functional.conv2d(input, self.weight,stride=self.stride,padding=self.padding, groups=self.channels)
        c = c/(self.kernel_size[0]*self.kernel_size[1])
        diff = ap - c
        return diff

m = ConvVsAvgPoolModule((2,3), 1, 0, 2)

input = torch.randn(size=(2,2,3,5))
diff = m(input)
print(diff) # 0
```

**Comment by mgehre-amd** [comment]
> zach mentioned we can use the conv which has dilation support. It looks doable.

I think the main difficulty is that the scale factor must count only valid elements at the boundaries (see `count_include_pad`), and thus there needs to be a different scale per window.

**Comment by AmosLewis** [comment]
fix https://github.com/llvm/torch-mlir/pull/3490
