### ISSUE TITLE
Bump onnx to 1.16.1

### ISSUE THREAD

**Issue by stellaraccident** [llvm/torch-mlir#3507]
Onnx 1.16.1 has Python 3.12 support and we should upgrade. Looks like it causes some minor test failures.

Please update in test-requirements.txt, validate and push.

**Comment by vivekkhandelwal1** [comment]
Okay, I will do this.

**Comment by zjgarvey** [comment]
I'm not sure if these changes will fix the mentioned issues or not: <https://github.com/llvm/torch-mlir/pull/3317>
