### ISSUE TITLE
Support specialized lowering to depthwise_conv_2d_nchw_chw_q

### ISSUE THREAD

**Issue by newling** [llvm/torch-mlir#3540]
Depthwise convolution is a  group convolution with group size = 1. In onnx the IR stores the number of groups not the group size. This is how a depthwise convolution gets lowered from ONNX to linalg. IR like:

```
 %654 = torch.operator "onnx.Conv"(%653, %554, %553) {torch.onnx.auto_pad = "NOTSET", torch.onnx.dilations = [1 : si64, 1 : si64], torch.onnx.group = 32 : si64, torch.onnx.kernel_shape = [3 : si64, 3 : si64], torch.onnx.pads = [1 : si64, 1 : si64, 1 : si64, 1 : si64], torch.onnx.strides = [1 : si64, 1 : si64]} : (!torch.vtensor<[1,32,257,257],f32>, !torch.vtensor<[32     ,1,3,3],f32>, !torch.vtensor<[32],f32>) -> !torch.vtensor<[1,32,257,257],f32>
 ```

gets lowered to IR like
```
 %244 = torch.aten.convolution %240, %241, %243, %227, %227, %227, %false, %229, %int32 : !torch.vtensor<[1,32,257,257],!torch.qint8>, !torch.vtensor<[32,1,3,3],!torch.qint8>, !torch.vtensor<[32],si32>, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool, !torch.list<int>, !torch.int -> !torch.vtensor<[1,32,257,257],si32>
```

gets lowered to IR like

```
%411 = linalg.conv_2d_ngchw_gfchw_q {dilations = dense<1> : vector<2xi64>, strides = dense<1> : vector<2xi64>} ins(%expanded, %expanded_468, %396, %398 : tensor<1x32x1x259x259xi8>, tensor<32x1x1x3x3xi8>, i32, i32) outs(%expanded_469 : tensor<1x32x1x257x257xi32>) -> tensor<1x32x1x257x257xi32>
```

So the depthwise convolution is represented as a group convolution in the linalg dialect. This is fine, however it would be nice to use the most specialized operation in linalg available for each op. There is some support in torch's linalg lowering for specialization of depthwise convolution: 

https://github.com/llvm/torch-mlir/blob/5e4f00acb13f3f849a05e5ac28ee39307a5fdbff/lib/Conversion/TorchToLinalg/Linear.cpp#L1233

Moreover there is one depthwise quantized convolution operation in linalg:
https://mlir.llvm.org/docs/Dialects/Linalg/#linalgdepthwise_conv_2d_nhwc_hwc_q-linalgdepthwiseconv2dnhwchwcqop

The linalg operation linked to is in "hwc" layout. But unfortunately the group convolution we'd like to specialize is in "chw" layout (see %411 above). 

So I see 2 steps to completing this task 

1) Add a new operation in MLIR, along the lines of https://github.com/llvm/llvm-project/blob/2ad7b4af95bc333d8f216915cd1b9d688590dcc5/mlir/include/mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.yaml#L4396

2) Extend the specialization to linalg depthwise convolution in torch-mlir

**Comment by newling** [comment]
@yzhang93 @zjgarvey @MaheshRavishankar I think this is what is needed if we want to avoid group-wise conv getting down to codegen. That said, I'm still not sure why we can't just handle the special case of group-size=1 directly in codegen (maybe there is some IREE machinery I'm not familiar with).

**Comment by yzhang93** [comment]
After offline discussion, we decided to take a path to convert the torch depthwise conv directly to `linalg.transpose` followed by `linalg.depthwise_conv_2d_nhwc_hwc_q` ops as this is the way for lowering Conv2d ops in deeplabv3 currently. However, for the long term, it might be good to introduce new named ops, i.e., `linalg.conv_2d_nchw_fchw_q \ linalg.depthwise_conv_2d_nchw_chw_q`.

**Comment by zjgarvey** [comment]
Resolving this for now, since <https://github.com/llvm/torch-mlir/pull/3564> was merged.
