### ISSUE TITLE
How to translate a pytorch model to mlir?

### ISSUE THREAD

**Issue by FlintWangacc** [llvm/torch-mlir#3742]
As the deletion of torchscript, torchscript.compile is not available anymore. Is there another interface to translate a pytorch model to mlir?

**Comment by stellaraccident** [comment]
There is a standalone example in the readme: https://github.com/llvm/torch-mlir?tab=readme-ov-file#fximporter-resnet18

It references a simple API that is part of torch-mlir to export an nn module to FX then to mlir: https://github.com/llvm/torch-mlir/blob/a33d1232c5c67e82147126619d787d56521f8617/projects/pt1/examples/fximporter_resnet18.py#L32
