### ISSUE TITLE
Fail to perform GPT2-MLIR and Resnet-MLIR transformation with the latest Torch-Mlir

### ISSUE THREAD

**Issue by Jason048** [llvm/torch-mlir#3773]
Hello, I cloned the latest Torch-MLIR today and successfully built the code following the instructions in [development.md](https://github.com/llvm/torch-mlir/blob/eb7bf78a9c1e250949cf0151628f35fb0ac06903/docs/development.md). The command `python test/python/fx_importer/basic_test.py `executed successfully. However, I encountered an error when running 
`python projects/pt1/examples/torchscript_resnet18_all_output_types.py`  : 
![image](https://github.com/user-attachments/assets/b6ed054c-5284-4dc3-b896-db693837c3b9)
I also tried GPT-2-MLIR with the following code: 
```
from transformers import GPT2LMHeadModel, GPT2Tokenizer, GPT2Model
import torch
import torch_mlir
from torch_mlir import fx

test_modelname = "gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(test_modelname)
prompt = "What is nature of our existence?"
encoding = tokenizer(prompt, return_tensors="pt")

model = GPT2LMHeadModel.from_pretrained(
    test_modelname,
    num_labels=2,
    output_attentions=False,
    output_hidden_states=False,
    attn_implementation="eager",
)

model.to("cpu")
model.eval()

module = fx.export_and_import(model, encoding["input_ids"], output_type="linalg-on-tensors", func_name=model.__class__.__name__, ) 
```
Here is the error message:

![image](https://github.com/user-attachments/assets/c9fd3941-7298-4b20-ab50-3e244af4ad4d)

Could you please check the problem?
@stellaraccident

**Comment by stellaraccident** [comment]
If you would like to submit a patch to remove broken examples from development.md, please do so: that file is maintained as needed by people developing the project and existing devs rarely go back and try the instructions.
