### ISSUE TITLE
Unsupported by backend lowering: `torch.operator` op 

### ISSUE THREAD

**Issue by ds1231h** [llvm/torch-mlir#380]
I’m new to the torch-mlir, and I’m trying it with a simple op, but met such error:

>    error: unsupported by backend lowering: torch.operator op
    note: see current operation: %41 = “torch.operator”(%38, %40) {name = “aten.maximum”} : (!torch.tensor<[?,?],f32>, !torch.tensor<[?,?],f32>) → !torch.tensor
    note: this is likely due to a missing op that needs to be generated by torch_ods_gen.py
    Traceback (most recent call last):
    File “/torch-mlir/examples/iou_of.py”, line 119, in
    compiled = compile_module(mlp_module)
    File “/torch-mlir/examples/iou_of.py”, line 99, in compile_module
    pm.run(mb.module)
    RuntimeError: Failure while executing pass pipeline.

As far as I’m concerned, such an error means there’s something wrong in the pass manager of “torch-backend-to-linalg-on-tensors-backend-pipeline”. But I have no idea how to fix that or is there an error with my code?

Thanks!

----------------------------
I proposed such question in the community too:
https://llvm.discourse.group/t/unsupported-by-backend-lowering-torch-operator-op/4590

**Comment by dan-garvey** [comment]
@ds1231h Should have pr up tonight or tomorrow = )

**Comment by ds1231h** [comment]
> 
> 
> @ds1231h Should have pr up tonight or tomorrow = )

Great! Thanks!


> @ds1231h - while you are waiting, do you have another module that you can try? It is useful for us to know what we are missing! Please file bugs!

Actually, I found these op are pretty frequently: 
```
torch.Tensor.new_tensor
torch.tensor.expand
torch.where
prim.abs
torch.tensor.long
torch.sort
torch.unique
torch.reshape
torch.nonzero
```
Is there any plan to support them? @silvasean

**Comment by cathyzhyi** [comment]
Thanks for collecting the list! Currently we are actively working on this [list](https://github.com/llvm/torch-mlir/issues/342#issuecomment-931729772) and will start this [list](https://github.com/llvm/torch-mlir/issues/365#issue-1028365785) soon. `torch.tensor.expand` (aten::expand) is being implemented by @Shukla-Gaurav. We haven't got anyone actively working on the rest of the ops yet.

**Comment by ds1231h** [comment]
I see. Thanks!





This op list is collected from the actual business of SenseTime, which might be searched from the open-mmLab/mmdetection(https://github.com/open-mmlab/mmdetection).



For practical needs, our group plans to complete the conversion from PyTorch to MLIR through torch-mlir.



If you do not have such a plan to support that, I would like to add them by myself. I hope to have the opportunity to give back my work to the community because it requires the consent of my leaders.



Thanks again for your work!





Yours sincerely,
Pei Mu





在 2021-11-01 21:28:28，"Yi Zhang" ***@***.***> 写道：

Thanks for collecting the list! Currently we are actively working on this list and will start this list soon. torch.tensor.expand (aten::expand) is being implemented by @Shukla-Gaurav. We haven't got anyone actively working on the rest of the ops yet.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ds1231h** [comment]
> 
> 
> Thanks @ds1231h
> 
> I think that torch.where, prim.abs, and torch.reshape are probably the easiest to get started with. sort/unique/nonzero are more difficult, because they do not lower easily to linalg (I can explain how to lower them to linalg if you are interested).

Thanks a lot! I would follow your advice and try the ```torch.where, prim.abs, and torch.reshape``` firstly :)

As for the ```sort/unique/nonzero```, I intend to finish the first three operators before dealing with them.  (Maybe in another issue, I guess)

Thanks again!

**Comment by ds1231h** [comment]
Hi @dan-garvey, Thanks for your pr #398 
I've merged your changes(without dropout op) in my environment and tried the IouOfModule again, but I got such an error:
```bash
torch-mlir/e2e_testing/torchscript/vision_models.py:46:17: error: failed to legalize operation 'torch.aten.select.int' that was explicitly marked illegal
        area1 = (bbox1[:, 2] - bbox1[:, 0]) * (bbox1[:, 3] - bbox1[:, 1])
                ^
torch-mlir/e2e_testing/torchscript/vision_models.py:46:17: note: see current operation: %30 = "torch.aten.select.int"(%29, %6, %2) : (!torch.vtensor<[?,?],f32>, !torch.int, !torch.int) -> !torch.vtensor<[?,1],f32>
```
Was I missing something?

Actually, I'm not sure what's the ```was explicitly marked illegal``` means.

**Comment by dan-garvey** [comment]
No you didn't miss something, my patch just isn't quite finished yet, will try to get your case covered in the next upload, and I'll let you know when its covered if you want to try before its merged

**Comment by silvasean** [comment]
> Actually, I'm not sure what's the `was explicitly marked illegal` means.

This is a message from MLIR Dialect Conversion framework https://mlir.llvm.org/docs/DialectConversion/

We use Dialect Conversion to implement the TorchToLinalg transformation. To do that, we mark the op "illegal" so that dialect conversion will call the pattern to legalize it.

**Comment by ds1231h** [comment]
> 
> 
> No you didn't miss something, my patch just isn't quite finished yet, will try to get your case covered in the next upload, and I'll let you know when its covered if you want to try before its merged

Thanks! Looking forward to it. If there is anything I can do, please let me know.

**Comment by ds1231h** [comment]
> 
> 
> > Actually, I'm not sure what's the `was explicitly marked illegal` means.
> 
> This is a message from MLIR Dialect Conversion framework https://mlir.llvm.org/docs/DialectConversion/
> 
> We use Dialect Conversion to implement the TorchToLinalg transformation. To do that, we mark the op "illegal" so that dialect conversion will call the pattern to legalize it.

Thanks for your answer. I understand that now.

**Comment by ds1231h** [comment]
hi @cathyzhyi 
I tried transform AtenSelectIntOp to AtenSliceTensorOp follow your comment, but got a segment fault. 
And My code in DecomposeComplexOps.cpp is:
```
// Decompose AtenSelectIntOp(dim, index) into:
//           AtenSliceTensorOp(dim, start=index, end=index+1,step=1)
namespace {
class DecomposeAtenSelectIntOp : public OpRewritePattern<AtenSelectIntOp> {
public:
  using OpRewritePattern::OpRewritePattern;
  LogicalResult matchAndRewrite(AtenSelectIntOp op,
                                PatternRewriter &rewriter) const override {
    printf("DecomposeAtenSelectIntOp\n");
    Location loc = op.getLoc();
    Value self = op.self();
    Value dimValue = op.dim();
    Value indexValue = op.index();

    Value oneValue = rewriter.create<arith::ConstantIndexOp>(loc, 1);
    indexValue.dump();
    Value endValue = rewriter.create<mlir::arith::AddIOp>(loc, indexValue, oneValue);
    printf("intEndValue: \n");
    endValue.dump();

    BaseTensorType tensorType = self.getType().cast<BaseTensorType>();
    if (!tensorType.hasDtype() || !tensorType.getDtype().isa<mlir::FloatType>())
      return rewriter.notifyMatchFailure(op, "Only support floating type");

    // get result type
    SmallVector<int64_t> sizes;
    int64_t dimInt;
    if (tensorType.hasSizes()) {
      ArrayRef<int64_t> inputShape = tensorType.getSizes();
      int64_t inputRank = inputShape.size();
      if (matchPattern(dimValue, m_TorchConstantInt(&dimInt))) {
        dimInt = toPositiveDim(dimInt, inputRank);
        if (!isValidDim(dimInt, inputRank))
          return rewriter.notifyMatchFailure(op, "dim is not a valid dim");
        sizes.append(inputShape.begin(), inputShape.end());
        sizes[dimInt] = 1;
      } else {
        sizes.resize(inputRank, kUnknownSize);
      }
    }

    Value result;
    Type resultType = tensorType.getWithSizesAndDtype(
            sizes.size() == 0 ? Optional<ArrayRef<int64_t>>()
                              : llvm::makeArrayRef(sizes),
            tensorType.getDtype());

	  printf("Before AtenSliceTensorOp\n"); // Seems got segment faul after this
    result = rewriter.create<AtenSliceTensorOp>(
            loc, resultType, result, dimValue, indexValue, endValue, oneValue);
	  printf("Get result\n");
	  result.dump();
    rewriter.replaceOpWithNewOp<TensorStaticInfoCastOp>(op, op.getType(),
                                                        result);
	  printf("Return success\n");

    return success();
  }
};
}
```
It seems something wrong in ```rewriter.create```, but it's a bit difficult for me to trace that error.
Is there any advice?
Thanks a lot.

**Comment by ds1231h** [comment]
> hi @cathyzhyi I tried transform AtenSelectIntOp to AtenSliceTensorOp follow your comment, but got a segment fault. And My code in DecomposeComplexOps.cpp is:
> 
> ```
> // Decompose AtenSelectIntOp(dim, index) into:
> //           AtenSliceTensorOp(dim, start=index, end=index+1,step=1)
> namespace {
> class DecomposeAtenSelectIntOp : public OpRewritePattern<AtenSelectIntOp> {
> public:
>   using OpRewritePattern::OpRewritePattern;
>   LogicalResult matchAndRewrite(AtenSelectIntOp op,
>                                 PatternRewriter &rewriter) const override {
>     printf("DecomposeAtenSelectIntOp\n");
>     Location loc = op.getLoc();
>     Value self = op.self();
>     Value dimValue = op.dim();
>     Value indexValue = op.index();
> 
>     Value oneValue = rewriter.create<arith::ConstantIndexOp>(loc, 1);
>     indexValue.dump();
>     Value endValue = rewriter.create<mlir::arith::AddIOp>(loc, indexValue, oneValue);
>     printf("intEndValue: \n");
>     endValue.dump();
> 
>     BaseTensorType tensorType = self.getType().cast<BaseTensorType>();
>     if (!tensorType.hasDtype() || !tensorType.getDtype().isa<mlir::FloatType>())
>       return rewriter.notifyMatchFailure(op, "Only support floating type");
> 
>     // get result type
>     SmallVector<int64_t> sizes;
>     int64_t dimInt;
>     if (tensorType.hasSizes()) {
>       ArrayRef<int64_t> inputShape = tensorType.getSizes();
>       int64_t inputRank = inputShape.size();
>       if (matchPattern(dimValue, m_TorchConstantInt(&dimInt))) {
>         dimInt = toPositiveDim(dimInt, inputRank);
>         if (!isValidDim(dimInt, inputRank))
>           return rewriter.notifyMatchFailure(op, "dim is not a valid dim");
>         sizes.append(inputShape.begin(), inputShape.end());
>         sizes[dimInt] = 1;
>       } else {
>         sizes.resize(inputRank, kUnknownSize);
>       }
>     }
> 
>     Value result;
>     Type resultType = tensorType.getWithSizesAndDtype(
>             sizes.size() == 0 ? Optional<ArrayRef<int64_t>>()
>                               : llvm::makeArrayRef(sizes),
>             tensorType.getDtype());
> 
> 	  printf("Before AtenSliceTensorOp\n"); // Seems got segment faul after this
>     result = rewriter.create<AtenSliceTensorOp>(
>             loc, resultType, result, dimValue, indexValue, endValue, oneValue);
> 	  printf("Get result\n");
> 	  result.dump();
>     rewriter.replaceOpWithNewOp<TensorStaticInfoCastOp>(op, op.getType(),
>                                                         result);
> 	  printf("Return success\n");
> 
>     return success();
>   }
> };
> }
> ```
> 
> It seems something wrong in `rewriter.create`, but it's a bit difficult for me to trace that error. Is there any advice? Thanks a lot.

More specifically, any help about pointing out the problem immediately or any debugging method for MLIR would appreciate a log!

**Comment by cathyzhyi** [comment]
@ds1231h In the `DecomposeComplexOps` pass, we are decomposing torch ops to simpler torch ops so  you can't use std dialect like this `Value endValue = rewriter.create<mlir::arith::AddIOp>(loc, indexValue, oneValue);`.  https://github.com/llvm/torch-mlir/pull/398 is still in draft state but it contains all the main parts needed.

**Comment by ds1231h** [comment]
> 
> 
> @ds1231h In the `DecomposeComplexOps` pass, we are decomposing torch ops to simpler torch ops so you can't use std dialect like this `Value endValue = rewriter.create<mlir::arith::AddIOp>(loc, indexValue, oneValue);` in this pass. See
> 
> https://github.com/llvm/torch-mlir/blob/127c7d8e27ede211af77392b5277ba06fb515fb7/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp#L124
> that torch dialect is the only legal dialect in this pass. You could refer to https://mlir.llvm.org/docs/DialectConversion/.
> 
> #398 is still in draft state but it contains all the main parts needed. It should be working pretty soon :)

Thank you very much for your advertisement! Due to my needs being quite emergency, I'm just doing it as a runnable model.
Stilling looking forward to #398!

**Comment by ds1231h** [comment]
I'm also working on the SelectInt op by myself, and I have a question. 

In my view, the SliceTensor op is an elementwise op, but the SelectInt op is a reduce op (as it reduces the selected dim). Am I right?

If so, we need to match the `AtenSelectIntOp` pattern in but not `ConvertReductionOp`.
In this case, is it still possible to implement it through the `AtenSliceTensorOp`?
@cathyzhyi @silvasean @dan-garvey

**Comment by cathyzhyi** [comment]
`SliceTensor` is not an elementwise op and need to be lowered in its own conversion pattern.  You are right about `SelectInt ` being reduction op but it's not the operation supported by `ConvertReductionOp` which does destructive updates along the reduced dimension (with a keepDim parameter) rather than select one index from the reduced dimension. It's possible to change `ConvertReductionOp` to include this but would make the code hard to read and not really worth it.  IMO #398 is using best way to implement those 2 ops.

**Comment by ds1231h** [comment]
> `SliceTensor` is not an elementwise op and need to be lowered in its own conversion pattern. You are right about `SelectInt ` being reduction op but it's not the operation supported by `ConvertReductionOp` which does destructive updates along the reduced dimension (with a keepDim parameter) rather than select one index from the reduced dimension. It's possible to change `ConvertReductionOp` to include this but would make the code hard to read and not really worth it. IMO #398 is using best way to implement those 2 ops.

Thank you!

**Comment by ds1231h** [comment]
Thanks for @dan-garvey 's work, done!
