### ISSUE TITLE
Compiler segfaults when running SliceTensor folder

### ISSUE THREAD

**Issue by Max191** [llvm/torch-mlir#3841]
The folder for the AtenSliceTensorOp causes a segmentation fault for certain inputs. This happens when the indices of the slice are out of bounds:

```mlir
func.func @test_shape_clip_start(%arg0: !torch.vtensor<[3,4,5],f32>) -> !torch.vtensor<[3],si64> attributes {torch.onnx_meta.ir_version = 10 : si64, torch.onnx_meta.opset_version = 21 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
  %none = torch.constant.none
  %0 = torch.aten._shape_as_tensor %arg0 : !torch.vtensor<[3,4,5],f32> -> !torch.vtensor<[3],si64>
  %int-10 = torch.constant.int -10
  %int-1 = torch.constant.int -1
  %int1 = torch.constant.int 1
  %int0 = torch.constant.int 0
  %1 = torch.aten.slice.Tensor %0, %int0, %int-10, %int-1, %int1 : !torch.vtensor<[3],si64>, !torch.int, !torch.int, !torch.int, !torch.int -> !torch.vtensor<[3],si64>
  return %1 : !torch.vtensor<[3],si64>
}
```

Running the canonicalizer on the above IR runs the folder and causes the segmentation fault:
```
iree-opt test.mlir -canonicalize
```

**Comment by zjgarvey** [comment]
Looking into this right now.

**Comment by zjgarvey** [comment]
Ah, interestingly, this is partly an issue with the `start` not being clamped properly in the folder, and partly an issue with the IR generated from the `onnx.Shape` lowering being incorrect. It shouldn't have `end = -1`, since the result would only have two elements. E.g.

```python
import torch
a = torch.arange(3)
b = torch.ops.aten.slice.Tensor(a, 0, -10, -1, 1)
print(b)
```
returns 
```
tensor([0, 1])
```

 I'll have a solution soon on both fronts. Thanks for posting the issue.

**Comment by zjgarvey** [comment]
PR up for the relevant fixes. <https://github.com/llvm/torch-mlir/pull/3843>
