### ISSUE TITLE
`Conversion/TorchToTosa/basic.mlir` failing on ARM, due to different random numbers in `torch.aten.uniform`

### ISSUE THREAD

**Issue by dbabokin** [llvm/torch-mlir#3859]
After https://github.com/llvm/torch-mlir/commit/4dd213b04223f2b49418205739702d80ff2c4a9b by @justin-ngo-arm, I see `Conversion/TorchToTosa/basic.mlir` test is failing on my ARM-based MacbookPro for `torch.aten.uniform` check. This line doesn't match:
https://github.com/llvm/torch-mlir/blob/7058f456b8aed85f6f08a73034be4cfa714c267e/test/Conversion/TorchToTosa/basic.mlir#L2266

Instead I have the following line in my output:
```
%0 = "tosa.const"() <{value = dense<[[1.0002023, 1.76529205, 6.41217375, 9.0245018], [9.71160125, 2.70720792, 5.63478279, 4.5820756], [3.36615539, 7.69161224, 1.8059299, 6.04350948]]> : tensor<3x4xf32>}> : () -> tensor<3x4xf32>
```

Which is also uniform distribution, but with different random numbers. The test works fine for me on x86 Linux, though.

I'm not sure if the test needs to be fixed or `torch.aten.uniform` itself to be more reproducible across platforms.

**Comment by justin-ngo-arm** [comment]
Hi @dbabokin , I've fixed the test and will tag you in the PR review process. Thank you for catching this issue.

**Comment by dbabokin** [comment]
@justin-ngo-arm Thanks for blazingly fast response!

**Comment by justin-ngo-arm** [comment]
@dbabokin I've tagged you in a comment in this recently merged PR - https://github.com/llvm/torch-mlir/pull/3855 - which includes the fix for the issue. Please let me know if this resolves your problem and we can close the issue out. Thank you!

**Comment by dbabokin** [comment]
I've just checked and the issue is fix. Thanks you!
