### ISSUE TITLE
TorchToStd.cpp is out of date

### ISSUE THREAD

**Issue by silvasean** [llvm/torch-mlir#409]
A lot of the patterns there should be moved to a new TorchToArith.cpp conversion, now that arith dialect was split out of std.

**Comment by stellaraccident** [comment]
Can we just call all of these ConvertToTheDialectFormerlyKnownAsStandard :)

(Rip Prince)

**Comment by stephenneuendorffer** [comment]
I've submitted a unicode community request to reserve a symbol for "TheDialectFormerlyKnownAsStandard".  Design ideas would be appreciated.

**Comment by silvasean** [comment]
We have two options TorchTo〄.cpp and TorchTo㉿.cpp

Those are "U+3004 japanese industrial standard symbol" and "U+327F korean standard symbol".

I have created a poll:

[![](https://api.gh-polls.com/poll/01FM5E93QVYB4KVYMVT8HJXW45/TorchTo%E3%80%84.cpp)](https://api.gh-polls.com/poll/01FM5E93QVYB4KVYMVT8HJXW45/TorchTo%E3%80%84.cpp/vote)
[![](https://api.gh-polls.com/poll/01FM5E93QVYB4KVYMVT8HJXW45/TorchTo%E3%89%BF.cpp)](https://api.gh-polls.com/poll/01FM5E93QVYB4KVYMVT8HJXW45/TorchTo%E3%89%BF.cpp/vote)

**Comment by u99127** [comment]
now fixed with #1163 and #1210

**Comment by silvasean** [comment]
Thanks for fixing this!!
