### ISSUE TITLE
Support for clamp (min=numpy.ndarray, max=numpy.ndarray)

### ISSUE THREAD

**Issue by ds1231h** [llvm/torch-mlir#410]
Hi,
I met a pattern like this:
```python
wh_ratio_clip=16 / 1000,
max_ratio = np.abs(np.log(wh_ratio_clip))
dw = dw.clamp(min=-max_ratio, max=max_ratio)
dh = dh.clamp(min=-max_ratio, max=max_ratio)
```
And I got this error:
```bash
TypeError: clamp() received an invalid combination of arguments - got (max=numpy.ndarray, min=numpy.ndarray, ), but expected one of:
         * (Number min, Number max)
              didn't match because some of the arguments have invalid types: (min=numpy.ndarray, max=numpy.ndarray, )
```

It seems we only have the Scalar version for clamp:
```
"aten::clamp : (Tensor, Scalar?, Scalar?) -> (Tensor)",
```
Do you have any plan to support the tensor version?
Or if could you help me to add that pattern?

**Comment by ds1231h** [comment]
Btw, I found another op ```aten.reciprocal```.
Shall I use the ```arith::DivFOp```to implement that?

**Comment by cathyzhyi** [comment]
> Btw, I found another op `aten.reciprocal`. Shall I use the `arith::DivFOp`to implement that?

Yea, it's an elementwise op that can be implemented by using `arith::DivFOp` in the compute payload.

**Comment by silvasean** [comment]
This looks like two problems:

1. You are using numpy.ndarray instead of torch.Tensor
2. Torch-MLIR does not support `aten::clamp.Tensor` (we only support `aten::clamp`). That support needs to be added. It is a simple elementwise op, so it should be easy to handle.

**Comment by ds1231h** [comment]
> e compute payload

Thanks for the reply! I'll give it a try.

**Comment by ds1231h** [comment]
> 
> 
> This looks like two problems:
> 
>     1. You are using numpy.ndarray instead of torch.Tensor
> 
>     2. Torch-MLIR does not support `aten::clamp.Tensor` (we only support `aten::clamp`). That support needs to be added. It is a simple elementwise op, so it should be easy to handle.

That's pretty clear, thank you! I'll try to add that one.

**Comment by ds1231h** [comment]
Thanks for your help and I have done these two ops successfully.
Another op ```torch.view``` encountered.
That seems quite difficult for me. Is there any example to follow?

**Comment by ds1231h** [comment]
These two ops have been fixed.
