### ISSUE TITLE
Support for control flow

### ISSUE THREAD

**Issue by ds1231h** [llvm/torch-mlir#424]
Hi, community!

I met a problem about if control-flow(just maybe, which I'm still debugging).
Just for curious, how do we support the control flow from pytorch to linalg then to scf dialect?

For now, I saw some codes in ```mlir/lib/Dialect/SCF/Transforms/StructuralTypeConversions.cpp```, but I can not get the whole path.

**Comment by cathyzhyi** [comment]
We have limited support for control flow. There is a `TorchToSCFPass` that can convert torch control flow ops to scf dialect. `RefineTypes` supports propagating types across branches. However, some passes don't support branches well yet like `MaximizeValueSemantics`.

**Comment by ds1231h** [comment]
Well noted! Thanks!

**Comment by ds1231h** [comment]
I tested a pytorch code like this:
```
def forward(self, x, y):
        if x.size() == 1:
            x = x + y
        return torch.add(x, y)
```

And I got such error in the ```createFinalizingBackendTypeConversionPass```:
```
test.mlir:5:10: error: failed to legalize operation 'torch.copy.to_tensor'
    %0 = torch.copy.to_tensor %arg0 : !torch.tensor<[2,2],f32>
         ^
test.mlir:5:10: note: see current operation: %8 = "torch.copy.to_tensor"(%1) : (!torch.vtensor<[2,2],f32>) -> !torch.tensor<[2,2],f32>
```

So what this bug means? And how can I fix that problem and solve it? Could you please give me some advice or tutorials?
Thank you!

**Comment by ds1231h** [comment]
By the way, is there any control flow related examples?

**Comment by pashu123** [comment]
> I tested a pytorch code like this:
> 
> ```
> def forward(self, x, y):
>         if x.size() == 1:
>             x = x + y
>         return torch.add(x, y)
> ```
> 
> And I got such error in the `createFinalizingBackendTypeConversionPass`:
> 
> ```
> test.mlir:5:10: error: failed to legalize operation 'torch.copy.to_tensor'
>     %0 = torch.copy.to_tensor %arg0 : !torch.tensor<[2,2],f32>
>          ^
> test.mlir:5:10: note: see current operation: %8 = "torch.copy.to_tensor"(%1) : (!torch.vtensor<[2,2],f32>) -> !torch.tensor<[2,2],f32>
> ```
> 
> So what does this bug mean? And how can I fix that problem and solve it? Could you please give me some advice or tutorials? Thank you!

I guess this is basically the current limitation of MaximiseValueSemantics pass. For more info you can checkout the pass here: https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp

**Comment by ds1231h** [comment]
> > I tested a pytorch code like this:
> > ```
> > def forward(self, x, y):
> >         if x.size() == 1:
> >             x = x + y
> >         return torch.add(x, y)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And I got such error in the `createFinalizingBackendTypeConversionPass`:
> > ```
> > test.mlir:5:10: error: failed to legalize operation 'torch.copy.to_tensor'
> >     %0 = torch.copy.to_tensor %arg0 : !torch.tensor<[2,2],f32>
> >          ^
> > test.mlir:5:10: note: see current operation: %8 = "torch.copy.to_tensor"(%1) : (!torch.vtensor<[2,2],f32>) -> !torch.tensor<[2,2],f32>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So what does this bug mean? And how can I fix that problem and solve it? Could you please give me some advice or tutorials? Thank you!
> 
> I guess this is basically the current limitation of MaximiseValueSemantics pass. For more info you can checkout the pass here: https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp

ok, thanks!
