### ISSUE TITLE
The Plan B for Unspported TrochScript Code

### ISSUE THREAD

**Issue by ds1231h** [llvm/torch-mlir#433]
Hi, community!

I seldomly met some ops which were not supported in ```torch_ods_gen.py```. 
In this case, do we have a plan B to locate the unsupport one and run it by native_torch or torchscript?

**Comment by cathyzhyi** [comment]
Can you list more details on what those ops are? And what is the error msg when you try to add them?

**Comment by ds1231h** [comment]
I believe technically torch-mlir can cover all ops and expressions supported by pytorch, but we do need some time and skills to add them, right? So if users want to run their pytorch code by torch-mlir immediately, they do not want any further coding work. I guess, in this situation, they wish torch-mlir could figure out which op in a model is not supported, and run the unsupported one by native_torch or torchscript, as configured in ```main.py```. And the ops with implementation in ```torch_ods_gen.py``` can run smoothly.

So there's no such specific list or error msg, I'm afraid. Btw, I believe we could cover all cases with torch-mlir in the future. :)

**Comment by silvasean** [comment]
We don't yet have a clear direction for op fallback. It's very difficult to do that in a way that would work with RefBackend, IREE, and other backends. So for now, we just have to do the hard work to implement the op :/

**Comment by ds1231h** [comment]
okay, I got it. Thank you!
