### ISSUE TITLE
"Unsupported op" error with TorchScript ResNet-18 example

### ISSUE THREAD

**Issue by erwei-xilinx** [llvm/torch-mlir#455]
When I ran the torchscript_resnet18_e2e.py example, I got the following error.

```
error: unsupported by backend lowering: `torch.operator` op
note: see current operation: %246 = "torch.operator"(%238, %243, %244, %245, %109, %100, %6) {name = "aten.avg_pool2d"} : (!torch.tensor<[?,?,?,?],f32>, !torch.list<!torch.int>, !torch.list<!torch.int>, !torch.list<!torch.int>, !torch.bool, !torch.bool, !torch.none) -> !torch.tensor
note: this is likely due to a missing op that needs to be generated by torch_ods_gen.py
Traceback (most recent call last):
  File "torchscript_resnet18_e2e.py", line 114, in <module>
    pm.run(mb.module)
RuntimeError: Failure while executing pass pipeline.
```

This resnet18 example used to work for me, but this error started to appear after I pulled and built torch-mlir again recently. This build passes all the regression tests.

**Comment by silvasean** [comment]
@ramiro050 can you triage this?

**Comment by ramiro050** [comment]
> @ramiro050 can you triage this?

Sure! Let me take a look.

**Comment by ramiro050** [comment]
@erwei-xilinx, my guess is that this might be related to the version of `TorchVision` that you are using. The `Resnet` model should be using the op `aten.adaptive_avg_pool2d` (see https://github.com/pytorch/vision/blob/ba299e8f52737448f1cbb9fffd25bf3d6e7ceef7/torchvision/models/resnet.py#L203), which is supported by `torch-mlir`, not the op `aten.avg_pool2d`.

The `Resnet` model used to use the op `aten.avg_pool2d`, but then it was changed to use `aten.adaptive_avg_pool2d` instead, as seen here https://github.com/pytorch/vision/commit/dc0238b82f0df5c44ec9878cb41011d1852a7afd.

Please let me know if this fixes your issue!

**Comment by erwei-xilinx** [comment]
@ramiro050 Thanks so much for the quick response. You are right and indeed I found multiple installations of TorchVision in my virtual env and after cleaning up the older versions I was once again able to run that example.
