### ISSUE TITLE
Return type for AtenEqTensorOp

### ISSUE THREAD

**Issue by anupgangwar** [llvm/torch-mlir#490]
Hi,

The return type for the AtenEqTensorOp operator should be boolean/i1 Tensor (ref: https://pytorch.org/docs/stable/generated/torch.eq.html). However, currently it is being set as f32 Tensor. Is this expected?

I also could not find anything on EqTensor lowering in the repo. Is the lowering for other Dialects defined elsewhere?

Thanks,
Anup

**Comment by anupgangwar** [comment]
@ramiro050 Can you comment?

**Comment by ramiro050** [comment]
Hi @anupgangwar! The lowering for `EqTensor` was just recently added to the `TorchToLinalg` pass https://github.com/llvm/torch-mlir/pull/483. It should be returning a tensor of bools. I just tried lowering the calculation `x == x` where `x` is a rank 2 tensor, and I get the following MLIR

```mlir
#map = affine_map<(d0, d1) -> (d0, d1)>
module attributes {torch.debug_module_name = "MyModule"}  {
  func @forward(%arg0: tensor<?x?xf32>) -> tensor<?x?xi1> {
    %c1 = arith.constant 1 : index
    %c0 = arith.constant 0 : index
    %0 = tensor.dim %arg0, %c0 : tensor<?x?xf32>
    %1 = tensor.dim %arg0, %c1 : tensor<?x?xf32>
    %2 = arith.cmpi eq, %0, %0 : index
    assert %2, "mismatched size for broadcast"
    %3 = arith.cmpi eq, %1, %1 : index
    assert %3, "mismatched size for broadcast"
    %4 = linalg.init_tensor [%0, %1] : tensor<?x?xi1>
    %5 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%arg0 : tensor<?x?xf32>) outs(%4 : tensor<?x?xi1>) {
    ^bb0(%arg1: f32, %arg2: i1):  // no predecessors
      %6 = arith.cmpf ueq, %arg1, %arg1 : f32
      linalg.yield %6 : i1
    } -> tensor<?x?xi1>
    return %5 : tensor<?x?xi1>
  }
}
```

which does return an `i1` tensor. Is there a particular example that you have that results in an `f32` tensor?

**Comment by anupgangwar** [comment]
Hi @ramiro050,
Thanks for the quick response. It looks like I do not have this commit since it was just merged. Will retry and update this thread.
Thanks

**Comment by anupgangwar** [comment]
Confirmed that I do see the correct Tensor of type 'i1' now. Will close the issue.
