### ISSUE TITLE
A prototype of jit.ignore support.

### ISSUE THREAD

**Issue by jinminxi104** [llvm/torch-mlir#504]
@ds1231h  and I are working on a prototype of jit.ignore support.
(This issue is similar to #462, and thanks for all helps in #462)
We would love any comments, and see if community is interesting in this prototype.

We are planning to convert jit.ignore function to a `std.call`. 
User can write the jit.ignore function in c/c++ manually, 
and link it with the program generated by torchMLIR

The use cases which we are considering are:
1.  allows user to write c/c++  manually  for TorchScript/TorchMLIR-incompatible python code
2. allows user to link with external library.

### Example

``` python
@torch.jit.ignore    
@detect_type       # detect_type is for getting the rank of foo. please read the design part.
def foo(self, in1, in2):    
    return some_torchscript_incompatible_python_code
    
@export              
@annotate_args([     
    None,            
    ([1024, 4], torch.float32, True),
    ([1024, 4], torch.float32, True),
])
def forward(self, arg1, arg2):
    some codes...
    xxx = self.foo(in1, in2)
    some codes...
    return ret
```

### Design
1.  jit.trace the forward and get the rank/dtype of `foo`.(the `detect_type` decorator in example code)
```python
# get args of forward
for arg in method._torch_mlir_arg_annotations:
  get args in `@annotate_args`

# trace forward
torch.jit.trace(forward, args)
 ```
use a decorator to get rank/dtype of `foo`
``` python
def detect_type(func):
     @wraps(func)
     def wrapper(*args, **kw):
         ret = func(*args, **kw)
         store_tracing_result(ret.dim(), ret.dtype)
         return ret
     return wrapper
```
2. import rank/dtype of `foo` via importer.
    After `importJitFunctionAsFuncOp` in `IValueImporter::importCompilationUnit`, we added rank&dtype to the `foo`
    Then, the IR looks like
    ```
    func @__torch__.IouOfModule.forward(%arg0: !torch.nn.Module<"__torch__.IouOfModule">, %arg1: !torch.tensor {torch.type_bound = !torch.vtensor <[1024,4],f32>}, %arg2: !torch.tensor {torch.type_bound = !torch.vtensor<[1024,4],f32>}) -> !torch.tensor {
        some IRs
        %1 = torch.extern "prim.PythonOp.foo"(%arg0, %0, %arg1) : (!torch.nn.Module<"__torch__.xxx">, !torch.tensor, !torch.tensor) -> !torch.tensor<[?,?],f32>
        some IRs
        return %2 : !torch.tensor
    }
    ```
    The torch.extern has a ranked output type
3. added `torch.extern` to represent the `foo`.
4. convert `torch.extern` to `std.call` (WIP)
   We are trying to do this conversion in TorchToStd pass and facing some problem of tensor<->memref. Is "converting `torch.extern` to `std.call` in TorchToStd" a correct way?

**Comment by powderluv** [comment]
Adding @ramiro050 @cathyzhyi @silvasean  for their thoughts.

**Comment by ds1231h** [comment]
Update:

> 4. convert torch.extern to std.call (WIP)

> We are trying to do this conversion in TorchToStd pass and facing some problem of tensor<->memref. Is "converting torch.extern to std.call in TorchToStd" a correct way?

This task has been completed. The `torch.extern` transformed to `std.call` successfully. 
The external C function is:
```
void _mlir_ciface_foo(Memref* output, Memref* input_1, Memref* input_2) {
   ...
}
```

Any feedback would appreciate a lot!

**Comment by silvasean** [comment]
This is basically a request for "custom ops". See this RFC: https://github.com/llvm/torch-mlir/issues/1462
Let's move discussion to the RFC.
