### ISSUE TITLE
Help with supporting algorithms that don't fit `linalg.generic`

### ISSUE THREAD

**Issue by ramiro050** [llvm/torch-mlir#510]
While working on the remaining ops in https://github.com/llvm/torch-mlir/issues/365, we've run into several ops that do not fit well into the `linalg.generic` form efficiently. One very simple example is doing a histogram operation of the form

```python
for bucket in buckets:
    count[bucket] += 1
```

There is a way to run this in `linalg.generic` by using two maps `(i, j) -> (i), (i, j) -> (j)`, however, this turns an `O(n)` implementation into an `O(n^2)` implementation.

The common limitation among the ops we are trying to implement is that we need to index and modify the output tensor in an order specified by the values in the input tensors, which cannot be done by `linalg.generic` with tensors because the tensors are immutable, as far as I can tell.[^1]

[^1]: If ops of this form are already efficiently implementable in `linalg`, I would appreciate any help on how to achieve such an implementation 😃 

What is the plan for supporting ops like these? @silvasean mentioned here https://github.com/llvm/torch-mlir/pull/478#discussion_r770003563 that the goal is to keep everything at the `linalg` level so that we can get really nice parallelization based on the backend. Is the plan to add more primitive ops to the `linalg` dialect or enhance the already existing ops to give a bit more flexibility? 

Summary of ops can't be effectively implemented with `linalg.generic`:

|   | status | op                              | note                                                   |
|---|--------|---------------------------------|--------------------------------------------------------|
| 1 | -      | `aten.index.put`                | scatter op Current `linalg.generic` implementation  [PR488](https://github.com/llvm/torch-mlir/pull/488)                  |
| 2 | -      | `aten.embedding_dense_backward` | histogram algorithm                                    |
| 3 | -      | `aten.cumsum`                        | scan op [PR](https://github.com/google/iree/pull/8020) |
| 4 | -     | `aten.segement_reduce`                        | scatter op [PR](https://github.com/llvm/torch-mlir/pull/523) |

**Comment by vivekkhandelwal1** [comment]
Out of the ops listed here [](https://github.com/llvm/torch-mlir/issues/365)

**Comment by vivekkhandelwal1** [comment]
In particular, ops like `embedding_dense_backward` require this kind of implementation.

**Comment by cathyzhyi** [comment]
I will make some adjustment to https://github.com/llvm/torch-mlir/pull/528 but the current patch is good enough to unblock anyone needs to work on these ops right away.  A `LowerAlgorithmicOps` pass will need to be added to lower TorchOps to Linalg_ext.

**Comment by silvasean** [comment]
We've implemented a few of these already with TMTensor. I think we can close this.
