### ISSUE TITLE
Tracking Torch-MLIR Lazy Tensor Core Backend

### ISSUE THREAD

**Issue by antoniojkim** [llvm/torch-mlir#556]
Creating this issue to inquire about and track the status of the Torch-MLIR LTC backend.

The LTC backend API has somewhat stabilized (with some probability of minor changes). So, I think getting experimental support for a Torch-MLIR specific LTC backend would be fruitful. If there is any work that has already been done for this, I'd like to get an idea of what's been done and what still needs doing. We can use this issue to track the work items.

Once we have a baseline for where things are, I would be happy to contribute to the effort of getting the Torch-MLIR LTC backend to a working state.

CC: @silvasean @ke1337 @emad-cb @henrytwo

**Comment by silvasean** [comment]
Hi Antonio,

I'm not aware of any code to plug into the LTC backend interface (buffer management, compilation callbacks, etc.) specifically for Torch-MLIR.

A few thoughts about my personal expectations for merging LTC support "officially" into Torch-MLIR:

- I want to avoid "multiplying an experiment by an experiment": Both Torch-MLIR and LTC are fairly young and experimental, so it becomes really confusing and difficult for users if we aren't careful. I don't want to have a complicated matrix of different Torch-MLIR vs PyTorch build configurations that we have to support from a CI/user perspective. I'd even be open to moving the entire Torch-MLIR project to canonically be built from source against the LTC staging branch if necessary to reduce divergence.

- I would like to include instructions / demo / CI (not necessarily inside Torch-MLIR proper) for an accessible OSS way to run "realistic" (for some definition) workloads. I think that [IREE](https://github.com/google/iree) is a good candidate for a backend for that (we have multiple engineers we can point towards that problem to help!). Our current RefBackend leaks too much memory / is too slow for even the most rudimentary training workload. But we also don't want to single-source on just the IREE backend -- we just want IREE to be a plug-in that is maintained out of tree, on equal footing to what any vendor would maintain.


There's a lot of open questions and challenges contained in those two points above. I think that some kind of minimal/hacky integration through IREE on a branch would be a really good starting point. Once we have that, we can bring into the room eyeballs from the LTC side, Torch-MLIR side, and stakeholders from a couple backends to see how to slice up and layer that for inclusion into mainline Torch-MLIR.

We haven't currently had the right mix of engineering resources available to get the ball rolling on that, and would be blessed if you could help :pray: We have engineers that can help with the IREE integration aspect if that's something you are unfamiliar with.

**Comment by antoniojkim** [comment]
> Both Torch-MLIR and LTC are fairly young and experimental, so it becomes really confusing and difficult for users if we aren't careful. I don't want to have a complicated matrix of different Torch-MLIR vs PyTorch build configurations that we have to support from a CI/user perspective.

That makes sense. I don't think this will be much of a concern though. It is all experimental at the moment, so I don't think we need to worry about different build configurations. I think we can make the hard assumption that we'll always be working off of the latest PyTorch `lazy_tensor_staging` branch and the latest Torch-MLIR `main`.

Once LTC is fully upstreamed into an official release of PyTorch, then we can start worrying about that. I think it would be reasonable to make a "release" of Torch-MLIR every time PyTorch releases a major version upgrade. Then, for each release we can worry about various build configurations. But again, this is still far into the future. I think its something to keep in mind, but not actively need to worry about.

> I'd even be open to moving the entire Torch-MLIR project to canonically be built from source against the LTC staging branch if necessary to reduce divergence.

I don't think this is necessary. I proposed on the discord thread that a `lazy_tensor_staging` branch (or perhaps a better name would be something like `torch_mlir_ltc_backend`) be creatd. We can make that branch of Torch-MLIR be canonically built against the LTC staging branch. That branch would also need to regularly fetch any new items from the `main` branch to reduce divergence like you mentioned.

> I would like to include instructions / demo / CI (not necessarily inside Torch-MLIR proper) for an accessible OSS way to run "realistic" (for some definition) workloads. I think that [IREE](https://github.com/google/iree) is a good candidate for a backend for that (we have multiple engineers we can point towards that problem to help!). Our current RefBackend leaks too much memory / is too slow for even the most rudimentary training workload. But we also don't want to single-source on just the IREE backend -- we just want IREE to be a plug-in that is maintained out of tree, on equal footing to what any vendor would maintain.

I don't have any experience working with IREE. So, when the time comes where we do need to start working on build configurations, help with the integration will definitely be needed.

> I think that some kind of minimal/hacky integration through IREE on a branch would be a really good starting point. Once we have that, we can bring into the room eyeballs from the LTC side, Torch-MLIR side, and stakeholders from a couple backends to see how to slice up and layer that for inclusion into mainline Torch-MLIR.

Not sure about the IREE integration just yet. I think we should at least have the skeleton of some rudimentary backend ready first. I have some ideas about that that I'd like to discuss with you (perhaps on the discord thread).

> We haven't currently had the right mix of engineering resources available to get the ball rolling on that, and would be blessed if you could help

This is definitely something I'm interested in seeing working sooner rather than later. So, I would be happy to get the ball rolling on this 😄

**Comment by ke1337** [comment]
Hi @silvasean and @antoniojkim , thanks for this conversation!

Could you comment on the roadmap for `torch/xla`, in the context of suggested IREE+torch-mlir+LTC? According to [LTC doc](https://github.com/pytorch/pytorch/tree/lazy_tensor_staging/lazy_tensor_core#lazy-tensors-core), seems torch/xla would move to LTC in [this effort](https://github.com/pytorch/xla/tree/asuhan/xla_ltc_plugin). However the `xla_ltc_plugin` branch's last commit was in Aug 9, 2021, which seems not being actively worked on. On the other hand, it seems TPU is missing from the [IREE architecture overview](https://github.com/google/iree#architecture-overview).

I am very interested in the architecture of IREE, but would also like to know if there are some designs/limitations for TPU in it.

**Comment by stellaraccident** [comment]
Sorry to disappoint, but IREE is not related to Google cloud TPUs (at least for a timeframe that will be remotely helpful for anything here).

**Comment by antoniojkim** [comment]
Plan is to stage work regarding the Torch-MLIR LTC backend on the following branch: https://github.com/llvm/torch-mlir/tree/torch_mlir_ltc_backend

**Comment by silvasean** [comment]
This is landed and pretty stable now. Closing this bug.
