### ISSUE TITLE
How to transform a non-const torch.aten.Bool to the condition of scf.if

### ISSUE THREAD

**Issue by ds1231h** [llvm/torch-mlir#560]
HI,

I'm not very sure if I accurately described my problem in the title.
I'm focusing on the control flow in torch-mlir, then I met such an error:
```
error: failed to legalize operation 'torch.aten.Bool.Tensor'
    %13 = torch.aten.Bool.Tensor %12 : !torch.vtensor<[?,?],i1> -> !torch.bool
```

which context IR is:
```
// some code for getting the CompareOp
%7 = linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel", "parallel"]} ins(%2, %3 : tensor<2x2xf32>, tensor<2x2xf32>) outs(%6 : tensor<2x2xi1>) {
 ^bb0(%arg2: f32, %arg3: f32, %arg4: i1): // no predecessors
 %19 = arith.cmpf ueq, %arg2, %arg3 : f32
 linalg.yield %19 : i1
 } -> tensor<2x2xi1>
 %8 = tensor.cast %7 : tensor<2x2xi1> to tensor<?x?xi1>
 %9 = torch_c.from_builtin_tensor %8 : tensor<?x?xi1> -> !torch.vtensor<[?,?],i1>
 %10 = torch.aten.Bool.Tensor %9 : !torch.vtensor<[?,?],i1> -> !torch.bool
 %11 = torch_c.to_i1 %10
 %12 = scf.if %11 -> (tensor<2x2xf32>) {
// some code for then block and else block of the scf.if
```

May I need to convert the `torch.aten.Bool.Tensor` to `torch_c.to_i1` immediatelly? 
Or May I need to do other transformations in `torchToStd` or `torchToScf`?

Any advice would be appreciated a lot!
@stellaraccident @silvasean @cathyzhyi 

Thanks!
Pei

**Comment by cathyzhyi** [comment]
You need to lower `torch.aten.Bool.Tensor` in TorchToLinalg similar as lowering of `AtenIntTensorOp` https://github.com/llvm/torch-mlir/blob/127c7d8e27ede211af77392b5277ba06fb515fb7/lib/Conversion/TorchToLinalg/TorchToLinalg.cpp#L2568. I am wondering how is the IR generated though because the aten ops converting Tensor to scalar usually expect input to be rank 0.

**Comment by ds1231h** [comment]
Hi Cathy,
Thanks for your advice!

> . I am wondering how is your IR snippet generated though because the aten ops converting Tensor to scalar usually expect input to be rank 0.

my `forward` function in pytorch is:
```
@export
    @annotate_args([
        None,
        ([2, 2], torch.float32, True),
        ([2, 2], torch.float32, True),
    ])
    def forward(self, x, y):
        if x == y:
            x = x - y
        else:
            x = x + y
        return torch.add(x, y)
```
So its rank seems <2x2xi1>.
And I add a `RewriteIfLikeOp` class for the control-flow problems in MaximizeValueSemantics.
For the detailed C++ code, find [here](https://github.com/ds1231h/torch-mlir/compare/main...ds1231h:control-flow-fix) please.

**Comment by cathyzhyi** [comment]
I see. `if x == y:`  would make Torchscript runtime give the following error
```
           if x == y:
        RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```
You probably want to use `if torch.ne(x, y).any()` instead.

**Comment by ds1231h** [comment]
Yes, thank you!

So I get such IR now:
```
    // some code for getting the CompareOp
    %7 = linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel", "parallel"]} ins(%2, %3 : tensor<2x2xf32>, tensor<2x2xf32>) outs(%6 : tensor<2x2xi1>) {
    ^bb0(%arg2: f32, %arg3: f32, %arg4: i1):  // no predecessors
      %20 = arith.cmpf ueq, %arg2, %arg3 : f32
      linalg.yield %20 : i1
    } -> tensor<2x2xi1>
    %8 = tensor.cast %7 : tensor<2x2xi1> to tensor<?x?xi1>
    %9 = torch_c.from_builtin_tensor %8 : tensor<?x?xi1> -> !torch.vtensor<[?,?],i1>
    %10 = torch.aten.all %9 : !torch.vtensor<[?,?],i1> -> !torch.vtensor<[1],i1>
    %11 = torch.aten.Bool.Tensor %10 : !torch.vtensor<[1],i1> -> !torch.bool
    %12 = torch_c.to_i1 %11
    %13 = scf.if %12 -> (tensor<2x2xf32>) {
    // some code for then block and else block of the scf.if
```
I guess I need to convert two aten ops including `torch.aten.all` and `torch.aten.Bool.Tensor`, is that right?
By the way, is there any example for `torch.aten.all`?

Thanks again!

**Comment by cathyzhyi** [comment]
> I guess I need to convert two aten ops including torch.aten.all and torch.aten.Bool.Tensor, is that right?
yea, that's correct.

> is there any example for torch.aten.all?
It's a reduction on all dimension op. You can search for `AtenMaxOp` in TorchToLinalg.cpp and follow the example.

**Comment by ds1231h** [comment]
Thank you!

**Comment by ds1231h** [comment]
Thanks for your help! @cathyzhyi 
Now the very basic demo of the if-control-flow has been done.
Find the detailed code here [ds1231h/control-flow-fix](https://github.com/ds1231h/torch-mlir/compare/main...ds1231h:control-flow-fix), please.
If we could start a discussion about the control flow supporting plan in discourse.llvm.org?
