### ISSUE TITLE
Failure while running heavydep tests 

### ISSUE THREAD

**Issue by sjarus** [llvm/torch-mlir#568]
I tried to follow the https://github.com/llvm/torch-mlir/blob/main/build_tools/torchscript_e2e_heavydep_tests/README.md to run the heavydep tests, specifically to obtain a BERT static model for TOSA backend. However, I see the following error following those steps: 

(heavydep_venv) $ ./tools/torchscript_e2e_test.sh --serialized-test-dir=serialized_tests --filter=BasicMtModule_basic
/media/home1/sursud01/torch-mlir/fork2/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/torchscript/framework.py:272: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ../aten/src/ATen/native/BinaryOps.cpp:607.)
  output = self.__wrapped__(*args, **kwargs)
python: /media/home1/sursud01/torch-mlir/fork2/torch-mlir/external/llvm-project/llvm/../mlir/include/mlir/IR/Types.h:251: U mlir::Type::cast() const [U = mlir::torch::Torch::ValueTensorType]: Assertion `isa<U>()' failed.
./tools/torchscript_e2e_test.sh: line 12: 22740 Aborted                 (core dumped) python -m e2e_testing.torchscript.main "$@"

I did pip install --upgrade -r requirements.txt before building torch-mlir within this venv. 

Having never tried this setup previously, I'd appreciate any input to get this working.

**Comment by pashu123** [comment]
@sjarus I have tried running the MiniLM model present here: https://github.com/llvm/torch-mlir/blob/main/build_tools/torchscript_e2e_heavydep_tests/minilm_sequence_classification.py this works fine. Not sure about BasicMt. 
/tools/torchscript_e2e_test.sh --serialized-test-dir=serialized_tests --filter=MiniLMSequenceClassification_basic

**Comment by sjarus** [comment]
You're right @pashu123 - I tried MiniLM just now and it does work fine. I'll continue my experiments with MiniLM. instead and leave this issue open for the moment. Thanks for your tip!

**Comment by cathyzhyi** [comment]
@sjarus `BasicMtModule_basic` is a machine translation model which we don't fully support yet.

**Comment by sjarus** [comment]
Thanks to both of you! The only hurdle now is I'm trying to make a static form of MiniLM - I tried [1, 384] for an input shape from prior BERT work but that triggers a coredump. @pashu123 did you use fixed shapes in some manner here ?

**Comment by cathyzhyi** [comment]
Hey Suraj, did you change the `test_input` to a different sentence? For the current input, the input shape would be [1,7].

**Comment by sjarus** [comment]
Thanks! I tried [1, 6] previously and that failed. [1, 7] worked for the default path and I'll use it for TOSA work.
