### ISSUE TITLE
Issue incorporating llvm change

### ISSUE THREAD

**Issue by nirvedhmeshram** [llvm/torch-mlir#589]
I am trying to incorporate this llvm change in torch-mlir
https://reviews.llvm.org/D118543
Essentially in this location OpTrait has become Trait and what NativeTrait means has changed
https://github.com/llvm/torch-mlir/blob/main/include/torch-mlir/Dialect/Torch/IR/TorchBase.td#L41-L49
So this snippet
```
class TorchOpTrait<string name> : NativeTrait<"", ""> {
  let trait = name;
  let cppNamespace = "::mlir::torch::Torch::OpTrait";
}

def HasValueSemantics : TorchOpTrait<"HasValueSemantics">;
def IsTrailingUnderscoreInplaceVariant
  : TorchOpTrait<"IsTrailingUnderscoreInplaceVariant">;
def AllowsTypeRefinement : TorchOpTrait<"AllowsTypeRefinement">;
```
gives the following error
```
[5/622] Building dialects/_torch_ops_gen.py...
FAILED: tools/torch-mlir/python/dialects/_torch_ops_gen.py /home/nirvedh/torch-mlir/build/tools/torch-mlir/python/dialects/_torch_ops_gen.py
cd /home/nirvedh/torch-mlir/build && /home/nirvedh/torch-mlir/build/bin/mlir-tblgen -gen-python-op-bindings -bind-dialect=torch -I /home/nirvedh/torch-mlir/python -I/home/nirvedh/torch-mlir/build/include -I/home/nirvedh/torch-mlir/external/llvm-project/llvm/include -I/home/nirvedh/torch-mlir/external/llvm-project/llvm/../mlir/include -I/home/nirvedh/torch-mlir/build/tools/mlir/include -I/home/nirvedh/torch-mlir/include -I/home/nirvedh/torch-mlir/build/tools/torch-mlir/include /home/nirvedh/torch-mlir/python/torch_mlir/dialects/TorchBinding.td --write-if-changed -o tools/torch-mlir/python/dialects/_torch_ops_gen.py -d tools/torch-mlir/python/dialects/_torch_ops_gen.py.d
Included from /home/nirvedh/torch-mlir/python/torch_mlir/dialects/TorchBinding.td:14:
Included from /home/nirvedh/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchOps.td:13:
Included from /home/nirvedh/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchTypes.td:13:
/home/nirvedh/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchBase.td:49:1: error: Record `AllowsTypeRefinement' does not have a field named `dependentTraits'!

def AllowsTypeRefinement : TorchOpTrait<"AllowsTypeRefinement">;
```

**Comment by stellaraccident** [comment]
I think you want to change:

```
class TorchOpTrait<string name> : NativeOpTrait<name> {
  let cppNamespace = "::mlir::torch::Torch::OpTrait";
}
```

**Comment by nirvedhmeshram** [comment]
Thanks, that fixed that issue, next one I am having is with this change
https://github.com/llvm/llvm-project/commit/12bfd159b7602fee776d4a0d4b2f1193e875fd35

**Comment by nirvedhmeshram** [comment]
Gives this kind of error 
```In file included from /home/nirvedh/torch-mlir/lib/Dialect/Torch/IR/TorchDialect.cpp:48:
/home/nirvedh/torch-mlir/build/tools/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchTypes.cpp.inc:251:7: error: use of undeclared identifier 'parser'; did you mean 'parse'?
  if (parser.parseLess())```

**Comment by stellaraccident** [comment]
On mobile and not able to look closely. But it has been a *very busy* few weeks for llvm changes. Thanks for working on it.

I recall making similar changes in IREE but can't remember the details. I can check later, but in the meantime, you are welcome to look through our last few integrates: https://github.com/google/iree/pulls?q=is%3Apr+is%3Aclosed+integrate

**Comment by stellaraccident** [comment]
Also, don't hesitate to ask on the #mlir channel of the llvm discord. Folks there typically know exactly what each change is.

**Comment by nirvedhmeshram** [comment]
Thank you Stella. Yes I have asked on the mlir discord. I have also opend this WIP so that folks can see where exactly I am failing
https://github.com/llvm/torch-mlir/pull/590
Current issue which I see the IREE llvm bump also had to make a change for is adding
```
let hasCustomAssemblyFormat = 1;
```
and removing the `let Parser` , `let Printer`
I get this error
```
/home/nirvedh/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchTypes.td:50:33: error: Value 'hasCustomAssemblyFormat' unknown!
  let hasCustomAssemblyFormat = 1;
```

**Comment by stellaraccident** [comment]
@jpienaar Any ideas?

**Comment by jpienaar** [comment]
So we didn't have to make the hasCustomAssemblyFormatChange, we just did it to reduce warnings. One can do that as separate step. Do you have branch with the above fixes until this point?

**Comment by jpienaar** [comment]
If you look at the change LLVM side, something like

```
ParseResult parseConstantIntOp(...
```

should become

```
ParseResult ConstantIntOp::parse(...
```

on Ops defined. hasCustomAssemblyFormat is for Ops and not Types or Attributes so only change Ops defined (printer & parser is unchanged for Types & Attributes).

**Comment by nirvedhmeshram** [comment]
I have fixed issue 1, the operands of all the cast style ops are flipped now. Was easy once I realized that.

**Comment by nirvedhmeshram** [comment]
Currently it builds but some tests are failing. Here is an example
```
(mlir_venv) nirvedh@nirvedh-bench-image:~/torch-mlir$ ./build/bin/torch-mlir-opt test/Conversion/TorchToLinalg/basic.mlir -convert-torch-to-linalg -split-input-file -verify-diagnostics
within split at test/Conversion/TorchToLinalg/basic.mlir:1 offset :26:8: error: unexpected error: failed to legalize operation 'torch.aten.mm' that was explicitly marked illegal
  %0 = torch.aten.mm %arg0, %arg1 : !torch.vtensor<[?,?],f32>, !torch.vtensor<[?,?],f32> -> !torch.vtensor<[?,2],f32>
       ^
```

**Comment by jpienaar** [comment]
And yeah the cast ops allowed for being built with either type or operand first and the latter form got removed, good catch (so I've been walking through these the last two weeks elsewhere :-), but difficult to remember what changed when and where).

**Comment by nirvedhmeshram** [comment]
Thanks for the debugging techniques insight was not aware of them

**Comment by nirvedhmeshram** [comment]
There is also this issue
```
Load new dialect in Context builtin
Load new dialect in Context builtin
Load new dialect in Context torch
Load new dialect in Context std
Load new dialect in Context cf
Load new dialect in Context arith
Load new dialect in Context linalg
Load new dialect in Context affine
Load new dialect in Context math
Load new dialect in Context memref
Load new dialect in Context tensor
Load new dialect in Context complex
Load new dialect in Context torch_c

//===-------------------------------------------===//
Legalizing operation : 'builtin.func'(0x6b482c0) {
  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'builtin.func -> ()' {
Trying to match "(anonymous namespace)::ConvertElementwiseOp"
    ** Failure : not a supported elementwise op
"(anonymous namespace)::ConvertElementwiseOp" result 0
  } -> FAILURE : pattern failed to match

  * Pattern : 'builtin.func -> ()' {
Trying to match "(anonymous namespace)::ConvertReductionOp"
    ** Failure : not a supported reduce op
"(anonymous namespace)::ConvertReductionOp" result 0
  } -> FAILURE : pattern failed to match

  * Pattern : 'builtin.func -> ()' {
Trying to match "(anonymous namespace)::ConvertAtenScalarToTensorLike"
    ** Failure : not a supported Scalar to Tensor like op
"(anonymous namespace)::ConvertAtenScalarToTensorLike" result 0
  } -> FAILURE : pattern failed to match
} -> FAILURE : no matched legalization pattern
//===-------------------------------------------===//
```

**Comment by stellaraccident** [comment]
If all else fails, I believe Sean is back from vacation tomorrow :)

As Jacques says, there is probably a legality step missing somewhere. The assert op moved from std->cf and conversion targets tended to be set up a little too loosely based on std.

**Comment by nirvedhmeshram** [comment]
Great, I was able to solve the `cf.assert` issue by adding it to the conversion target, but stumped with the `bultin.func` failing, documentation says `As such, this dialect is implicitly loaded in every MLIRContext, and available directly to all users of MLIR.`

**Comment by stellaraccident** [comment]
Probably a red herring and not related directly to func but trying to legalize something it contains.

**Comment by nirvedhmeshram** [comment]
Thank you all, the PR is merged now
