### ISSUE TITLE
resnet18 is able to pass using the commits of torch-mlir before Jan 28 but fails after that day. 

### ISSUE THREAD

**Issue by zzy82518996** [llvm/torch-mlir#592]
New torch-mlir is not able to pass the "python examples/torchscript_resnet18_e2e.py" test.
I think this is mainly due to the commit 'e1b3e5bc92decafc7d99cd093e47ec909c62d0fa'
Below is the error message.
![Screen Shot 2022-02-14 at 12 29 20 PM](https://user-images.githubusercontent.com/9006099/153915494-1b0eb1bb-4e4b-498a-9ae6-1cbe011ec8b6.png)
How to solve this issue ?

**Comment by cathyzhyi** [comment]
Hey it's because torch version change. Please update your local torch version to the latest nightly build.

**Comment by zzy82518996** [comment]
Thanks, but I use the "pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html" command from PyTorch website to build the latest nightly build, but still got the same error ?

**Comment by zzy82518996** [comment]
Oh, I see. Thanks. I use python3.6, the official indeed suggest python3.7 or higher. I will upgrade my python version and give it a try again. Thanks.

**Comment by zzy82518996** [comment]
BTW, is there any instruction on how to dump the mlir after different passes from the end to end example ? I did not find the relative instruction.

**Comment by cathyzhyi** [comment]
You will need failed test to see the instructions. https://github.com/llvm/torch-mlir/blob/756b75fb2d996747483d24c1a6bfa3eadd80ec11/python/torch_mlir_e2e_test/utils.py#L54. If you would like to look at mlir dump for passed runs you can save the initial ir by using this patch and then use the `torch-mlir-opt` command
```
diff --git a/python/torch_mlir_e2e_test/utils.py b/python/torch_mlir_e2e_test/utils.py
index 4d41ecf1..52d08153 100644
--- a/python/torch_mlir_e2e_test/utils.py
+++ b/python/torch_mlir_e2e_test/utils.py
@@ -32,6 +32,19 @@ def run_pipeline_with_repro_report(module,
         # Lower module in place to make it ready for compiler backends.
         with module.context:
             pm = PassManager.parse(pipeline)
+            if "torchscript-module-to-torch-backend-pipeline" in pipeline:
+              filename = module_name + '_frontend.mlir'
+            elif "torch-backend-to-linalg-on-tensors-backend-pipeline" in pipeline:
+              filename = module_name + '_midend.mlir'
+            elif "refback-munge-calling-conventions" in pipeline:
+              filename = module_name + '_backend.mlir'
+            else:
+              assert("unhandled pipeline name in run_pipeline_with_repro_report")
+
+            filename = os.path.join("put your path here",
+                                    filename)
+            with open(filename, 'w') as f:
+                f.write(asm_for_error_report)
```

**Comment by zzy82518996** [comment]
I see, will give it a try, thanks !

**Comment by cathyzhyi** [comment]
@zzy82518996 is it ok to close this issue?

**Comment by zzy82518996** [comment]
Sure, thanks for the reply.
