### ISSUE TITLE
Incomplete shape inference using RefineTypes

### ISSUE THREAD

**Issue by henrytwo** [llvm/torch-mlir#601]
I tried piping the MLIR provided below through `torch-mlir-opt -torch-refine-types -torch-refine-public-return` to infer tensor shapes but ran into a few issues:

`torch.aten.mm` (example below) had question marks appear in its output shape, rather than an explicit shape. During a separate test, I found that ` torch.operator "aten.binary_cross_entropy_backward"(...)` did not get annotated with any output shape information at all -- not even rank data.

However, I did notice that a few ops, such as `torch.aten.permute`, _did_ get annotated with the correct output shapes.

Is there anything that can be done to improve the shape inference? I'm wondering if this behaviour is intentional, or if some operations are missing support.

Might be related to: https://github.com/llvm/torch-mlir/issues/415

Input:
```
module {
  func @main(%arg0: !torch.vtensor<[1337,10],f32>) -> !torch.tensor {
    %0 = torch.tensor_static_info_cast %arg0 : !torch.vtensor<[1337,10],f32> to !torch.vtensor
    %1 = torch.copy.to_tensor %0 : !torch.tensor
    %int1 = torch.constant.int 1
    %int0 = torch.constant.int 0
    %2 = torch.prim.ListConstruct %int1, %int0 : (!torch.int, !torch.int) -> !torch.list<!torch.int>
    %int1_0 = torch.constant.int 1
    %int0_1 = torch.constant.int 0
    %3 = torch.prim.ListConstruct %int1_0, %int0_1 : (!torch.int, !torch.int) -> !torch.list<!torch.int>
    %4 = torch.aten.permute %1, %3 : !torch.tensor, !torch.list<!torch.int> -> !torch.tensor
    %5 = torch.aten.mm %1, %4 : !torch.tensor, !torch.tensor -> !torch.tensor
    return %5 : !torch.tensor
  }
}
```

Output:
```
module {
  func @main(%arg0: !torch.vtensor<[1337,10],f32>) -> !torch.vtensor<[?,?],f32> {
    %0 = torch.tensor_static_info_cast %arg0 : !torch.vtensor<[1337,10],f32> to !torch.vtensor<[1337,10],f32>
    %1 = torch.copy.to_tensor %0 : !torch.tensor<[1337,10],f32>
    %int1 = torch.constant.int 1
    %int0 = torch.constant.int 0
    %2 = torch.prim.ListConstruct %int1, %int0 : (!torch.int, !torch.int) -> !torch.list<!torch.int>
    %int1_0 = torch.constant.int 1
    %int0_1 = torch.constant.int 0
    %3 = torch.prim.ListConstruct %int1_0, %int0_1 : (!torch.int, !torch.int) -> !torch.list<!torch.int>
    %4 = torch.aten.permute %1, %3 : !torch.tensor<[1337,10],f32>, !torch.list<!torch.int> -> !torch.tensor<[10,1337],f32>
    %5 = torch.aten.mm %1, %4 : !torch.tensor<[1337,10],f32>, !torch.tensor<[10,1337],f32> -> !torch.tensor<[?,?],f32>
    %6 = torch.tensor_static_info_cast %5 : !torch.tensor<[?,?],f32> to !torch.tensor
    %7 = torch.copy.to_vtensor %5 : !torch.vtensor<[?,?],f32>
    return %7 : !torch.vtensor<[?,?],f32>
  }
}
```

**Comment by ramiro050** [comment]
Hi @henrytwo, I actually just started working on adding static shape information to `aten.mm`, so by the end of today that should work! In the case of `torch.operator "aten.binary_cross_entropy_backward"(...)`, the problem with this op is that it is currently not yet supported by `torch-mlir`, so there is no way of knowing what the result type should be for it. (The same applies to any op that appears as `torch.operator "name.of.op"(...)`) In general, the way to improve the static information is by adding static calculations to the `refine-types` pass in this file:

https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/Torch/Transforms/RefineTypes.cpp

Happy to help with any other questions you have

**Comment by cathyzhyi** [comment]
On a side note, technically things are supposed to work with dynamic shapes. Only rank should be required. However, due to some limitations with certain ops we sometimes do need more static shape info.

**Comment by henrytwo** [comment]
>  so by the end of today that should work!

Thanks for the speedy response -- this will be helpful!

>  the problem with this op is that it is currently not yet supported by torch-mlir, so there is no way of knowing what the result type should be for it. (The same applies to any op that appears as torch.operator "name.of.op"(...))

Are there plans to eventually add static shape information to _all_ supported ops? I'm trying to lower to a custom dialect which requires static tensor shapes.

**Comment by silvasean** [comment]
> Are there plans to eventually add static shape information to _all_ supported ops? I'm trying to lower to a custom dialect which requires static tensor shapes.

Yes, we intend to support that, and have a patch in progress to do so.

**Comment by silvasean** [comment]
The new system supports this. See https://github.com/llvm/torch-mlir/blob/main/docs/shape_lib.md
