### ISSUE TITLE
[RFC] Need to add a scatter-like op in Linalg_Ext/TMTensor

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#609]
Hi @silvasean @cathyzhyi, 

I am working on the lowering of `aten.embedding_dense_backward` op. For the implementation of this op, I have two requirements that can be fulfilled with the infra available in torch-mlir:
1.)
```
for (i = 0; i < indices.size(); i++)
        count[indices[i]]++
```
2.)
```
for (i = 0; i < indices.size(); i++) {
        for (j = 0; j < grad_out.size()[1]; j++) {
                grad_out[indices[i], j] += grad[i, j] * scale
        }
}
```

We have a `scatter` op in linalg_ext that is closest to our needs, but the problem with the `scatter` op is, in case of the repeated indices, it results in a race condition because the tiled implementation of `scatter` op doesn't take care of the repeated indices. Therefore, we need to add a `scatter-like` op in `Linalg_ext/TMTensor` to handle the input with repeated indices.

I am creating this issue to get your views on this. I have also created an issue in IREE https://github.com/google/iree/issues/8318 to get their opinion as well.

**Comment by cathyzhyi** [comment]
The IREE side of change is merged https://github.com/google/iree/pull/8365. @vivekkhandelwal1 will help to port the changes to TMTensor dialect.

**Comment by vivekkhandelwal1** [comment]
I am closing this issue with this commit https://github.com/llvm/torch-mlir/commit/5dbace239b754f08811d4d10e61104178fadcedf.
