### ISSUE TITLE
[RFC] Lowering  aten::_index_put_impl_ into tm_tensor.scatter op

### ISSUE THREAD

**Issue by erman-gurses** [llvm/torch-mlir#616]
(https://github.com/llvm/torch-mlir/pull/614)

**Comment by silvasean** [comment]
> We will need a new pass called something like `DecomposeOrConvertTorchOp` to convert Torch ops to a mixed of torch and aten ops.

Do you mean a mix of torch and TMTensor ops? I think this pass would naturally be the scope of a ConvertTorchToTMTensor pass.

**Comment by cathyzhyi** [comment]
sry, I meant a mixed of torch and linalg/tmtensor ops. 

> ConvertTorchToTMTensor

We have another pass called lowerAlgorithmicOps https://github.com/llvm/torch-mlir/pull/574 which lowers algorithmic torch ops to linalg and tm_tensor ops. I feel calling `ConvertTorchToTMTensor` for this new pass would cause confusion as it is not explicit the torch can also be decomposed to Torch ops.

**Comment by silvasean** [comment]
I left a comment in #574. I think that there should be LowerAlgorithmicOps (similar to DecomposeComplexOps) as a Torch->Torch lowering. Then ConvertTorchToTMTensor which happens in backends (i.e. after the Torch backend contract, just before ConvertTorchToLinalg).

**Comment by cathyzhyi** [comment]
> I left a comment in #574. I think that there should be LowerAlgorithmicOps (similar to DecomposeComplexOps) as a Torch->Torch lowering. Then ConvertTorchToTMTensor which happens in backends (i.e. after the Torch backend contract, just before ConvertTorchToLinalg).

Ha, I see. There seems to be confusion about passes naming. I updated my comments. Thanks for clarifying this!

**Comment by silvasean** [comment]
Starting with the 1D version of this and emitting a clear diagnostic for the unsupported cases seems like a good incremental first step.

**Comment by cathyzhyi** [comment]
closed by #650
