### ISSUE TITLE
no member named 'toGraphFunction' in namespace 'torch::jit'

### ISSUE THREAD

**Issue by yhz5256** [llvm/torch-mlir#617]
[2669/2720] Building CXX object tools/torch-mlir/python/torch_mlir/dialects/...er/jit_ir/csrc/CMakeFiles/TorchMLIRJITIRImporter.dir/function_importer.cpp.o
FAILED: tools/torch-mlir/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/CMakeFiles/TorchMLIRJITIRImporter.dir/function_importer.cpp.o 
/usr/bin/clang++  -DMLIR_PYTHON_PACKAGE_PREFIX=torch_mlir. -DTorchMLIRJITIRImporter_EXPORTS -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/torch-mlir/python/torch_mlir/dialects/torch/importer/jit_ir/csrc -I../python/torch_mlir/dialects/torch/importer/jit_ir/csrc -I/usr/include/python3.8 -Iinclude -I../external/llvm-project/llvm/include -I../external/llvm-project/llvm/../mlir/include -Itools/mlir/include -I../include -Itools/torch-mlir/include -Itools/torch-mlir/python -isystem /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.8/dist-packages/torch/include -isystem /usr/local/cuda-11.2/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -g -fPIC -fvisibility=hidden   -D_GLIBCXX_USE_CXX11_ABI=0 -U__GXX_ABI_VERSION -D__GXX_ABI_VERSION=1011 '-DPYBIND11_COMPILER_TYPE="_gcc"' -frtti -fexceptions -Wno-unused-value -Wno-covered-switch-default -std=c++14 -MD -MT tools/torch-mlir/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/CMakeFiles/TorchMLIRJITIRImporter.dir/function_importer.cpp.o -MF tools/torch-mlir/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/CMakeFiles/TorchMLIRJITIRImporter.dir/function_importer.cpp.o.d -o tools/torch-mlir/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/CMakeFiles/TorchMLIRJITIRImporter.dir/function_importer.cpp.o -c /home/yang/Source/torch-mlir/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/function_importer.cpp
/home/yang/Source/torch-mlir/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/function_importer.cpp:67:28: error: no member named 'toGraphFunction' in namespace 'torch::jit'
      context, torch::jit::toGraphFunction(*function).graph()->block(),
               ~~~~~~~~~~~~^
1 error generated.
[2682/2720] Building CXX object tools/torch-mlir/python/CMakeFiles/TorchMLIR..._mlir.dso.dir/__/external/llvm-project/mlir/lib/Bindings/Python/IRCore.cpp.o
ninja: build stopped: subcommand failed.

**Comment by cathyzhyi** [comment]
there seems to be a similar issue https://github.com/llvm/torch-mlir/issues/450 in the past. Can you try to update your pytorch to the latest nightly build?

**Comment by cathyzhyi** [comment]
@yhz5256 I am closing the issue as it should be resolved by the above suggestions. Please feel free to reopen if there is any further questions. Thanks!
