### ISSUE TITLE
Fix RefineType for ops like aten.log

### ISSUE THREAD

**Issue by cathyzhyi** [llvm/torch-mlir#651]
The existing code assumes the result tensor type is the same as input type for  a few aten ops like `log`, `exp`, `erf`. See https://github.com/llvm/torch-mlir/blob/486f95e84f587d020ba789b071b12f890510f1a1/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L221-L235
This incorrect. The result  tensor of  these ops should always have the default dtype rather than the same as the input type. E2E tests for none default dtype input need to be added.

**Comment by binfoo1993** [comment]
Hi @cathyzhyi,

I am Ph.D. student at George Washington University, who is interested in ML compiler.

I want to work on this issue.

**Comment by cathyzhyi** [comment]
@binfoo1993 Hey Qiang, thanks for your interest in the project! You could refer to https://github.com/llvm/torch-mlir/wiki/Torch-ops-E2E-implementation for some basic information. Please let me know if you have further questions.

**Comment by binfoo1993** [comment]
> @binfoo1993 Hey Qiang, thanks for your interest in the project! You could refer to https://github.com/llvm/torch-mlir/wiki/Torch-ops-E2E-implementation for some basic information. Please let me know if you have further questions.

Thanks for assigning this issue to me!

**Comment by binfoo1993** [comment]
Hi @cathyzhyi,

I did some source code reading, trying to understand this right:

- For torch ops such as `exp`, `log`, `cos` etc, the output tensor's dtype could be different with input's. For example 
```python
import torch as th
a = th.IntTensor([1, 2, 3, 4])
print(th.exp(a).dtype) # torch.float32
```
- But existing codes assume they are of the same dtype.

So we should:

-  Find all ops satisfying this property, use another `if` branch to handle the type analysis.
- No matter what the input dtype is, always use `float32` for the result tensor. But the size should still be the same.
- Add e2e test for input tensor with dtypes not `float32`.

Besides, I have one concern:

- I notice our codes also handle `float64` dtype, for this input dtype, the output should also be of `float64`.
```python
import torch as th
a = th.DoubleTensor([1, 2, 3, 4])
print(th.exp(a).dtype) # torch.float64
```

Please let me know if I understand this wrong!

**Comment by cathyzhyi** [comment]
@binfoo1993 yea, your understanding above is correct! And thanks for pointing out about special case of `float64` which I missed in the issue description. A heads-up that RefineType.cpp will be changed soon by #654 which should make this task easier as you will only need to handle the dtype but not the shape.

**Comment by binfoo1993** [comment]
@cathyzhyi cool! Then should I wait until the change is committed then I can start my coding?

**Comment by cathyzhyi** [comment]
> @cathyzhyi cool! Then should I wait until the change is committed then I can start my coding?

yea, it's merged already.

**Comment by binfoo1993** [comment]
Ok, great!

I will change the Dtype handling logic for the following Ops:

- AtenTanhOp
- AtenExpOp 
- AtenSinOp
- AtenCosOp
- AtenSigmoidOp
- AtenReciprocalOp 
- AtenLogOp
- AtenSqrtOp
- AtenLog2Op 
- AtenRsqrtOp 
- AtenErfOp

Please let me know if I miss any Ops in the list.

**Comment by silvasean** [comment]
Fixed in https://github.com/llvm/torch-mlir/pull/687
