### ISSUE TITLE
`aten::native_layer_norm` 2nd and 3rd results not implemented correctly

### ISSUE THREAD

**Issue by silvasean** [llvm/torch-mlir#665]
When revamping the shape library, I noticed that the shape function for `torch.aten.native_layer_norm` was not implemented correctly for the 2nd and 3rd results. I tried fixing the buggy shape function, but it seems that the TorchToLinalg lowering broke if I did that (the shape function actually calculates the wrong rank).

I left some comments (including a correct version of the code) in shape_lib_gen.py about the issue and expected behavior. 
https://github.com/llvm/torch-mlir/blob/a5fe0cf06308af3a372e40ae927995f7920fb55d/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py#L766

Our testing didn't catch this because for some reason the test was only checking the first result, rather than all 3:
https://github.com/llvm/torch-mlir/blob/a5fe0cf06308af3a372e40ae927995f7920fb55d/e2e_testing/torchscript/norm_like.py#L194

To fix this bug, you should be able to uncomment the correct code linked above in shape_lib_gen.py, and then debug what TorchToLinalg is doing wrong.

**Comment by cathyzhyi** [comment]
I think this is covered in https://github.com/llvm/torch-mlir/pull/570 by @gprateek93.  Prateek, could you split  https://github.com/llvm/torch-mlir/pull/570 and check in the part that fixes this issue?

**Comment by gprateek93** [comment]
> I think this is covered in #570 by @gprateek93. Prateek, could you split #570 and check in the part that fixes this issue?

Sure.

**Comment by gprateek93** [comment]
Refer to this PR: [#674](https://github.com/llvm/torch-mlir/pull/674)
