### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wm901115nwpu** [llvm/torch-mlir#666]
torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp:24:10: fatal error: 'ATen/native/quantized/packed_params.h' file not found

**Comment by cathyzhyi** [comment]
should be fixed by https://github.com/llvm/torch-mlir/pull/662

**Comment by cathyzhyi** [comment]
oh, sry, this is because of #662 and you need to update your pytorch to the latest nightly build to work.

**Comment by cathyzhyi** [comment]
oh, sry, this is because of #662 and you need to update your pytorch to the latest nightly build to work.

**Comment by cathyzhyi** [comment]
@wm901115nwpu I am closing the issue as it should be resolved by the above suggestions. Please feel free to reopen if there is any further questions. Thanks!
