### ISSUE TITLE
[RFC] Adding the implementation of aten::max_pool2d_with_indices_backward

### ISSUE THREAD

**Issue by erman-gurses** [llvm/torch-mlir#672]
Hi @cathyzhyi and @silvasean

I received this implementation from @gpetters94  and I am currently working on it. In the last discussion with George, he summarized the steps that should be followed:

1. Flatten gradient output to a 1d tensor
2. Fill with zeroes
3. Loop through the indices, inserting 1 into the zeroed-out tensor at each point
4. Expand to the original size and return

All the steps are mentioned here as well as discussions: 
https://github.com/llvm/torch-mlir/pull/607

I guess I can use scatter operation mentioned in the link below for the Step 3
https://github.com/llvm/torch-mlir/pull/650

Do you have any comments or suggestions for this plan?

**Comment by erman-gurses** [comment]
@vivekkhandelwal1 Can you please share your opinion about this RFC? Particularly, feasibility of using `TMTensor::ScatterOp`. Last time we have a short discussion about it. What would be the problem converting 3D indices tensor to 2D tensor? Are we losing the functionality indices when we do that? Can you please elaborate them?

**Comment by cathyzhyi** [comment]
closed by https://github.com/llvm/torch-mlir/pull/739
