### ISSUE TITLE
Adding shape information for Torch MLIR LTC Backend

### ISSUE THREAD

**Issue by henrytwo** [llvm/torch-mlir#727]
After https://github.com/llvm/torch-mlir/pull/725 lands, the next goal is to try to add shape information to the output MLIR.

`lazy::Node` contains tensor shape information (retrieved by calling `shapes()`); however, this information is not retained when it's converted to a `jit::Node`. ([This](https://github.com/henrytwo/torch-mlir/blob/2de2f1182452b6d070d2ed484804c056436215b9/python/torch_mlir/csrc/base_lazy_backend/mlir_node_lowering.cpp#L193) shows that the only thing extracted from the `lazy::Node` during lowering is its symbol)

It also looks like there is nothing on the MLIR generation side for adding shape information (as far as I could see).

I don't think there is anything on the JIT side that enables storing tensor shape information, which might make this more difficult. My immediate thought is to try to map `lazy::Node -> MlirOperation` to insert shape information, but that doesn't feel like the most proper way to do this.

@silvasean, do you have any thoughts or ideas on how to proceed with this?

cc: @antoniojkim @ke1337

**Comment by silvasean** [comment]
`jit::Value`'s of `c10::TensorType` should be able to hold a shape.

**Comment by henrytwo** [comment]
Ah that's good to hear -- I'll investigate what we can do upstream

**Comment by henrytwo** [comment]
I opened an issue on the PyTorch side here: https://github.com/pytorch/pytorch/issues/75217

**Comment by henrytwo** [comment]
Closing this issue now that we have a PR open: https://github.com/llvm/torch-mlir/issues/727
