### ISSUE TITLE
Issue with buffers when lowering slices of statically shaped tensors

### ISSUE THREAD

**Issue by dan-garvey** [llvm/torch-mlir#750]
@dan-garvey after my fix in https://github.com/llvm/torch-mlir/pull/721 there still seems to be some issue with affine maps in IouOfModuleStatic when lowering linalg to buffers -- can you take a look and add that test with the fix?

_Originally posted by @silvasean in https://github.com/llvm/torch-mlir/issues/716#issuecomment-1083632134_

Haven't managed to carve out time for this yet, so adding it as an issue and self-assigning so I don't lose track of it.

**Comment by silvasean** [comment]
IouOfModuleStatic works now. Closing.
