### ISSUE TITLE
[RFC] Add lowering for aten::_adaptive_avg_pool2d_backward

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#763]
Hi,

I am working on adding the lowering for `aten::_adaptive_avg_pool2d_backward` op. The algorithm of the op is as follows:
```
# Input: [C, inH, inW]
# Grad_Output: [C, outH, outW]
# Result: [C, inH, inW]
for c in range(C):
    for oh in range(outH):
        ih0 = floor[(oh * inH) / outH]
        ih1 = ceil[{(oh + 1) * inH} / outH]
        kh = ih1 - ih0
        for ow in range(outW):
            iw0 = floor[(ow * inW) / outW]
            iw1 = ceil[{(ow + 1) * inW} / outW]
            kw = iw1 - iw0
            for ih in range(ih0, ih1):
                for iw in range(iw0, iw1):
                    # result tensor is initialized with zeros
                    result[c, (ih * inW) + iw] += grad_output[c, (oh * outW) + ow] / kh /kw
```

Since the accumulation is happening here, the lowering for this op has to be added via the TMTensor dialect. But I am not sure whether the current infra can support this kind of loop structure. I would like to hear others' views on this.

**Comment by silvasean** [comment]
The general case of adaptive avg pool is quite difficult I think. The only case we handle for forward was the 1x1 result case, so this can probably be simplified in that scenario. Can you show the loop nest with that simplification applied?

**Comment by vivekkhandelwal1** [comment]
The way result size is computed for adaptive avg pool forward, and backward is quite different. Here, the result size is extracted from the input tensor size. If we support only the 1x1 case, it means the input tensor has to be of size `[N, C, 1, 1]`, which I don't think will solve any purpose even if implemented. Also, I don't think the 1x1 result case will simplify this algo since the loops are not dependent on the `inH, inW`. We have to find some other way of doing this.

**Comment by vivekkhandelwal1** [comment]
For the 1x1 result case, the simplified algo will look like this:
```
# Input: [C, inH=1, inW=1]
# Grad_Output: [C, outH, outW]
# Result: [C, 1, 1]
for c in range(C):
    for oh in range(outH):
        for ow in range(outW):
            # result tensor is initialized with zeros
            result[c, 0] += grad_output[c, (oh * outW) + ow]
```

**Comment by silvasean** [comment]
I would think that for the 1x1 case, the backward op would be very trivial. Basically:

```
Forward result: [C, 1, 1]
Gradient of the output: [C, 1, 1]
Gradient of the input: [C, W, H]
```

The forward calculation is something like `avg(x) = sum(x) / x.size()` in that case, so basically the backward function is the same as the backward pass of a global summation (modulo a data-independent factor computed from the size), which is very trivial.

**Comment by vivekkhandelwal1** [comment]
> I would think that for the 1x1 (forward) case, the corresponding backward op would be very trivial. Basically:
> 
> ```
> Forward result: [C, 1, 1]
> Gradient of the output: [C, 1, 1]
> Gradient of the input: [C, W, H]
> ```
> 
> The forward calculation is something like `avg(x) = sum(x) / x.size()` in that case, so basically the backward function is the same as the backward pass of a global summation (modulo a data-independent factor computed from the size), which is very trivial.

Then, should we implement this for the 1x1 case only?

**Comment by silvasean** [comment]
I think we only have 1x1 implemented for the forward op, so I doubt we have a real model that uses non-1x1. So I think we should only implement the 1x1 case for now.

**Comment by vivekkhandelwal1** [comment]
> I think we only have 1x1 implemented for the forward op, so I doubt we have a real model that uses non-1x1. So I think we should only implement the 1x1 case for now.

There are multiple models like Alexnet and Vgg16 for which we require to add support for cases other than 1x1. For example, Alexnet has a requirement of 6x6, and Vgg16 requires 7x7. So, we have to extend the `adaptive_avg_pool2d` implementation to support these cases. The exact requirement for the backward one is still not known to me.

**Comment by vivekkhandelwal1** [comment]
> I don't know what the adaptive_avg_pool2d op does in the non-1x1 case even for the forward pass -- I assume it does some kind of average filtering, but the exact behavior is not obvious to me, especially when the result size is not a divisor of the input size. Can you look into it?

Okay, I will take a look at it.

**Comment by zwang92** [comment]
- Just like @vivekkhandelwal1 comments that "Vgg16 for which we require to add support for cases other than 1x1".

When I try to lower torchvision.models.vgg16 by 'torchscript-module-to-torch-backend-pipeline,torch-backend-to-linalg-on-tensors-backend-pipeline' , it fails with error " [Lower to Linalg Fail]  'torch.aten.adaptive_avg_pool2d' legalize failed".
It is found the fail is due to ConvertAtenAdaptiveAvgPool2dOp only supporting output_size with H and W both equal to constant 1 as following source code .
![image](https://user-images.githubusercontent.com/6805661/165295084-b81bf193-160b-4894-962e-34ed33562ff9.png)

- I am wondering why there is "H and W both equal to constant 1 "  limitation , can i remove this limitation ?

thank you

**Comment by vivekkhandelwal1** [comment]
> * I am wondering why there is "H and W both equal to constant 1 "  limitation , can i remove this limitation ?

Hi @zwang92, the reason behind the `H and W both equal to constant 1` limitation is that the implementation of the `torch.aten.adaptive_avg_pool2d` op currently supports only [1, 1] output size. You cannot just remove this limitation because the behavior of the op for the output size other than [1, 1] is different than that of the output size [1, 1]. Therefore to remove this limitation, i.e., support output sizes other than [1, 1], the implementation must be modified.

**Comment by zwang92** [comment]
@vivekkhandelwal1  thanks a lot for your answer.
I am newcomer of MLIR. About your comments "support output sizes other than [1, 1], the implementation must be modified"  , do you mean the source code in ConvertAtenAdaptiveAvgPool2dOp::matchAndRewrite as following picture must be modified to support output sizes other than [1, 1]  even though the code taking H and W into account ?

![image](https://user-images.githubusercontent.com/6805661/165301855-125afc2f-5a45-4a30-bd60-e45e53c1b39b.png)

thank you

**Comment by zwang92** [comment]
@vivekkhandelwal1  thanks a lot for your answer.
I am newcomer of MLIR. About your comments "support output sizes other than [1, 1], the implementation must be modified"  , do you mean the source code in ConvertAtenAdaptiveAvgPool2dOp::matchAndRewrite as following picture must be modified to support output sizes other than [1, 1]  even though the code taking H and W into account ?

![image](https://user-images.githubusercontent.com/6805661/165301855-125afc2f-5a45-4a30-bd60-e45e53c1b39b.png)

thank you

**Comment by vivekkhandelwal1** [comment]
@zwang92 Yes the source code in `ConvertAtenAdaptiveAvgPool2dOp::matchAndRewrite` has to be modified. The current code only adds all the elements and divides them by `HxW`, which is 1 in this case. The original definition of the op is available at: https://pytorch.org/docs/stable/generated/torch.nn.AdaptiveAvgPool2d.html?highlight=adaptive#torch.nn.AdaptiveAvgPool2d

**Comment by silvasean** [comment]
There are 4 values: W, H, which are the input width and height, and also output_size() which contains outW, outH -- the unimplemented part is supportin outW and outH != 1.
