### ISSUE TITLE
`GeFloatModule_basic` test has started to fail. 

### ISSUE THREAD

**Issue by powderluv** [llvm/torch-mlir#807]
Unexpected outcome summary:

****** Failed tests - 1 tests
    FAIL - "GeFloatModule_basic"
        @ trace item #0 - call to "forward"
        @ output of call to "forward"
        ERROR: value (False) is not equal to golden value (True)

Summary:
    Passed: 466
    Failed: 1
    Expectedly Failed: 8

https://github.com/llvm/torch-mlir/runs/6198970107?check_suite_focus=true

**Comment by gpetters94** [comment]
I've dug around and it looks like the problem is arising at the lowering for `AtenFloatTensorOp`. I'm going to put a PR up with a fix for the GeFloat tests while I dig deeper into the issue.
