### ISSUE TITLE
Torchscript_resnet18.py example fails

### ISSUE THREAD

**Issue by susowl** [llvm/torch-mlir#810]
Hello
I have installed torch miler into docker using  pre-built snapshot from readme.md and tried to run torchscript_resnet18.py.
But unfortunately it fails with following output:

PyTorch prediction
[('Labrador retriever', 70.65678405761719), ('golden retriever', 4.988343715667725), ('Saluki, gazelle hound', 4.477432727813721)]
Killed

**Comment by silvasean** [comment]
I was unable to reproduce this. Can you share more details about how to reproduce?

**Comment by susowl** [comment]
Here is my Dockerfile:
FROM python:3.9
RUN python -m pip install --upgrade pip
RUN pip install --pre torch-mlir torchvision -f https://github.com/llvm/torch-mlir/releases --extra-index-url https://download.pytorch.org/whl/nightly/cpu
RUN mkdir ~/samples && cd ~/samples && wget https://raw.githubusercontent.com/llvm/torch-mlir/main/examples/torchscript_resnet18.py

**Comment by silvasean** [comment]
I followed your Docker instructions and it worked for me:
```
PyTorch prediction
[('Labrador retriever', 70.6567611694336), ('golden retriever', 4.98834228515625), ('Saluki, gazelle hound', 4.477431297302246)]
torch-mlir prediction
[('Labrador retriever', 70.65674591064453), ('golden retriever', 4.9883222579956055), ('Saluki, gazelle hound', 4.477451324462891)]
```

Do you maybe have a ulimit or something which is killing the process?

**Comment by susowl** [comment]
Looks like it is VSCode. Sample works normal until i install python extension on VSCode and start example from it.
And with VSCode server and python extension I can't run example even from command line.
Thanks!
