### ISSUE TITLE
generate_serialized_tests.sh is failing because of hf_big_bird and timm_resnest

### ISSUE THREAD

**Issue by cathyzhyi** [llvm/torch-mlir#813]
The 2 tests are introduced by https://github.com/llvm/torch-mlir/pull/783. @pashu123 is working on a fix.

**Comment by silvasean** [comment]
Hi folks, as a matter of policy, we should revert commits that introduce failures ("roll back"), rather than "fix forward". Fixes often take longer than we expect ;) and we want the CI as green as possible, to avoid masking other failures that arise.

**Comment by pashu123** [comment]
@silvasean Here's the PR: https://github.com/llvm/torch-mlir/pull/814. Sorry for the late fix. Also, we can't obtain the inference graph of gpt2, big bird and fb/bart through the recursive scripting and functorch's aot should be used in that case.
