### ISSUE TITLE
Need support for non-unit group size for `aten.convolution` op

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#823]
The current implementation of `aten.convolution` op supports only group_size=1. The support for non_unit group size is required for many torch benchmark models like mnasnet1_0, mobilenet_v3_large, mobilenet_v2, resnext50_32x4d, timm_regnet. The support for group_size other than 1 is required to get these models run e2e. More details of the support required are available at: https://docs.google.com/spreadsheets/d/15PcjKeHZIrB5LfDyuw7DGEEE8XnQEX2aX8lm8qbxV8A/edit#gid=1219968311&range=A14:H14.

**Comment by cathyzhyi** [comment]
I had a local patch from a long time ago https://github.com/cathyzhyi/mlir-npcomp/commit/556f6244bd2e0e785179d4b267fcc7e06c6d7d22. The codebase has diverged a lot since then but might be used as a reference.

**Comment by vivekkhandelwal1** [comment]
@gpetters94, please take a look at https://github.com/cathyzhyi/mlir-npcomp/commit/556f6244bd2e0e785179d4b267fcc7e06c6d7d22.

**Comment by gpetters94** [comment]
PR's up at #858.

**Comment by vivekkhandelwal1** [comment]
Hi @gpetters94, did you fix the above-mentioned issue?
