### ISSUE TITLE
CeilFloatModule_basic CI failure after latest nightly pytorch updates

### ISSUE THREAD

**Issue by cathyzhyi** [llvm/torch-mlir#842]
This test [CeilFloatModule_basic](https://github.com/llvm/torch-mlir/blob/28be6511d253c216e5243b906a1bb777f693e5e6/python/torch_mlir_e2e_test/test_suite/scalar.py#L130) failed with error 
```
ERROR: expected a value of type `torch.Tensor` but got `int`. 
```
The baseline believes the result should a Tensor but the last 2 operations are:
```
    %4 = torch.aten.ceil.float %3 : !torch.float -> !torch.int loc(#loc3)
    return %4 : !torch.int loc(#loc0)
```
Didn't get to the bottom of the problem. 
[MLIR dump](https://gist.github.com/c855501a8356f978a7d9a4ad9879996d) and [torchscript graph dump](https://gist.github.com/5e991f708eb120b8ef61dc4307537022)

**Comment by silvasean** [comment]
Hi Yi, can we pin the CI to a known-good version of PyTorch while investigating this if there isn't a quick fix?

**Comment by cathyzhyi** [comment]
@silvasean I submitted a workaround in https://github.com/llvm/torch-mlir/pull/843

**Comment by makslevental** [comment]
It's probably this same scalar promotion bug that just got patched in upstream pytorch https://github.com/pytorch/pytorch/issues/74400#event-6574874903

**Comment by silvasean** [comment]
@makslevental -- is the new behavior the "expected" behavior then?

**Comment by cathyzhyi** [comment]
> python scalars go in, python scalars come out
So `torch.ops.aten.ceil(1.5)` should expect scalar output rather than Tensor right?

**Comment by makslevental** [comment]
> > python scalars go in, python scalars come out
> 
> So `torch.ops.aten.ceil(1.5)` should expect scalar output rather than Tensor right?

@cathyzhyi [this is the PR](https://github.com/pytorch/pytorch/pull/76835) that fixed the big I linekd to earlier. Like I said I haven't dug deep on it, but high-level that's the behaviour I would expect.

**Comment by cathyzhyi** [comment]
I see. Thanks for confirming. Seems `torch.ops.aten.ceil(1.5)` still returns a Tensor even with that fix. Let me open another issue upstream.

**Comment by cathyzhyi** [comment]
I opened an issue https://github.com/pytorch/pytorch/issues/77223 upstream.

**Comment by silvasean** [comment]
It is working again.
