### ISSUE TITLE
[RFC] Add support for non-unit output size for `aten::adaptive_avg_pool2d` op

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#847]
Hi,

I am working on adding the support for non-unit output size for `aten::adaptive_avg_pool2d` op. The support for output sizes: [6,6] and [7,7] is required for `vgg16` and `alexnet` models.  The algorithm of the op is as follows:

```
# Input: [C, inH, inW]
# Output Size: [outH, outW]
# Result: [C, outH, outW]
for c in range(C):
    for oh in range(outH):
        ih0 = floor[(oh * inH) / outH]
        ih1 = ceil[{(oh + 1) * inH} / outH]
        kh = ih1 - ih0
        for ow in range(outW):
            iw0 = floor[(ow * inW) / outW]
            iw1 = ceil[{(ow + 1) * inW} / outW]
            kw = iw1 - iw0
            sum = 0
            for ih in range(ih0, ih1):
                for iw in range(iw0, iw1):
                    sum += input[c, (ih * inW) + iw]

            result[c, (oh * outW) + ow]  = sum / kh / kw
```
I don't see a way to do this in `TorchToLinalg` or `TMTensor`. Even with the `linalg::genericOp` we can implemented a perfectly nested loop but the algorithm is in the form of an imperfect loop-nest. Also, the behaviour of the op is not only determined by the output size but also the input shape, which makes this op more complex. 

I would like to get suggestions from the community regarding the feasibility of the implementation of this op with the current infrastructure available in the torch-mlir.

**Comment by silvasean** [comment]
you could use linalg.index and tensor.extract in the payload

**Comment by silvasean** [comment]
no. I mean using linalg.index to get the current induction variable and then use some arithmetic + tensor.extract to perform the load from the input.

Unless the number of iterations in `for ih in range(ih0, ih1)` varies on each iteration... (is `ceil[{(ow + 1) * inW} / outW] - floor[(ow * inW) / outW]` a constant?). If it isn't a constant, then I don't think this is a good algorithm. I would look at what the GPU kernels in PyTorch do in practice -- I doubt they have such divergent loops.

**Comment by vivekkhandelwal1** [comment]
> is ceil[{(ow + 1) * inW} / outW] - floor[(ow * inW) / outW] a constant?

No. The number of iterations for ih, iw varies in each iteration.

**Comment by vivekkhandelwal1** [comment]
> I would look at what the GPU kernels in PyTorch do in practice -- I doubt they have such divergent loops.

They do this: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/AdaptiveAveragePooling.cu#L50-L103. It's similar to the cpu implementation.

**Comment by silvasean** [comment]
Interesting. Is the case we are interested in divisible? That would make things simpler. Another option would be to limit this to certain static shape scenarios, but I'd like to avoid that.

**Comment by vivekkhandelwal1** [comment]
Closed with https://github.com/llvm/torch-mlir/pull/855.
