### ISSUE TITLE
ERROR: No matching distribution found for torch-mlir

### ISSUE THREAD

**Issue by geg00** [llvm/torch-mlir#848]
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Chip:	Apple M1 Max
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	32 GB
  System Firmware Version:	7459.101.3
  OS Loader Version:	7459.101.3
  Serial Number (system):	FVQWJWV42G
  Hardware UUID:	E5D06237-B789-574E-9187-8EEBED74CE1A
  Provisioning UDID:	00006001-001C71442EF8801E
  Activation Lock Status:	Enabled

(mlir_venv) (base) gerardogarcia@Gerardos-MacBook-Pro ~ % pip install --pre torch-mlir torchvision -f https://github.com/llvm/torch-mlir/releases --extra-index-url https://download.pytorch.org/whl/nightly/cpu   

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cpu
Looking in links: https://github.com/llvm/torch-mlir/releases
ERROR: Could not find a version that satisfies the requirement torch-mlir (from versions: none)
ERROR: No matching distribution found for torch-mlir

**Comment by powderluv** [comment]
can you please check what version of Python you have ? We currently only have wheels for 3.9 and will add 3.10 soon.

**Comment by geg00** [comment]
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by powderluv** [comment]
Can you please try with the latest release .451 or later ?

**Comment by geg00** [comment]
(mlir_venv) (base) gerardogarcia@Gerardos-MacBook-Pro ~ % pip install -U https://github.com/llvm/torch-mlir/releases/download/snapshot-20220514.451/torch-1.12.0.dev20220514-cp39-none-macosx_10_9_x86_64.whl
Collecting torch==1.12.0.dev20220514
  Downloading https://github.com/llvm/torch-mlir/releases/download/snapshot-20220514.451/torch-1.12.0.dev20220514-cp39-none-macosx_10_9_x86_64.whl (134.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 MB 26.2 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.12.0.dev20220514 typing-extensions-4.2.0

(mlir_venv) (base) gerardogarcia@Gerardos-MacBook-Pro mlir % pip install Pillow 
(mlir_venv) (base) gerardogarcia@Gerardos-MacBook-Pro mlir % pip install requests     

(mlir_venv) (base) gerardogarcia@Gerardos-MacBook-Pro mlir % python torchscript_resnet18.py
Traceback (most recent call last):
  File "/Users/gerardogarcia/mlir/torchscript_resnet18.py", line 15, in <module>
    import torch_mlir
ModuleNotFoundError: No module named 'torch_mlir'

😐

Any other ideas?

**Comment by geg00** [comment]
I don't know if you are still interested but I tried with the new release and still the same issue

(mlir_venv) (base) gerardogarcia@Gerardos-MacBook-Pro torch-mlir % pip install -U --pre https://github.com/llvm/torch-mlir/releases/download/snapshot-20220517.456/torch-1.12.0.dev20220517-cp39-none-macosx_10_9_x86_64.whl
Collecting torch==1.12.0.dev20220517
  Downloading https://github.com/llvm/torch-mlir/releases/download/snapshot-20220517.456/torch-1.12.0.dev20220517-cp39-none-macosx_10_9_x86_64.whl (135.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.2/135.2 MB 4.2 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in /Users/gerardogarcia/mlir_venv/lib/python3.9/site-packages (from torch==1.12.0.dev20220517) (4.2.0)
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 1.12.0.dev20220516
    Uninstalling torch-1.12.0.dev20220516:
      Successfully uninstalled torch-1.12.0.dev20220516
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.13.0.dev20220516 requires torch==1.12.0.dev20220516, but you have torch 1.12.0.dev20220517 which is incompatible.
Successfully installed torch-1.12.0.dev20220517
(mlir_venv) (base) gerardogarcia@Gerardos-MacBook-Pro torch-mlir % python examples/torchscript_resnet18.py 
Traceback (most recent call last):
  File "/Users/gerardogarcia/mlir/torch-mlir/examples/torchscript_resnet18.py", line 15, in <module>
    import torch_mlir
ModuleNotFoundError: No module named 'torch_mlir'
(mlir_venv) (base) gerardogarcia@Gerardos-MacBook-Pro torch-mlir %

**Comment by powderluv** [comment]
I see you are installing the x86 binaries in your env. And also you have both your conda env and your pip env active. 

I would suggest start with a deactivated conda. Type `conda deactivate` so you don't see `(base)` in your prompt. 

and if you do a `which python3.9` what does it output ?  

Here is my output:

````
anush@MacStudio github % which python3.9
/opt/homebrew/bin/python3.9
anush@MacStudio github % python3.9 -m venv torch-mlir-test
anush@MacStudio github % source torch-mlir-test/bin/activate
(torch-mlir-test) anush@MacStudio github % python -m pip install --upgrade pip
Requirement already satisfied: pip in ./torch-mlir-test/lib/python3.9/site-packages (22.0.4)
Collecting pip
  Using cached pip-22.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-22.1
(torch-mlir-test) anush@MacStudio github % pip install --pre torch-mlir torchvision -f https://github.com/llvm/torch-mlir/releases --extra-index-url https://download.pytorch.org/whl/nightly/cpu

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cpu
Looking in links: https://github.com/llvm/torch-mlir/releases
Collecting torch-mlir
  Downloading https://github.com/llvm/torch-mlir/releases/download/snapshot-20220518.459/torch_mlir-20220518.459-cp39-cp39-macosx_11_0_universal2.whl (168.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.5/168.5 MB 15.6 MB/s eta 0:00:00
Collecting torchvision
  Using cached torchvision-0.12.0-cp39-cp39-macosx_11_0_arm64.whl (1.2 MB)
Collecting torch==1.12.0.dev20220518
  Downloading https://download.pytorch.org/whl/nightly/cpu/torch-1.12.0.dev20220518-cp39-none-macosx_11_0_arm64.whl (47.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.8/47.8 MB 23.7 MB/s eta 0:00:00
Collecting numpy
  Using cached numpy-1.22.3-cp39-cp39-macosx_11_0_arm64.whl (12.8 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-9.1.1-cp39-cp39-macosx_11_0_arm64.whl (2.8 MB)
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2022.5.18-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.2/155.2 kB 1.7 MB/s eta 0:00:00
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Installing collected packages: urllib3, typing-extensions, pillow, numpy, idna, charset-normalizer, certifi, torch, requests, torchvision, torch-mlir
Successfully installed certifi-2022.5.18 charset-normalizer-2.0.12 idna-3.3 numpy-1.22.3 pillow-9.1.1 requests-2.27.1 torch-1.12.0.dev20220518 torch-mlir-20220518.459 torchvision-0.12.0 typing-extensions-4.2.0 urllib3-1.26.9
(torch-mlir-test) anush@MacStudio github % 
````

**Comment by powderluv** [comment]
Fixed. Closing this out. Please reopen if you still have problems.
