### ISSUE TITLE
How to add lowering for ops with string operands?

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#866]
Hi, I am working on adding the lowering for torch ops with string operands required for the vision transformer. But I can't find a way to work with non-constant torch strings. For example for op `aten.len.str`, `aten.find` the string operands are not constant. In such a case, how to operate on the string operands?

**Comment by silvasean** [comment]
Can you describe what the model is doing with strings? I don't think we will be supporting runtime strings in our core flow.

**Comment by vivekkhandelwal1** [comment]
> Can you describe what the model is doing with strings? I don't think we will be supporting runtime strings in our core flow.

Here's the IR dump of the vision transformer which uses these ops: https://gist.github.com/3d6ce52e66dfd308831b6661ea245c41.

**Comment by silvasean** [comment]
Can you describe what it is doing with the strings and paste valid IR?

**Comment by vivekkhandelwal1** [comment]
> Can you describe what it is doing with the strings and paste valid IR (otherwise it's harder to read and tools don't work on it)?

I haven't gone through the whole IR, so I don't know what it's doing. I am adding the vision transformer test, which is failing and hence got this IR dump. By valid IR, do you mean the input IR to the passes?

**Comment by silvasean** [comment]
Yes, something that passes the verifier.

**Comment by vivekkhandelwal1** [comment]
> Yes, something that passes the verifier.

Hi @silvasean, this is the link to the valid input IR: https://gist.github.com/vivekkhandelwal1/358f1689d5184ce32c43f89f1984c493.

**Comment by silvasean** [comment]
At a glance, it looks like it is related to error handling and special casing for the "cpu" device. Both should get folded away and never reach our backends.
