### ISSUE TITLE
[RFC] Add lowering for `aten::_native_multi_head_attention` op

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#904]
Hi,

I am working on adding the lowering for `aten::_native_multi_head_attention` op. The CPP implementation of the op in PyTorch is available at: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/transformers/attention.cpp#L285. https://github.com/tensorflow/addons/blob/v0.17.0/tensorflow_addons/layers/multihead_attention.py#L22-L298, this is the TensorFlow implementation of multi_head_attention in python.

I want to ask with the current infra available in torch-mlir, can we add the lowering for this op? If yes, should it be added in `TorchToLinalg` or `TorchToTMTensor`?

**Comment by vivekkhandelwal1** [comment]
@silvasean @ramiro050 @cathyzhyi, I would be happy if you guys can share your views on this issue.

**Comment by silvasean** [comment]
I think should just go into DecomposeComplexOps -- AFAIK it's just a manual fusion of a few matmuls or something.
