### ISSUE TITLE
error: unhandled: could not import node:  = prim::Store

### ISSUE THREAD

**Issue by ashay** [llvm/torch-mlir#907]
The code for converting from TorchScript into the Torch dialect fails for the following (contrived but minimal) program because `NodeImporter::importNode()` does not handle `c10::prim::Store`.  Is this a reasonable use case to add `Load` and `Store` ops to the Torch dialect, or is there an easier/better/shorter solution?  Thanks!

---

```python
import torch
import torch_mlir

class Inner(object):
    @classmethod
    def foo(cls):
        this_dict = {}
        this_dict["key"] = 42
        return this_dict

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.inner = Inner()
    def forward(self, data):
        return data

torch_model = Model()
torch_data = torch.tensor([0, 1, 2, 3], dtype=torch.bfloat16)
output_type = torch_mlir.OutputType.TORCH
torch_mlir.compile(torch_model, [torch_data], output_type)
```

```
> python3 code.py
error: unhandled: could not import node:  = prim::Store[name="cls"](%cls) # code.py:6:12
...
```

cc: @silvasean

**Comment by silvasean** [comment]
Yep, I think we just need to import it (it should go away during lowering since we cannot lower it to backends).

This would help https://github.com/llvm/torch-mlir/issues/832 too!

**Comment by ashay** [comment]
Fixed as part of PR https://github.com/llvm/torch-mlir/pull/983.
