### ISSUE TITLE
[RFC] Add support to tag tensors that will be converted to custom quantized numerics

### ISSUE THREAD

**Issue by nithinsubbiah** [llvm/torch-mlir#922]
**Motivation:** Hardware vendors use custom numeric format(s) that is pertinent to their own hardware as one of the ways to obtain stand-out performance. When lowering a model from the front-end framework (ex: PyTorch) there isn't a straight forward to add information about this custom numeric format that can be realized on the back end. Adding this support in Torch-MLIR would be a great benefit to lower from PyTorch to MLIR ecosystem with self-contained information about tensor formats.

**Proposal:** The idea is to add an attribute to the op that contains the string of tensor format and its properties.

For example, I'd like to add support for block floating point format. A model containing a matmul op in Torch dialect with the proposed attribute would be as follows:
```
func.func @forward(%arg0: !torch.vtensor<[5,64],f32>) -> !torch.vtensor<[5,4],f32> {
    %0 = torch.vtensor.literal(dense<[-0.109009251, 0.0110379457, 0.12105535, 0.037429437]> : tensor<4xf32>) : !torch.vtensor<[4],f32>
    %1 = torch.vtensor.literal(dense<"42D83BD"> : tensor<4x64xf32>) : !torch.vtensor<[4,64],f32>
    %2 = torch.aten.linear %arg0, %1, %0 {quantization_type: "bfp", precision: 8, block_size: 64, block_dim=-1, rounding="nearest"}: !torch.vtensor<[5,64],f32>, !torch.vtensor<[4,64],f32>, !torch.vtensor<[4],f32> -> !torch.vtensor<[5,4],f32>
    return %2 : !torch.vtensor<[5,4],f32>
  }
 ```

**Comment by silvasean** [comment]
No, we aren't adding any custom attributes to ops -- it is already hard enough to manage the zoo of ops and their exact semantics. Adding sideband attributes to the mix which causes the semantics to diverge from the upstream behavior isn't going to be sustainable.

**Comment by nithinsubbiah** [comment]
Do you have any suggestions on how we can achieve this?

**Comment by silvasean** [comment]
I'm still trying to understand better the workflow and details of the use case. Let's iterate in https://github.com/llvm/torch-mlir/issues/910 to get a better understanding of the needs here and then come back to this.

**Comment by zincnode** [comment]
> **Motivation:** Hardware vendors use custom numeric format(s) that is pertinent to their own hardware as one of the ways to obtain stand-out performance. When lowering a model from the front-end framework (ex: PyTorch) there isn't a straight forward to add information about this custom numeric format that can be realized on the back end. Adding this support in Torch-MLIR would be a great benefit to lower from PyTorch to MLIR ecosystem with self-contained information about tensor formats.
> 
> **Proposal:** The idea is to add an attribute to the op that contains the string of tensor format and its properties.
> 
> For example, I'd like to add support for block floating point format. A model containing a matmul op in Torch dialect with the proposed attribute would be as follows:
> 
> ```
> func.func @forward(%arg0: !torch.vtensor<[5,64],f32>) -> !torch.vtensor<[5,4],f32> {
>     %0 = torch.vtensor.literal(dense<[-0.109009251, 0.0110379457, 0.12105535, 0.037429437]> : tensor<4xf32>) : !torch.vtensor<[4],f32>
>     %1 = torch.vtensor.literal(dense<"42D83BD"> : tensor<4x64xf32>) : !torch.vtensor<[4,64],f32>
>     %2 = torch.aten.linear %arg0, %1, %0 {quantization_type: "bfp", precision: 8, block_size: 64, block_dim=-1, rounding="nearest"}: !torch.vtensor<[5,64],f32>, !torch.vtensor<[4,64],f32>, !torch.vtensor<[4],f32> -> !torch.vtensor<[5,4],f32>
>     return %2 : !torch.vtensor<[5,4],f32>
>   }
> ```

Hi, do you only know what `%1 = torch.vtensor.literal(dense<"42D83BD"> : tensor<4x64xf32>) : !torch.vtensor<[4,64],f32>` stands for? I also got hex strings like this. But I don't know how to parse it to get the data inside the tensor. 

See here for a more detailed description: #931

**Comment by silvasean** [comment]
Closing this, as the issues have been moved to other issues or will come up as part of separate quantization efforts.
