### ISSUE TITLE
[RFC] Add lowering for `aten::native_group_norm` op 

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#976]
Hi all!

I am working on adding the lowering for `aten::group_norm` op. Currently, I require the lowering to only support the cases where the `number of groups = 1`. From here (https://towardsdatascience.com/what-is-group-normalization-45fe27307be7#:~:text=On%20the%20other%20hand%2C%20when%20G%20%3D%201%2C%20GN%20becomes%20LN) and many other places it can be inferred that when no. of groups = 1, GN reduces to the LN. I am trying to decompose the GN op into the LN op, but there are two issues:
1.) The LN has an additional parameter namely `normalized_shape`.
2.) The `weight` and `bias` in the case of GN are of `shape = {C}` where C is the number of channels, while in the case of LN the shape of `weight` and `bias` is equal to the shape of normalized_shape. 

Regarding these two issues, I have two questions:
1.) What should be the value of `normalized_shape` when we decompose the GN into LN?
2.) SInce the shapes of `weight` and `bias` in the case of GN are different from the ones in LN, should we broadcast the `weight` and `bias` to match the shape of `normalized_shape`?

The PyTorch implementation of GN is available at: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/group_norm_kernel.cpp#L27-L84, and that of LN is available at: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/layer_norm_kernel.cpp#L25-L87.

`Note: GN = Group Norm, LN = Layer Norm`

**Comment by silvasean** [comment]
Didn't Chilli provide a decomposition?

**Comment by vivekkhandelwal1** [comment]
> Didn't Chilli provide a decomposition?

Yes, he provided the decomposition but the issue was created before that. I will close this once I test the working of that.
