### ISSUE TITLE
Unable to lower down nn.Embedding and nn.EmbeddingBag to LinalgDialect

### ISSUE THREAD

**Issue by JoshuaQSH** [llvm/torch-mlir#987]
Hi guys,

Recently I am trying to lower down the transformer-based model to MLIR Linalg Dialect. But got the error down there:

```shell
Exception:
Lowering Torch Backend IR -> Linalg-on-Tensors Backend IR failed with the following diagnostics:
error: 'linalg.generic' op expected operand rank (1) to match the result rank of indexing_map #0 (2)
note: see current operation: %10 = "linalg.generic"(%0, %9) ({
^bb0(%arg1: i64, %arg2: f32):
  %13 = "arith.index_cast"(%arg1) : (i64) -> index
  %14 = "linalg.index"() {dim = 1 : i64} : () -> index
  %15 = "arith.constant"() {value = 0 : index} : () -> index
  %16 = "arith.constant"() {value = 4 : index} : () -> index
  %17 = "arith.index_cast"(%arg1) : (i64) -> index
  %18 = "arith.cmpi"(%17, %16) {predicate = 2 : i64} : (index, index) -> i1
  "cf.assert"(%18) {msg = "index must be smaller than dim size"} : (i1) -> ()
  %19 = "arith.constant"() {value = 0 : i64} : () -> i64
  %20 = "arith.cmpi"(%arg1, %19) {predicate = 5 : i64} : (i64, i64) -> i1
  "cf.assert"(%20) {msg = "index must be larger or equal to 0"} : (i1) -> ()
  %21 = "tensor.extract"(%2, %13, %14) : (tensor<4x2xf32>, index, index) -> f32
  "linalg.yield"(%21) : (f32) -> ()
}) {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"], operand_segment_sizes = dense<1> : vector<2xi32>} : (tensor<3xi64>, tensor<?x?xf32>) -> tensor<?x?xf32>
```

In this example, I just simply builded up an `nn.Embedding()` module and try to implement `torch_mlir.compile()`, which seemed it was able to capture the torchscript and transform it to TORCH dialect but was stuck in further lowering to Linalg. I have tried using `torch.jit.trace()` instead but got `TypeError: forward() takes 2 positional arguments but 4 were given`.

I then ran `torch-mlir-opt -pass-pipeline='torch-backend-to-linalg-on-tensors-backend-pipeline' /tmp/Embedding.mlir
` to see more details, and it showed:
```shell
/tmp/Embedding.mlir:3:3: error: custom op 'func.func' is unknown
  func.func @forward(%arg0: !torch.vtensor<[3],si64> loc(unknown)) -> !torch.vtensor<[3,2],f32> {
  ^
```
Is it because torch-mlir still lacks support for the embedding op? If so, how can I begin to add the new op? I am pretty new to both torch-mlir and mlir, might need some guides to begin with.

Thanks in advance :)

**Comment by ramiro050** [comment]
Hi @JoshuaQSH,

I had run into a similar issue a couple of weeks ago. Can you check if you have this commit https://github.com/llvm/torch-mlir/commit/246c2df65a01998b2159fec79675a0631f1f0218 in your branch?

**Comment by ramiro050** [comment]
> `nn.EmbeddingBag` still remained unsolved, which I got `ValueError: Arg annotations should have one entry per function parameter (including self).` while compiling `nn.EmbeddingBag`.

This seems to be an error with an annotation at the python level, probably in `torch.compile`. Can you post the script you're using that is leading to the `nn.EmbeddingBag` error?

**Comment by JoshuaQSH** [comment]
> > `nn.EmbeddingBag` still remained unsolved, which I got `ValueError: Arg annotations should have one entry per function parameter (including self).` while compiling `nn.EmbeddingBag`.
> 
> This seems to be an error with an annotation at the python level, probably in `torch.compile`. Can you post the script you're using that is leading to the `nn.EmbeddingBag` error?

My testing code here:
```python
import torch
import torch.nn as nn
import torch_mlir
from typing import List

embeddedbag = nn.EmbeddingBag(4, 2, mode='sum')
input_e = torch.tensor([1, 2, 3], dtype=torch.long)
offsets = torch.tensor([0])

print("EmbeddingBag: \n", embeddedbag(input_e, offsets))


module = torch_mlir.compile(embeddedbag,
    list([input_e, offsets]),
    output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,
    use_tracing=False)

print("LINALG_ON_TENSORS OutputType\n", module.operation.get_asm(large_elements_limit=10))
```
And got the following error:
```shell 
Traceback (most recent call last):
  File "embedding.py", line 18, in <module>
    module = torch_mlir.compile(embeddedbag,
  File "/home/shenghao/anaconda3/envs/torchrec/lib/python3.8/site-packages/torch_mlir/__init__.py", line 140, in compile
    class_annotator.annotateArgs(
ValueError: Arg annotations should have one entry per function parameter (including self).
```

**Comment by ramiro050** [comment]
The issue is that `embeddedbag` takes three inputs, but only two are given as example inputs in `torch_mlir.compile`. By running `print(torch.jit.script(embeddedbag).graph)`,

```python
graph(%self : __torch__.torch.nn.modules.sparse.EmbeddingBag,
      %input.1 : Tensor,
      %offsets.1 : Tensor?,
      %per_sample_weights.1 : Tensor?):
  %16 : Function = prim::Constant[name="embedding_bag"]()
  %11 : str = prim::Constant[value="sum"]() # /usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.10/site-packages/torch/nn/modules/sparse.py:386:56
  %10 : bool = prim::Constant[value=0]() # /usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.10/site-packages/torch/nn/modules/sparse.py:386:31
  %9 : float = prim::Constant[value=2.]() # /usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.10/site-packages/torch/nn/modules/sparse.py:385:46
  %8 : NoneType = prim::Constant() # /usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.10/site-packages/torch/nn/modules/sparse.py:385:31
  %weight : Tensor = prim::GetAttr[name="weight"](%self)
  %17 : Tensor = prim::CallFunction(%16, %input.1, %weight, %offsets.1, %8, %9, %10, %11, %10, %per_sample_weights.1, %10, %8) # /usr/local/google/home/ramiroleal/torch-mlir/venv-torch-mlir/lib/python3.10/site-packages/torch/nn/modules/sparse.py:384:15
  return (%17)
```

we can see that the signature is `(nn.Module, tensor, tensor?, tensor?)`.

That signature leads to another problem because currently torch-mlir does not support optional tensors as inputs. What you can do to circumvent this is to wrap your module inside another module:

```python
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.embeddedbag = nn.EmbeddingBag(4, 2, mode='sum')

    def forward(self, x, y):
        return self.embeddedbag(x, y, None)

module = MyModule()

module = torch_mlir.compile(module,
    list([input_e, offsets]),
    output_type=torch_mlir.OutputType.TORCH,
    use_tracing=False)
```

This will import into torch-mlir, but there errors when lowering to torch-backend because the IR has control flow in it, which is currently not supported

**Comment by ramiro050** [comment]
The control flow issue can be avoided by using tracing. Also, support for `aten.embedding_bag.padding_idx` needs to be added in torch-mlir to fully lower `nn.EmbeddingBag`

**Comment by JoshuaQSH** [comment]
> The control flow issue can be avoided by using tracing. Also, support for `aten.embedding_bag.padding_idx` needs to be added in torch-mlir to fully lower `nn.EmbeddingBag`

Thank you, that actually helps a lot. I think I can close this issue so far.
