### ISSUE TITLE
`torch_mlir.compile` error with jit.trace when using `TensorPlaceholder` for example_args (related to dynamic shape support)

### ISSUE THREAD

**Issue by sjain-stanford** [llvm/torch-mlir#997]
I am facing two issues that are likely inter-dependent.

### First Issue: 
This [line of code](https://sourcegraph.com/github.com/llvm/torch-mlir@5888c4f7dc5aad504ef8c77442ebbf3c0393623c/-/blob/python/torch_mlir/__init__.py?L120
) results in an exception when `example_args` is provided as `TensorPlaceholder`.

```
RuntimeError: Type 'Tuple[__torch__.TensorPlaceholder]' cannot be traced. Only Tensors and (possibly nested) Lists, Dicts, and Tuples of Tensors can be trace
```

Is `TensorPlaceholder` not intended to be used for `torch.jit.trace`, and only for the later steps during torch-mlir import (collecting `forward_annotation` for `class_annotator` etc)? If so, how can I use dynamic shapes when tracing, since the shapes are statically annotated during `jit.trace` and those get carried over to the torch dialect upon import? (this leads to the second issue below)
 
### Second Issue:
How can I get the `dynamic_axes` support when `use_tracing=True`?

For this simple model: 
```python3
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()

    def forward(self, x, y):
        x = F.relu(x)
        z1 = x + y
        z2 = torch.sum(z1, 0)
        return z1, z2
```
I first traced (`jit.trace`) with usual `torch.Tensor`s (`example_args = (torch.randn(8, 8), torch.randn(8))`), and modified [this line](https://sourcegraph.com/github.com/llvm/torch-mlir@5888c4f7dc5aad504ef8c77442ebbf3c0393623c/-/blob/python/torch_mlir/__init__.py?L131) to provide `dynamic_axes=[0]` to the `TensorPlaceholder.like` method. This seems to create the right input tensors (with dynamic dims) but then casts back to static shapes:
```
  func.func @forward(%arg0: !torch.vtensor<[?,8],f32>, %arg1: !torch.vtensor<[?],f32>) -> (!torch.vtensor<[8,8],f32>, !torch.vtensor<[8],f32>) {
    %0 = torch.tensor_static_info_cast %arg0 : !torch.vtensor<[?,8],f32> to !torch.vtensor<[8,8],f32>
    %1 = torch.tensor_static_info_cast %arg1 : !torch.vtensor<[?],f32> to !torch.vtensor<[8],f32>
    %2 = torch.aten.relu %0 : !torch.vtensor<[8,8],f32> -> !torch.vtensor<[8,8],f32>
```

@asaadaldien believes these static casts should be dropped from jit_import when using tracing, and only do the casting for constants (e.g. weights which are scripting / tracing invariant).

For reference here are the [full dumps](https://gist.github.com/sjain-stanford/c97dcc2e41e350b04633feb8f96a40a4) for Torchscript (`ts.txt`), raw imported TorchDialect module (`raw.mlir`) and after TS-to-Torch pipeline (`torch.mlir`).

Discord thread: https://discord.com/channels/636084430946959380/742573221882364009/991793938639892490

**Comment by pashu123** [comment]
I was also having the same issue when passing `TensorPlaceholder` instead of `torch.tensor` and `use_tracing=True` at the same time. @silvasean Can we pass a list of dynamic_axis instead of TensorPlaceholder? Somehow the `torch.tensor` should be preserved for `torch.jit.trace` to work.

**Comment by ramiro050** [comment]
For the second issue, I think we are limited by Pytorch. The tracer hardcodes the shapes to ensure correctness, since the `forward` method might have some control flow based on the shapes of the inputs. Since by the time the TS graph reaches torch-mlir we don't know if there was originally any input shape dependent control flow in the original module, there is no way for us to know if it is safe to remove the casts. The only way I can think of adding dynamic support for this in torch-mlir would be to have the user tell us which input tensors are used for control flow inside the function and which are not.

Another option would be to ask pytorch to allow generating a graph with dynamic shapes whenever `torch.jit.trace` does not encounter any control flow.

**Comment by asaadaldien** [comment]
@ramiro050 The traced TS imported to torch-mlir is control flow free by construction, once imported (with static casts removed) to torch-mlir I believe we can use the same machinery to resolve the shapes from user annotated inputs.
Did I miss something ? Is there cases where the  traced graph will be generated in a way such that we can't infer the shapes and we have to relay on torch's casts ?

**Comment by silvasean** [comment]
The trace never has control flow, but the original Python code might. Here is an example where torch.onnx.export creates an incorrect lowering:

```
import torch

class SumModule(torch.nn.Module):
    def forward(self, x):
        if x.shape[0] == 3:
            x = x + 1
        return torch.sum(x, dim=1)


onnx = torch.onnx.export(SumModule(), (torch.ones(2, 2),), "/tmp/onnx.pbtxt",
                  input_names=["x"], output_names=["sum"],
                  dynamic_axes={
                      # dict value: manually named axes
                      "x": {0: "my_custom_axis_name"},
                      # list value: automatic names
                      "sum": [0],
                  }, verbose=True)
```


Output:
```
/tmp/repro2.py:5: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if x.shape[0] == 3:
Exported graph: graph(%x : Float(*, 2, strides=[2, 1], requires_grad=0, device=cpu)):
  %onnx::ReduceSum_1 : Long(1, strides=[1], device=cpu) = onnx::Constant[value={1}, onnx_name="Constant_0"]()
  %sum : Float(*, strides=[1], requires_grad=0, device=cpu) = onnx::ReduceSum[keepdims=0, onnx_name="ReduceSum_1"](%x, %onnx::ReduceSum_1) # /tmp/repro2.py:6:0
  return (%sum)
```

The graph will not compute the right value for an input of size 3. To be fair, it does give a warning. We could provide a similar user experience I presume.

**Comment by silvasean** [comment]
I generally view this more as a feature request for `torch.jit.trace` to natively support `dynamic_axes`. We can hack around it, but there will always be issues.

**Comment by silvasean** [comment]
The casts aren't really the problem -- the static shapes have been propagated through the whole IR at the point we see it. It feels hacky to me to erase those and reinfer them (which is what torch.onnx.export does).

However, if you just want a trace with no shapes (to be inferred later), you can also use torch.fx.symbolic_trace:

```
import torch
import torch_mlir
from torch_mlir import TensorPlaceholder, OutputType
from torch.fx import symbolic_trace

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()

    def forward(self, x, y):
        x = torch.nn.functional.relu(x)
        z1 = x + y
        z2 = torch.sum(z1, 0)
        return z1, z2


example_args = (torch.randn(8, 8), torch.randn(8))

symbolic_traced = symbolic_trace(Net())
print("symbolic traced\n", symbolic_traced.graph)

dynamic_example_args = [
    TensorPlaceholder.like(example_args[0], dynamic_axes=[1]),
    TensorPlaceholder.like(example_args[1], dynamic_axes=[0]),
]
mlir = torch_mlir.compile(symbolic_traced, dynamic_example_args, OutputType.TORCH)
print("\ntorch output type\n", mlir)
```


```
symbolic traced
 graph():
    %x : [#users=1] = placeholder[target=x]
    %y : [#users=1] = placeholder[target=y]
    %relu : [#users=1] = call_function[target=torch.nn.functional.relu](args = (%x,), kwargs = {inplace: False})
    %add : [#users=2] = call_function[target=operator.add](args = (%relu, %y), kwargs = {})
    %sum_1 : [#users=1] = call_function[target=torch.sum](args = (%add, 0), kwargs = {})
    return (add, sum_1)

torch output type
 module attributes {torch.debug_module_name = "Net"} {
  func.func @forward(%arg0: !torch.vtensor<[8,?],f32>, %arg1: !torch.vtensor<[?],f32>) -> (!torch.vtensor<[8,?],f32>, !torch.vtensor<[?],f32>) {
    %int0 = torch.constant.int 0
    %false = torch.constant.bool false
    %int1 = torch.constant.int 1
    %none = torch.constant.none
    %0 = torch.aten.relu %arg0 : !torch.vtensor<[8,?],f32> -> !torch.vtensor<[8,?],f32>
    %1 = torch.aten.add.Tensor %0, %arg1, %int1 : !torch.vtensor<[8,?],f32>, !torch.vtensor<[?],f32>, !torch.int -> !torch.vtensor<[8,?],f32>
    %2 = torch.prim.ListConstruct %int0 : (!torch.int) -> !torch.list<int>
    %3 = torch.aten.sum.dim_IntList %1, %2, %false, %none : !torch.vtensor<[8,?],f32>, !torch.list<int>, !torch.bool, !torch.none -> !torch.vtensor<[?],f32>
    return %1, %3 : !torch.vtensor<[8,?],f32>, !torch.vtensor<[?],f32>
  }
}
```

Does that work for your use case?

**Comment by asaadaldien** [comment]
Awesome! thanks @silvasean I think that might work for our use case.
 
@sjain-stanford I believe we can run fx-tracing  then get the TS post tracing for our use cases ?

@silvasean Regarding dropping shape information when tracing and use the same shape-infer, e.g here the TS of the example ?

```
module __torch__.convnet_torch_mlir_test.Net {
  parameters {
  }
  attributes {
    training = False
    _is_full_backward_hook = None
  }
  methods {
    method forward {
      graph(%self : __torch__.convnet_torch_mlir_test.Net,
            %x.1 : Float(8, 8, strides=[8, 1], requires_grad=0, device=cpu),
            %y : Float(8, strides=[1], requires_grad=0, device=cpu)):
        %x : Float(8, 8, strides=[8, 1], requires_grad=0, device=cpu) = aten::relu(%x.1)
        %6 : int = prim::Constant[value=1]()
        %z1 : Float(8, 8, strides=[8, 1], requires_grad=0, device=cpu) = aten::add(%x, %y, %6)
        %8 : int = prim::Constant[value=0]()
        %9 : int[] = prim::ListConstruct(%8)
        %10 : bool = prim::Constant[value=0]()
        %11 : NoneType = prim::Constant()
        %12 : Float(8, strides=[1], requires_grad=0, device=cpu) = aten::sum(%z1, %9, %10, %11)
        %13 : (Float(8, 8, strides=[8, 1], requires_grad=0, device=cpu), Float(8, strides=[1], requires_grad=0, device=cpu)) = prim::TupleConstruct(%z1, %12)
        return (%13)
  
    }
  }
  submodules {
  }
}
```

What are we getting by keeping (or importing) shape information ?

**Comment by sjain-stanford** [comment]
Thanks @silvasean and @asaadaldien . This is an interesting workaround indeed to use FX symbolic trace to get trace simplifications (remove control flow etc), and continue using `jit.script` for dynamic shape support in torch-mlir. This is something we did previously consider on our internal workloads at Cruise - the main limitation though is a lot of them are not fully FX traceable (we could use`fx.wrap` and leaf modules etc but that prevents the same tracer simplifications on the wrapped code so not very helpful). We believe this could be resolved once we move to the `TorchDynamo` frontend, as we wouldn't have to worry about coverage limitations there. For now, could we entertain @asaadaldien 's proposal which is to (legally) strip the shape information from a traced TS during import to Torch dialect? At least de-risk and see how far we can get with it?

**Comment by sjain-stanford** [comment]
I think we'd still need to ensure is that the `jit.trace` is warnings-free.

**Comment by silvasean** [comment]
@pashu123 - that seems like a bug in PyTorch that it is dropping shape information. I filed a bug upstream: https://github.com/pytorch/pytorch/issues/81063

**Comment by silvasean** [comment]
I will add this feature after we land https://github.com/llvm/torch-mlir/pull/1001 which adds ImportOptions -- should be easy to add after that.
